### ISSUE TITLE
Language support

### ISSUE THREAD

**Issue by Sunser** [ONLYOFFICE/onlyoffice-owncloud#100]
希望此插件能直接支持中文语言，并不需要自行汉化。以及关于文件加密后无法使用的问题。

**Comment by Sunser** [comment]
I hope this plugin will support the Chinese language directly and don't need to do it yourself. And questions that cannot be used after file encryption.

**Comment by alexandervnuchkov** [comment]
Chinese is available in ONLYOFFICE Document Server version 5.0. The owncloud plugin is not translated into Chinese, if you want to contribute with the translation, feel free to contact me. 

> And questions that cannot be used after file encryption.
Which encryption do you mean here?

**Comment by LinneyS** [comment]
This issue was closed due to no response.
