### ISSUE TITLE
Sign cannot be verified

### ISSUE THREAD

**Issue by danielepercivaldi** [ONLYOFFICE/onlyoffice-owncloud#101]
Cannot install version 1.1.4 on ubuntu 14.04 + oc 9.1.6.
Oc control panel says that the code sign of the app cannot be verified.

**Comment by ibnpetr** [comment]
@danielepercivaldi 
Please make sure that you are using [the signed version](https://github.com/ONLYOFFICE/onlyoffice-owncloud/releases/download/v1.1.4/onlyoffice-owncloud.tar.gz) of the connector

**Comment by danielepercivaldi** [comment]
@ibnpetr The signed version you linked works fine. The version you can get from apps.owncloud.org and that you can install through oc control panel (I think its the same) does not work.

Thanks.

**Comment by LinneyS** [comment]
Updated app with signature on apps.owncloud.org
