### ISSUE TITLE
I can not access to ONLYOFFICE.

### ISSUE THREAD

**Issue by ivanoterouvigo** [ONLYOFFICE/onlyoffice-owncloud#104]
I installed connector only office but when I try to create a document it say.

You can not access to ONLYOFFICE

I check permissions of this folder in /var/www/cloud/apps/

and this is the result:

www-data www-data onlyoffice/

Could you help me to solve this?

**Comment by alexanderonlyoffice** [comment]
Hello @ivanoterouvigo 

Could you please specify where ONLYOFFICE Document Server is installed and the connection settings you have used for it in administrator section of NextCloud/OwnCloud.

**Comment by ivanoterouvigo** [comment]
Hello @alexanderonlyoffice.

I shared with you this info.
https://own.campusdomar.es/cloud/shared/

![collaboraoffice_v6_final_049](https://user-images.githubusercontent.com/11814769/30535619-3fd49aa4-9c63-11e7-9ede-46f50e5e0ac4.png)

Thanks

**Comment by alexanderonlyoffice** [comment]
Please note that we do not offer support for Collabora application. Please send us the connection settings for ONLYOFFICE.

**Comment by LinneyS** [comment]
Have you configured the settings?
working?
Can I close the issue?
