### ISSUE TITLE
Sub-process /usr/bin/dpkg returned an error code (1)

### ISSUE THREAD

**Issue by ivanoterouvigo** [ONLYOFFICE/onlyoffice-owncloud#105]
Configurando onlyoffice-communityserver (9.1.1.418) ...
mysql: [Warning] Using a password on the command line interface can be insecure.
mysql: [Warning] Using a password on the command line interface can be insecure.
mysql: [Warning] Using a password on the command line interface can be insecure.
mysql: [Warning] Using a password on the command line interface can be insecure.
mysql: [Warning] Using a password on the command line interface can be insecure.
mysql: [Warning] Using a password on the command line interface can be insecure.
mysql: [Warning] Using a password on the command line interface can be insecure.
mysql: [Warning] Using a password on the command line interface can be insecure.
mysql: [Warning] Using a password on the command line interface can be insecure.
mysql: [Warning] Using a password on the command line interface can be insecure.
mysql: [Warning] Using a password on the command line interface can be insecure.
mysql: [Warning] Using a password on the command line interface can be insecure.
mysql: [Warning] Using a password on the command line interface can be insecure.
mysql: [Warning] Using a password on the command line interface can be insecure.
/sbin/apparmor_parser
dpkg: error al procesar el paquete onlyoffice-communityserver (--configure):
 el subproceso instalado el script post-installation devolvió el código de salida de error 1
Se encontraron errores al procesar:
 onlyoffice-communityserver
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by ShockwaveNN** [comment]
Please, file bugs related to `onlyoffice-communityserver` in https://github.com/ONLYOFFICE/CommunityServer/issues

**Comment by alexeybannov** [comment]
What operating system are you using?

**Comment by ivanoterouvigo** [comment]
Sorry, I wrote this issue in :
https://github.com/ONLYOFFICE/CommunityServer/issues

Thi is it.
https://github.com/ONLYOFFICE/CommunityServer/issues/75

Thanks in advance
