### ISSUE TITLE
Formatting buttons not working and return to file view

### ISSUE THREAD

**Issue by svengit** [ONLYOFFICE/onlyoffice-owncloud#106]
I made 2 separate installs now with the same result. There are several formatting buttons in the top bar that do not work (and do not provide a tooltip on hover) and when you click them, they close the document.

 * in docx files every button left of superscript is broken
 * in xlsx files every button left of 'background color' is broken
 * in pptx files every button left of 'italic' is broken

There is nothing in the log files. Not a single line.

I tried 2 different installations (Oc 10.0.2, newest Onlyoffice App, newest Documentserver) and 5+ different clients/browsers

**Comment by ShockwaveNN** [comment]
Please duplicate your issue in https://github.com/ONLYOFFICE/DocumentServer/issues
And specify your browsers, os and display resolution.
This is pretty strange problem

**Comment by ShockwaveNN** [comment]
On second thought, this may be somehow related to integration with OwnCloud, so keep it here by now, do not duplicate.

**Comment by svengit** [comment]
Ok, tried with:
 * Windows 10 EN 64-Bit, 1920x1080, Firefox 55.0.3
 * 3 other Windows Systems during a presentation
 * Ubuntu 14.04 64 Bit, 1920x1200, Firefox 55.0.2
 * Ubuntu 14.04 64 Bit, 1920x1200, Chromium Version 60.0.3112.113 (Developer Build) Built on Ubuntu , running on Ubuntu 14.04 (64-bit)
All with the exact same results

Is there a quick and easy way to use the documentserver in an owncloud independent way so I can see if it's the owncloud integration or the documentserver?

**Comment by ShockwaveNN** [comment]
You can use nodejs integration example - https://github.com/ONLYOFFICE/document-server-integration/tree/master/web/documentserver-example/nodejs
Could you open `Chrome debug tool`, point out on object, that hover over all those button (I think there should be one) and show us a screenshot of debugger `Elements` tab

**Comment by svengit** [comment]
I think I found the problem and I am very sorry for wasting your time.
The logo div of the theme was too big and concealed those buttons while being invisible.

**Comment by ShockwaveNN** [comment]
@svengit It's fine. Just to be sure - you mention `logo div` - is this a `owncloud` log div, or is that `onlyoffice` logo?

**Comment by svengit** [comment]
It's the owncloud logo. It's called '.logo-icon'.

Maybe there is a way to enforce onlyoffice to be on top, so others don't make the same stupid mistake? Other things that were 'under' the div did not have problems

**Comment by ShockwaveNN** [comment]
@svengit Sorry, don't think so
