### ISSUE TITLE
Problems with installation of  ONLYOFFICE

### ISSUE THREAD

**Issue by ivanoterouvigo** [ONLYOFFICE/onlyoffice-owncloud#107]
Hellow everyone!

I am trying to install and use one of dockers with onlyoffice and owncloud or nextcloud configuration.

Firs of all I follow this video tutorial.
https://www.youtube.com/watch?v=7kiJ99tmsi0&feature=youtu.be

When I add only office to source.list. and after do.
sudo apt-get update.

It has following report.

```
W: Error de GPG: http://download.onlyoffice.com/repo/debian squeeze InRelease: Las firmas siguientes no se pudieron verificar porque su clave pública no está disponible: NO_PUBKEY 8320CA65CB2DE8E5
W: El repositorio «http://download.onlyoffice.com/repo/debian squeeze InRelease» no está firmado.
N: Los datos de un repositorio como este no se pueden autenticar y por tanto su uso es potencialmente peligroso.
N: Vea la página de manual apt-secure(8) para los detalles sobre la creación de repositorios y la configuración de usuarios.
W: http://archive.ubuntu.com/ubuntu/dists/precise/Release.gpg: Signature by key 630239CC130E1A7FD81A27B140976EAF437D05B5 uses weak digest algorithm (SHA1)
```

![error_onlyoffice_001](https://user-images.githubusercontent.com/11814769/31070326-2e60f83c-a760-11e7-964a-d63bbae5b891.png)

Could you help me with this?

I try installation of onlyoffice but it reports this.

```
docker@docker-Box:~$ sudo apt-get install onlyoffice-documentserver
Leyendo lista de paquetes... Hecho
Creando árbol de dependencias       
Leyendo la información de estado... Hecho
No se pudieron instalar algunos paquetes. Esto puede significar que
usted pidió una situación imposible o, si está usando la distribución
inestable, que algunos paquetes necesarios aún no se han creado o se
han sacado de «Incoming».
La siguiente información puede ayudar a resolver la situación:

Los siguientes paquetes tienen dependencias incumplidas:
 onlyoffice-documentserver : Depende: nodejs (>= 6.9.1) pero no va a instalarse
E: No se pudieron corregir los problemas, usted ha retenido paquetes rotos.
```

**Comment by ShockwaveNN** [comment]
@ivanoterouvigo Hi, this video is pretty old and not actual.
Use this instruction
http://helpcenter.onlyoffice.com/server/linux/document/linux-installation.aspx

**Comment by ShockwaveNN** [comment]
@ivanoterouvigo We added info in video description about deprecation of video

**Comment by ivanoterouvigo** [comment]
Thanks, It works fine now.
What is the best way to connect it with onwcloud/nextcloud service?

**Comment by LinneyS** [comment]
You can try https://github.com/ONLYOFFICE/docker-onlyoffice-owncloud

**Comment by ivanoterouvigo** [comment]
Thanks @LinneyS 
It looks that work fine.

**Comment by ivanoterouvigo** [comment]
Do you know what are the limit of cocurrent users or opened documents?

**Comment by ibnpetr** [comment]
@ivanoterouvigo 
Opensource version has a 20 editing sessions limitation (every additional editing session will fall back to a "view mode")

**Comment by ivanoterouvigo** [comment]
@ibnpetr @LinneyS @ShockwaveNN 
What about add more apps?
I would like to add my own app.
Is there any way of what are the best steps to create and add some simple app to my onwcloud?

**Comment by ibnpetr** [comment]
@ivanoterouvigo  
Feel free to contact owncloud team to discuss all possible ways to create your own apps.

**Comment by anteldan** [comment]
> @ivanoterouvigo Hi, this video is pretty old and not actual.
> Use this instruction
> http://helpcenter.onlyoffice.com/server/linux/document/linux-installation.aspx

Hi, 
I was following instructions from that page and I met a deadend:
```
:~$ sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys CB2DE8E5
Executing: /tmp/apt-key-gpghome.W28d3s1RsL/gpg.1.sh --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys CB2DE8E5
gpg: [don't know]: invalid packet (ctb=02)
gpg: keydb_get_keyblock failed: Valeur non trouvée
gpg: [don't know]: invalid packet (ctb=02)
gpg: /tmp/apt-key-gpghome.W28d3s1RsL/pubring.gpg: copy to '/tmp/apt-key-gpghome.W28d3s1RsL/pubring.gpg.tmp' failed: Paquet incorrect
gpg: erreur d'écriture du porte-clefs « /tmp/apt-key-gpghome.W28d3s1RsL/pubring.gpg » : Paquet incorrect
gpg: erreur de lecture de « [stream] » : Paquet incorrect
gpg:       Quantité totale traitée : 0
```

Also tried:
```
$ wget http://download.onlyoffice.com/repo/onlyoffice.key
$ sudo apt-key add onlyoffice.key 
```
but same errors...

Any hints ?

**Comment by jakubfijolek** [comment]
I have exactly same issue.

![Screenshot from 2020-11-02 12-26-30](https://user-images.githubusercontent.com/19429579/97863055-ad557400-1d06-11eb-918c-8f35f906bea6.png)
![Screenshot from 2020-11-02 12-26-06](https://user-images.githubusercontent.com/19429579/97863057-adee0a80-1d06-11eb-87f2-3ea959bac2f7.png)

**Comment by ShockwaveNN** [comment]
@jakubfijolek [This](https://unix.stackexchange.com/a/401548/80041) may be the solution
