### ISSUE TITLE
Onlyoffice behind Apache reverse proxy and owncloud 

### ISSUE THREAD

**Issue by r4a5a88** [ONLYOFFICE/onlyoffice-owncloud#108]
Hi Community,

I installed onlyoffice on a Server behind a apache revese proxy.
due to the server having multiple other websites behind it including an owncloud I can't put onlyoffice on / 
I  put it ot /onlyoffice but the onlyoffice server alway redirects it to /welcome , which I added in the proxy but then it tells me : "Something went wrong during installation"
I tried to apply the apache configuration from the onlyoffice website but it didn't work. 
When I entered the website I got  hostname , hostename/welcome  
Is ther a configration file or spot in the database where I can change the sitename?

**Comment by alexeybannov** [comment]
You can more details with an example config for Apache to describe the problem? In Docker we used as a proxy server with nginx https://github.com/ONLYOFFICE/docker-onlyoffice-owncloud/blob/master/nginx.conf.

**Comment by agolybev** [comment]
Hi @r4a5a88, 
You can see how to install documentserver in virtual path [here](https://helpcenter.onlyoffice.com/server/document/document-server-proxy.aspx).

**Comment by r4a5a88** [comment]
hi @agolybev 
I used that configuration on my server. 
It didn't work

**Comment by r4a5a88** [comment]
thats the apache conf for the onlyoffice site and a test-owncloud i am using to test it
```
Alias testcloud /testcloud
Alias onlyoffice /onlyoffice

#SetEnvIf Host "^(.*)$" THE_HOST=$1
#RequestHeader setifempty X-Forwarded-Proto https
#RequestHeader setifempty X-Forwarded-Host %{THE_HOST}e
#ProxyAddHeaders Off

ProxyPass /testcloud http://192.168.13.75/owncloud
    	ProxyPassReverse /testcloud http://192.168.13.75/owncloud

		
		
ProxyPassMatch (.*)(\/websocket)$ "ws://192.168.13.74/onlyoffice/$1$2"
ProxyPass /onlyoffice "http://192.168.13.74/"
ProxyPassReverse /onlyoffice "http://192.168.13.74"
ProxyPass	/welcome	http://192.168.13.74/welcome
ProxyPassReverse	/welcome http://192.168.13.74/welcome
```

**Comment by agolybev** [comment]
@r4a5a88 
Fisrt I'm not sure for 
```
Alias testcloud /testcloud
Alias onlyoffice /onlyoffice
```
Because you use this key word below in the config
Next,  this statements are required:
```
  SetEnvIf Host "^(.*)$" THE_HOST=$1
  RequestHeader setifempty X-Forwarded-Proto http
  RequestHeader setifempty X-Forwarded-Host %{THE_HOST}e
  RequestHeader edit X-Forwarded-Host (.*) $1${VPATH}
  ProxyAddHeaders Off
```  
Finaly, I think you  don't have to proxy `welcome` path by this:
```
ProxyPass	/welcome	http://192.168.13.74/welcome
ProxyPassReverse	/welcome http://192.168.13.74/welcome
```

**Comment by agolybev** [comment]
Try using this config: 
```
Listen 80
LoadModule authn_core_module modules/mod_authn_core.so
LoadModule authz_core_module modules/mod_authz_core.so
LoadModule unixd_module modules/mod_unixd.so
LoadModule proxy_module modules/mod_proxy.so
LoadModule proxy_http_module modules/mod_proxy_http.so
LoadModule proxy_wstunnel_module modules/mod_proxy_wstunnel.so
LoadModule headers_module modules/mod_headers.so
LoadModule setenvif_module modules/mod_setenvif.so

<IfModule unixd_module>
  User daemon
  Group daemon
</IfModule>

Define VPATH /onlyoffice
Define DS_ADDRESS 192.168.13.74

<Location ${VPATH}>
  Require all granted
  SetEnvIf Host "^(.*)$" THE_HOST=$1
  RequestHeader setifempty X-Forwarded-Proto http
  RequestHeader setifempty X-Forwarded-Host %{THE_HOST}e
  RequestHeader edit X-Forwarded-Host (.*) $1${VPATH}
  ProxyAddHeaders Off
</Location>

ProxyPassMatch ^\${VPATH}(.*)(\/websocket)$ "ws://${DS_ADDRESS}/$1$2"
ProxyPass ${VPATH} "http://${DS_ADDRESS}/"
ProxyPassReverse ${VPATH} "http://${DS_ADDRESS}/"
```
It won't proxy to owncloud, but you can test proxy to the documentserver.

**Comment by r4a5a88** [comment]
thanks for the conf.  
It works. I get a green screen. 
One more problem. In my cloud , when I open a document , I only see a white screen.

**Comment by r4a5a88** [comment]
![grafik](https://user-images.githubusercontent.com/22817846/31539368-a7f9842e-b008-11e7-941c-b41a7fe6b7c7.png)

**Comment by agolybev** [comment]
Hi @r4a5a88.
Yes this config is suitable only for HTTP traffic. Try changing string `RequestHeader setifempty X-Forwarded-Proto http` to `RequestHeader setifempty X-Forwarded-Proto https`

**Comment by r4a5a88** [comment]
Vielen Herzlichen Dank @agolybev  
Es funktioniert :)
