### ISSUE TITLE
Errors while trying to use ONLYOFFICE with Google Cloud Platform

### ISSUE THREAD

**Issue by mjmalec** [ONLYOFFICE/onlyoffice-owncloud#110]
Hello!

I have recently installed ownCloud on GCP (Google Cloud Platform) and it is working great. I created a VM just to host document server on (Ubuntu 17.04), but it doesn't seem to be working. I followed the steps (https://helpcenter.onlyoffice.com/server/linux/document/linux-installation.aspx) perfectly and even doing that, ONLYOFFICE document server still isn't working. When I click, "Save" in the ONLYOFFICE settings, I receive this error, "Error when trying to connect (Error occurred in the document service: Error while downloading the document file to be converted.)"

Any help would be much appreciated!

Best Regards,
Matt

**Comment by alexanderonlyoffice** [comment]
@mjmalec, Hello Matt,

It seems that your OwnCloud Server  is not accessible from the server with ONLYOFFICE Editors. Please try to use **_wget_** command to check the accessibility of OwnCloud server from your server with editors.

**Comment by mjmalec** [comment]
How would I do that?

**Comment by alexanderonlyoffice** [comment]
@mjmalec,  

Use **_wget_** command to check the accessibility of OwnCloud. Open terminal on the server with document server, enter **wget http://OwnCloud-server-address/** and you will be notified if there is a response from server.

**Comment by mjmalec** [comment]
Would I do that on my ownCloud server, or the ONLYOFFICE server?

**Comment by alexanderonlyoffice** [comment]
@mjmalec, please do it on the server with ONLYOFFICE document server.

**Comment by LinneyS** [comment]
Could you please specify if the problem recurs or we can close the topic.

**Comment by mjmalec** [comment]
That was like many months ago. The issue has been already resolved.
