### ISSUE TITLE
.doc /  .xls documents

### ISSUE THREAD

**Issue by r4a5a88** [ONLYOFFICE/onlyoffice-owncloud#111]
Hi onlyoffice

great app :)

One question: What do I have to install or configure in my owncloud so onlyoffice opens .odt .doc and .xls documents? Do I have to install it on the documentsserver or the owncloud

**Comment by alexanderonlyoffice** [comment]
Hello @r4a5a88,

You can use OwnCloud ONLYOFFICE Integration app to view and edit files using ONLYOFFICE editors. Please find more information under this [link](https://api.onlyoffice.com/editors/owncloud).

**Comment by r4a5a88** [comment]
Hi @alexanderonlyoffice

I am using the Integration app. in ithe app configuration I can only choose newer versions of office documents.

![screenshot](https://user-images.githubusercontent.com/22817846/31927519-c3e9a710-b894-11e7-8aa3-a85b1b0e4e7d.png)

Perhaps it something in owncould

**Comment by alexanderonlyoffice** [comment]
Hello @r4a5a88,

The above mentioned formats .odt, .doc, .xls will be converted in the .docx and .xlsx formats. If this file is in your documents, it will appear in the converted format. If the file is shared with you, it will appear in '_All files'_ folder. Click on the action menu (three dots icon) of the file and choose "**Open in ONLYOFFICE**" option to open and edit it.

**Comment by r4a5a88** [comment]
thank you . that solves it :)
