### ISSUE TITLE
Issue with External Storage when using Log-In Credentials, Save in Session

### ISSUE THREAD

**Issue by shieldsit** [ONLYOFFICE/onlyoffice-owncloud#112]
When accessing a Windows share as external storage and using log-in credentials, save in session setting on the external storage OnlyOffice is having an issue.  It appears to be a permissions problem but it's very strange.

We are using the LDAP backend so the username and passwords are the exact same using log-in credentials or username and password, yet OO errors when using the former.  The strange thing is, if I mount the storage with username and password, open a document (which works fine) and then mount the storage as log-in creds OO has no trouble.  It's only documents that have not been opened before, and when you try to open a document that hasn't been opened when mounted using username and password OO displays a "Download failed, press OK to return to document list"

Can anyone help me figure this issue out?  It will force me to setup hundreds of external mounts manually when it could be done easily if this issue wasn't present.  Thank you!

**Comment by shieldsit** [comment]
This is the only error I can find, if there is somewhere else to look please let me know!

`[ERROR] nodeJS - error downloadFile:url=http://164.4.245.200/owncloud/index.php/apps/onlyoffice/download?doc=ZW1sd3I0Wm4xakRYbHBBU3QxbHJmQXRZeUloc3hDODBzVXNTd1pub2JGST0/eyJmaWxlSWQiOjI4ODc0LCJ1c2VySWQiOiJCN0RDMEQ5OC0wMTM3LTRCNTUtOTc1Ny1DODBFNDBEQkQzRDIiLCJhY3Rpb24iOiJkb3dubG9hZCJ9;attempt=3;code:undefined;connect:undefined;(id=28874_1508769349)
Error: Error response: statusCode:404 ;body:
{"message":"Files not found"}
    at Request._callback (/var/www/onlyoffice/documentserver/server/Common/sources/utils.js:243:20)
    at Request.self.callback (/var/www/onlyoffice/documentserver/server/Common/node_modules/request/request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/var/www/onlyoffice/documentserver/server/Common/node_modules/request/request.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/var/www/onlyoffice/documentserver/server/Common/node_modules/request/request.js:1091:12)
    at IncomingMessage.g (events.js:292:16)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
`

**Comment by alexanderonlyoffice** [comment]
Hello @shieldsit,

Could you please send us full logs of OwnCloud to support@onlyoffice.com

**Comment by alexanderonlyoffice** [comment]
Hello @shieldsit,

We have received your log. According to the information from it, you are using incorrect internal URL addresses for both OwnCloud and document server in the administrator panel of OwnCloud.

**Comment by shieldsit** [comment]
Thank you for getting back to me!  Here is what is showing in my connector
settings in Owncloud.  Do you see where I've made a mistake?  We are
currently only testing this internally so the IP's are private.

[image: Inline image 1]

**Comment by alexanderonlyoffice** [comment]
@shieldsit, unfortunately, we can not see the attached image. You can send it to support@onlyoffice.com, if this is a matter of security.

**Comment by alexanderonlyoffice** [comment]
@shieldsit,  please check if the document server has an access to OwnCloud server address using **_wget_** command.  

As it is shown on the screenshot the internal address and the common address of document server are the same, then you can try not to use internal addresses. Click on the "**Advanced server settings**" to close this section.

**Comment by shieldsit** [comment]
Thanks for the help!  Is there something I should try to retrieve from the
OwnCloud server with wget?  Can you give me an example to try to make sure
I do it correctly?

I've tried with and without the internal address filled in.  It hasn't made
any difference.

**Comment by alexanderonlyoffice** [comment]
@shieldsit, use **_wget_** command to check the accessibility of OwnCloud. Open terminal on the server with document server, enter **wget http://OwnCloud-server-address/** and you will be notified if there is a response from server.

**Comment by shieldsit** [comment]
Thanks.  Yes wget works.

root@onlyoffice:~# wget http://164.4.245.200/owncloud
--2017-10-27 09:56:02--  http://164.4.245.200/owncloud
Connecting to 164.4.245.200:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: http://164.4.245.200/owncloud/ [following]
--2017-10-27 09:56:03--  http://164.4.245.200/owncloud/
Reusing existing connection to 164.4.245.200:80.
HTTP request sent, awaiting response... 302 Found
Location: http://164.4.245.200/owncloud/index.php/login [following]
--2017-10-27 09:56:03--  http://164.4.245.200/owncloud/index.php/login
Reusing existing connection to 164.4.245.200:80.
HTTP request sent, awaiting response... 200 OK
Length: 10822 (11K) [text/html]
Saving to: ‘owncloud’

owncloud            100%[===================>]  10.57K  --.-KB/s    in 0s

2017-10-27 09:56:03 (261 MB/s) - ‘owncloud’ saved [10822/10822]

**Comment by alexanderonlyoffice** [comment]
Hello @shieldsit,

Could you please send the screenshot of ONLYOFFICE address settings in OwnCloud administrator section, as we can not see the image you sent in one of the previous messages.

**Comment by LinneyS** [comment]
Please note that with authentication option "Session User" it does not work. Please follow this [link](https://api.onlyoffice.com/editors/owncloud#externalStorage) to find a description of the issue in Known Issues sections.
Duplicate #51
