### ISSUE TITLE
Write to own-/nextcloud on save and/or interval of X seconds/minutes

### ISSUE THREAD

**Issue by christoph-bessei** [ONLYOFFICE/onlyoffice-owncloud#116]
Currently onlyoffice writes a changed file to owncoud10-30 seconds after ALL editors closed the file. 

Is there a possibility that onlyoffice triggers this write every X seconds (if a change occurred)? This would avoid sync problems if someone forgets to close the file, which is a problem if another client is changing the file with the owncloud desktop/mobile client.

**Comment by informatico-madrid** [comment]
+1

**Comment by tavinus** [comment]
+1 as well

This would completely change how onlyoffice operates, but I think it would be better.
Versioning would also benefit a lot from this, since we would have more versions saved.

**Comment by KuenzelIT** [comment]
We also have this problem in our organization, since everyone expects "saving" to be a save of the file to the owncloud server, so that you get the "current" version of the file when downloading.

**Comment by y0va** [comment]
+1

**Comment by IwishIcanFLighT** [comment]
Would appreciate this as well. Depending on the usage, a file could remain opened on a editor for hours or even days. This could lead to versioning missing several iterations of a document which is not ideal.

Although saving a new version every time a change is made would lead to hundreds of versions on nextcloud which would be counterproductive.

An ideal approach would be to autosave the file every x seconds/minutes (could be an admin setting) even if the file is still opened somewhere.

**Comment by KuenzelIT** [comment]
I also vote for auto saving every x seconds or minutes!

**Comment by fmkaiser** [comment]
Until forcesave is solved properly I think I might have found a feasible workaround, namely the _sessionidle_ option in the documentserver _default.json_. 

Setting this to e.g. _60m_ disconnects idle sessions afer an hour, with the users getting a message:

![capture_001_22082018_180846](https://user-images.githubusercontent.com/2922101/44479806-f1865d80-a641-11e8-9a47-16e7c439af99.png)

When there's no more sessions, the document will be saved back to ownCloud. Assuming our users aren't working around the clock, that should make sure that documents are saved back after a finite amount of time, probably at least during the night. 

As a bonus, this also saves some licenses.

@LinneyS What do you think, is that a viable option or could it cause problems in other places?

**Comment by AFrancani** [comment]
+1

**Comment by IwishIcanFLighT** [comment]
@fmkaiser Thanks for this workaround. A real auto-save would still be ideal though.

**Comment by J4RF** [comment]
+1 for automatically writing the document server's cached changes to the backend file at regular intervals

**Comment by LinneyS** [comment]
Hi all!
Try _Keep intermediate versions when editing_ in settings in v6.0.1
