### ISSUE TITLE
Shared editing doesn't work 

### ISSUE THREAD

**Issue by tthdvd** [ONLYOFFICE/onlyoffice-owncloud#119]
Do you want to request a feature or report a bug?
bug
What is the current behavior?
When we open a file toghether, just some people see eachother (not everyone), we didn't find deterministic behavior . It's very strange, becouse two people see eachother and 2 different people see eachother.
If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.
More then one people open the file.
What is the expected behavior?
We should see each other work.
Did this work in previous versions of DocumentServer?
No
DocumentServer version:
5.0.4.15
Operating System:
Ubuntu 16.04.03 LTS
Browser version:
Chrome 61.0.3163.100

**Comment by alexanderonlyoffice** [comment]
Hello @tthdvd, 

It seems that 2 users who see each other have version control plugin on while the 2 others don't have it enabled. Please specify if there is a plugin.

**Comment by tthdvd** [comment]
Dear @alexanderonlyoffice ,

Where should I set up the version control plugin?

Thanks for your reply

**Comment by alexanderonlyoffice** [comment]
Hello @tthdvd,

You can find Versions plugin in Apps section of NextCloud.

**Comment by tthdvd** [comment]
We recognized this issue ,when we convert an odt file what is have special formating (like list elements) to the docx.

**Comment by LinneyS** [comment]
Could you please specify if the problem recurs or we can close the topic
