### ISSUE TITLE
Many errors in the logs

### ISSUE THREAD

**Issue by thfree** [ONLYOFFICE/onlyoffice-owncloud#12]
Все работает, но в логах постоянно это:

Nextcloud 11.0.2
ONLYOFFICE 1.0.1

![image](https://cloud.githubusercontent.com/assets/13134495/23546234/adfa99a2-000f-11e7-8d5e-b636d3571965.png)
```
{"reqId":"pxCvEjy6cF8n0wBOwPzN","remoteAddr":"","app":"PHP","message":"Undefined index: REQUEST_URI at \/***\/cloud\/apps\/onlyoffice\/appinfo\/application.
php#65","level":3,"time":"03 March 2017 09:49:31","method":"--","url":"--","user":"--","version":"11.0.2.7"}
```

**Comment by JohnPerkin** [comment]
Hello!
We tried to reproduce the issue but unfortunately the it did not repeat. We added a check so those errors will not appear any more.
Thank you for the interest in ONLYOFFICE.
