### ISSUE TITLE
OnlyOffice cannot be reached

### ISSUE THREAD

**Issue by BrechtLapage** [ONLYOFFICE/onlyoffice-owncloud#120]
Hi, I have followed this tutorial: 

https://www.linuxbabe.com/ubuntu/integrate-nextcloud-onlyoffice
My document server is up and running and is available through HTTPS. I just cannnot access any documents on my Nextcloud server via OnlyOffice.

I always get the error: ONLYOFFICE cannot be reached. Please contact admin
F12 shows: Failed to load resource: net::ERR_NAME_NOT_RESOLVED docservice/web-apps/apps/api/documents/api.js

I opened up every port on my Nextcloud and OnlyOffice machine that I can think of, I really don't see what I'm doing wrong. I didn't get any error when I added my OnlyOffice machine in Nextcloud, meaning HTTPS should work. I get: "Document Server is running" when I access it through HTTPS.
What am I doing wrong or forgetting?

Thanks in advance.

Greetings

PS: Yesterday I managed to get it working following this tutorial, I had to reinstall everything and now I can't get it to work.

My Nextcloud instance is running via HTTPS and my OnlyOffice server is running via HTTPS. I get "Document Server is running" when I access it via HTTPS. I really don't see what I'm doing wrong.

PS2:  wget https://mydomain/web-apps/apps/api/documents/api.js works, I can access it through the browser too.

**Comment by BrechtLapage** [comment]
FIX: couldn't access api.js from my browser, but I could in incognito modus. Just clear all your temporary files to fix the problem.

**Comment by quentinDupont** [comment]
Hello @BrechtLapage !

I followed the same tutorial. Unfortunately, I have a problem.
When I try to configure OnlyOffice in my Nextcloud. I have the error : Error when trying to connect (Bad Request or timeout error)

When I try to wget between my NC server and my OO server.

Resolving onlyoffice.xxxxx.fr (onlyoffice.xxxxx.fr)... 145.239.xx.xx
Connecting to onlyoffice.xxxxx.fr (onlyoffice.xxxxx..fr)|145.239.xx.xx|:443... connected.
ERROR: The certificate of 'onlyoffice.xxxxx..fr' is not trusted.
ERROR: The certificate of 'onlyoffice.xxxxx..fr' hasn't got a known issuer.

How do I make my NC server trust my OO server ?
I imagine you had to handle this issue ?

Thank a lot in advance for your help :)

**Comment by alexanderonlyoffice** [comment]
Hello @quentinDupont, 

Please see answer from @Klapstuhl in issue #172 and try to add Letsencrypt Intermediate CA certificate on both servers. 

Copy the CA certificate to **/usr/share/ca-certificates** and run `update-ca-certificates` as root.
