### ISSUE TITLE
Onlyoffice fails to start on Nextcloud 13 Beta 1

### ISSUE THREAD

**Issue by onny** [ONLYOFFICE/onlyoffice-owncloud#123]
Hey,
it looks like the Onlyoffice app is not yet supported by Nextcloud Beta 13.
![2017-11-21-203518_swaygrab](https://user-images.githubusercontent.com/757752/33092831-9b3fffda-cefb-11e7-8663-46eecec04770.png)
I'm not sure what is causing the error but maybe it is easy to fix?

Best regards,
Jonas

**Comment by onny** [comment]
In the generated source code of the page, the function OCA.Onlyoffice.OpenEditor doesn't seem to be available:
```
   <script nonce="bkRCUXZ5dGxUOXY2dWdMTDBhN0lCN0U2NkkvTWNYZzFFRDRRaHhveFNkaz06K2tSai9HVTBKYWpLNjBDUHFKMnNicHBJc0w3akNBbFpaUTlKeGtCZkFwZz0=" type="text/javascript">
        OCA.Onlyoffice.OpenEditor ({
            error: "Format do not supported",

            callbackUrl: "",
            key: "",
            title: "",
            url: "",
            userId: "",
            userName: "",
            documentType: "",
        });
    </script>
```

**Comment by onny** [comment]
Since I didn't find any errors in php logging, I decided to do a git bisect and my finding looks quite interesting. Since this commit (https://github.com/nextcloud/server/commit/fb9f13d4c13d2ea3ba70095f36e73c8915fce47f) with the title ``Make page loading faster by deferred script loading``, Onlyoffice app fails to load. I guess this should be a good hint :)

**Comment by ibnpetr** [comment]
@onny 
Thanks a lot, we will perform additional testing with NC, including beta 13

**Comment by fgalz** [comment]
@ibnpetr Any ETA when this will be fixed?

**Comment by DanMittendorf** [comment]
I just ran into this problem. Here is how I fixed it:

`cd into /nextcloud/apps/onlyoffice/templates
mv editor.php editor.bak
wget https://raw.githubusercontent.com/onny/onlyoffice-owncloud/e6286cb95a36909515b5d4ce4d6f24bc5c0bb320/templates/editor.php
chown http:http editor.php #might differ for some!, see this commit here: https://github.com/ONLYOFFICE/onlyoffice-owncloud/pull/129/commits/e6286cb95a36909515b5d4ce4d6f24bc5c0bb320)`

done!

Reload Nextcloud Beta 13 and enjoy

Oh, if you need to activate the OnlyOffice App in Nextcloud just 
`cd nextcloud/apps/onlyoffice/appinfo
nano info.xml
# change line13 to <nextcloud min-version="11" max-version="13"/>
`

**Comment by LinneyS** [comment]
Initialization moved
