### ISSUE TITLE
OnlyOffice incompatible with Circles App

### ISSUE THREAD

**Issue by Peter2121** [ONLYOFFICE/onlyoffice-owncloud#124]
We use [Circles App](https://github.com/nextcloud/circles) in our NextCloud to manage external users. Unfortunately, these users cannot use OnlyOffice, it seems that the OnlyOffice App does not understand such users. It would be nice to add the support of this app.

**Comment by MaxOnlyOffice** [comment]
Hello!
Thank you for your feedback. We will take into account your information.

**Comment by LinneyS** [comment]
Could you please specify if the problem recurs or we can close the topic
