### ISSUE TITLE
Collaborative Editing - Multiple User problem - Nextcloud APP

### ISSUE THREAD

**Issue by ExaconAT** [ONLYOFFICE/onlyoffice-owncloud#125]
**BUG**

**OO Nextloud installed via APT Guide**

- Opening the same document on different Systems Windows 7, 8, 10, Ubuntu / Browsers will result in different amounts of active Users in Chat Plugin OO happens when reloading the page or reopen the document

Please see screenshot.
https://pasteboard.co/GV6rK5T.jpg

**Login as different users and refresh the Document page, or reopen it.**

**Chat Plugin should Update**

**DocumentServer version:** Newest

**Operating System:** Ubuntu 16.04 LTS

**Browser version:** Apache2 NC, NGINX OO

**Comment by alexanderonlyoffice** [comment]
Hello @ExaconAT,

We have tested that case and, unfortunately, we cannot reproduce the problem.

Please specify if the changes made to the document are saved in it.

Send us also screenshots of the IE security settings (as it is shown on the screenshot, but we need screenshots of the entire list of settings - you need to scroll them down and make screenshots, so we can see the whole list).
![document docx - nextcloud - internet explorer - inprivate 2017-11-27 17 32 07](https://user-images.githubusercontent.com/30896337/33308079-1face96c-d42a-11e7-9e59-671e4dfbbd12.png)

**Comment by ExaconAT** [comment]
Thanks its working now.
