### ISSUE TITLE
Error opening large Office files

### ISSUE THREAD

**Issue by ExaconAT** [ONLYOFFICE/onlyoffice-owncloud#127]
Hello,

i've created a 115 mb pptx file (nextcloud plugin -> onlyoffice), and now i cant open it anymore.

Error:

![unbenannt](https://user-images.githubusercontent.com/33482537/33423755-0f639f24-d5ba-11e7-8d5e-d96913eadf5a.png)

Apache2 ini (nextcloud server):
max_execution_time | 600 | 600
max_file_uploads | 50 | 50
max_input_nesting_level | 64 | 64
max_input_time | 60 | 60
max_input_vars | 1000 | 1000
memory_limit | 512M | 1G
post_max_size | 1G | 1024M

BR
René

**Comment by alexanderonlyoffice** [comment]
Hello @ExaconAT,

Please specify if the problem occurs only with this particular file or with all files. 

Send us also the screenshot of ONLYOFFICE address settings in NextCloud administrator section and check logging section for any errors.

**Comment by ExaconAT** [comment]
I think this is a configuration problem in json on the oo server, i can remember that theres a max value for files.
