### ISSUE TITLE
File System on OO Documentserver not shrinking, after closing Documents in NC

### ISSUE THREAD

**Issue by ExaconAT** [ONLYOFFICE/onlyoffice-owncloud#128]
Scenario:
Created some big docx, pptx, xlsx files and opened them in nc.

Problem:
Filesystem usage wont shrink, after closing the documents?

Is there any possible solution?

BR

**Comment by MaxOnlyOffice** [comment]
Hello!
Please specify is this issue actual for now?

**Comment by ExaconAT** [comment]
No its fixed

Von: Maxim Ossipov [mailto:notifications@github.com]
Gesendet: Donnerstag, 15. März 2018 14:35
An: ONLYOFFICE/onlyoffice-owncloud <onlyoffice-owncloud@noreply.github.com>
Cc: René Hofmann <rh@exacon.at>; Author <author@noreply.github.com>
Betreff: Re: [ONLYOFFICE/onlyoffice-owncloud] File System on OO Documentserver not shrinking, after closing Documents in NC (#128)


Hello!
Please specify is this issue actual for now?
