### ISSUE TITLE
Security problem - Cached Files

### ISSUE THREAD

**Issue by ExaconAT** [ONLYOFFICE/onlyoffice-owncloud#131]
**Problem:** 

- Upload, create Office file in Nextcloud: close it.
- Data still remains @ /var/lib/onlyoffice/documentserver/App_Data/cache/files

Is it possible to automatically remove this files?

Already changed the Config in /etc/onlyoffice/documentserver/default.json
for filesCron and documentsCron to 1 hour, but the files wont get wiped.

**Best practice would be: Delete the files after all Users closed the Document.**

**Comment by ibnpetr** [comment]
Hello 
[Here](https://github.com/ONLYOFFICE/server/blob/bc6ea0318908373b750c4e7a328ebd41f92c5446/Common/config/default.json#L113) you can find the section responsible for the garbage collector 
86400 - life time of the file in cache (in seconds)
filesCron - how often garbage collector should check if there are any files in the cache that should be deleted.
Please note that we do not recommend to set the life time less than 10 min.

**Comment by ExaconAT** [comment]
Thanks!! Could you please provide me a configuration with 15 Minutes TTL for the Cached files?

If i'm in the document, there wont be a problem?

**Comment by MaxOnlyOffice** [comment]
Hello!
15 Min = 900 sec
If the document is open cached files of this document will not be deleted. 
Cached files will be deleted after executing filesCron (1 time per hour ("filesCron": "00 00 */1 * * *",))
