### ISSUE TITLE
Encryption with Masterkey OO not working

### ISSUE THREAD

**Issue by ExaconAT** [ONLYOFFICE/onlyoffice-owncloud#134]
Hello,

i've enabled oo and encryption (with master key) -NC 12.0.04 - i'm not able to open, create & open new OO linked documents.

Secret Key enabled.

Help appreciated

BR

**Comment by alexanderonlyoffice** [comment]
Hello @ExaconAT,

Please send us logs of the NextCloud to support@onlyffice.com.

Could you please specify the following: 

>   i'm not able to open

Send us also screenshots of the mentioned issue.

**Comment by ExaconAT** [comment]
> 

Error | no app in context | Can not decrypt this file, probably this is a shared file. Please ask the file owner to reshare the file with you. | 2017-12-04T14:04:39+0100
-- | -- | -- | --
Debug | onlyoffice | Download: 432

<
Error | no app in context | Can not decrypt this file, probably this is a shared file. Please ask the file owner to reshare the file with you. | 2017-12-04T14:04:39+0100
-- | -- | -- | --
Debug | onlyoffice | Download: 432


![1](https://user-images.githubusercontent.com/33482537/33554335-8aa4f0b2-d8fc-11e7-9c61-5b91b545f1b2.JPG)
![2](https://user-images.githubusercontent.com/33482537/33554336-8c190438-d8fc-11e7-867d-66dd1ae0bc92.JPG)
![3](https://user-images.githubusercontent.com/33482537/33554340-8d747ba0-d8fc-11e7-99b8-5d2badd21459.JPG)
![4](https://user-images.githubusercontent.com/33482537/33554341-8e9b9216-d8fc-11e7-9a91-7977997daad9.JPG)

**Comment by alexanderonlyoffice** [comment]
@ExaconAT,

Is this is a problem with external storage?

**Comment by ExaconAT** [comment]
No with local storage and encryption enabled.

**Comment by flaminestone** [comment]
@ExaconAT I can't repeat it case. You real use master encryption? Because it look like after user encryption activated. And master encryption is work correctly for me.
Can you provide your steps for setting nextcloud?

**Comment by ExaconAT** [comment]
@flaminestone 
On the first screenshot you can see that i have enabled the master encryption key

https://user-images.githubusercontent.com/33482537/33554335-8aa4f0b2-d8fc-11e7-9c61-5b91b545f1b2.JPG

**Comment by flaminestone** [comment]
@ExaconAT On your screenshot I see ability to recover password, if user forgot password. That will be possible only if used user encryption, no master encryption.
Please, read carefully nextcloud documentation, section of occ-encryption-commands.
ONLYOFFICE can correctly work only with master encryption
