### ISSUE TITLE
OnlyOffice stops saving document back to NextCloud

### ISSUE THREAD

**Issue by duckhawk** [ONLYOFFICE/onlyoffice-owncloud#135]
Problem: 
OnlyOffice in some case doesn't save document back to NextCloud. It happens time-to-time, with different documents, I can't identify, which situation causes it.
If needs, I have example of such document, and can collect all info needed for diag.

I have last versions of OnlyOffice and NextCloud 12.

I tried to set force save for every 5 minutes in default.json, but it seems, that OnlyOffice totaly ignores this param.

**Comment by alexanderonlyoffice** [comment]
Hello @duckhawk,

Please specify if JWT is on in Document Server and NextCloud.

**Comment by duckhawk** [comment]
Sorry, I don't know, can you tell, where I can check it?

**Comment by alexanderonlyoffice** [comment]
Hello @duckhawk,

Check the advanced server settings in NextCloud administrator section. When JWT is off the field 'Secret key' is blank (see attached screenshot).
![nextcloud](https://user-images.githubusercontent.com/30896337/33655998-bf12256a-da85-11e7-9a8d-3eeb9cfec72f.png)

**Comment by duckhawk** [comment]
No, this field is empty.

**Comment by alexanderonlyoffice** [comment]
@duckhawk,

Please send us logs of NextCloud in which we can check both cases (when the document was saved and when it was not saved). You can send them to support@onlyoffice.com

**Comment by alexanderonlyoffice** [comment]
Hello @duckhawk,

Please specify if the issue still exists.

**Comment by duckhawk** [comment]
Which logs I can send to you?
I can't find any logs, that belongs to nextcloud/onlyoffice on my server.

**Comment by alexanderonlyoffice** [comment]
Hello @duckhawk,

Please specify the OS of the server where the document server is installed, so we can tell you where to find logs. You can get logs of Nextcloud in Nextcloud Logging section. Please see the attached screenshot.

![logs of nextcloud](https://user-images.githubusercontent.com/30896337/38609481-d8d4f7de-3d86-11e8-83ac-7427e719522e.png)

**Comment by duckhawk** [comment]
There is Ubuntu 16.04 LTS installed on server (Onlyoffice is running in Docker, if it matters)

**Comment by alexanderonlyoffice** [comment]
@duckhawk, the logs should be in the following directory: **/app/onlyoffice/DocumentServer/logs/**

**Comment by alexanderonlyoffice** [comment]
Hello @duckhawk, please specify if the issue still persists, as we did not receive the logs.

**Comment by LinneyS** [comment]
This issue was closed due to no response.
