### ISSUE TITLE
The document loading blocks

### ISSUE THREAD

**Issue by CoriciM** [ONLYOFFICE/onlyoffice-owncloud#137]
We have edited 8 people a document and some left the windows of the browsers open. 
Now we can not log anymore the document. It always blocks at 82%. So we can not reach the document to save it. 

![image](https://user-images.githubusercontent.com/14921075/34143767-b4774db6-e48e-11e7-9966-f088c947abbe.png)

is there any solution at least to recover the latest version of the document?

**Comment by agolybev** [comment]
Hi @CoriciM, what product do you use?

**Comment by alexanderonlyoffice** [comment]
Hello @CoriciM,

Please specify if the issue still exists.

**Comment by alexanderonlyoffice** [comment]
This ticket is closed as there is no feedback about the issue.
