### ISSUE TITLE
Document not saving into owncloud

### ISSUE THREAD

**Issue by ManuelRighi** [ONLYOFFICE/onlyoffice-owncloud#139]
Hello,
I have 
owncloud server version 10.0.2 on Ubuntu Server 14.04.5 LTS
onlyoffice document server version 4.4.3-7 on another server, Ubuntu Server 16.04.3 LTS
onlyoffice app version 1.1.6

All same to work correctly, but document edited in onlyoffice is not saved to owncloud physical files.
For example if I download (from owncloud) excel file created with onlyoffice, file is empty. If this file is opened from onlyoffice, I have content ...

Can you help me ?
Thanks
Manuel

**Comment by tavinus** [comment]
Did you close the document and waited a few seconds?
Documents are only saved back to cloud a few seconds after ALL USERS CLOSE the document.

So, even if you hit save, that gets saved only at the document server instance (not owncloud). It will get sent back to owncloud when the file is closed.

There is a issue asking for a force save (without closing) here: https://github.com/ONLYOFFICE/onlyoffice-owncloud/issues/116

Cheers!
Gus

**Comment by LinneyS** [comment]
Could you please specify if the problem recurs or we can close the topic.

**Comment by KuenzelIT** [comment]
> Documents are only saved back to cloud a few seconds after ALL USERS CLOSE the document.

I know this is intended, but can someone explain this a little more?

We assume its about performance or something, but a save back to the owncloud every minute (or x) would already help a lot. Our users are totally irritated, that they get a start document after hours of editing with 5+ people.

We know that it's possible to download the current version from the editing menu, but it's still unintuitive.

**Comment by tavinus** [comment]
I am not sure why it is done like that.  
I think the auto-save to own/nextcloud was just not implemented yet...

**Comment by LinneyS** [comment]
@ManuelRighi 
Could you please specify if the problem recurs or we can close the topic?

**Comment by LinneyS** [comment]
This issue was closed due to no response.
