### ISSUE TITLE
Embed links for documents

### ISSUE THREAD

**Issue by zirkeltraining** [ONLYOFFICE/onlyoffice-owncloud#14]
in Onlyoffice, it's possible to get an embed link for a document so that i can for example embed an (editable) spreadsheet in a webpage. This is super useful for our internal team wiki. I can simply use the URL of an editor with a document open and use that in an iframe on our wiki.

Apparently, that's not easily possible with the OO-OC connector? why can't i embed a link like 
"https://myocserver.net/index.php/apps/onlyoffice/331" in a wiki and have it editable there? Some Cross-Site-Scripting issue?

The problem is that if we combine the two access methods - editing directly from within OC via the OO-OC integration AND embedding OC files via the WebDAV access from OC - then we tend to have two versions of the file which are not in sync! Concurrent editing only works from one of the two access paths, not from both at the same time.

**Comment by ibnpetr** [comment]
Thanks a lot for your interest in our products.

> This is super useful for our internal team wiki.... The problem is that if we combine the two access methods...

Please contact us at support@onlyoffice.com if you are interested in any kind of custom development. We will discuss features required by you.
