### ISSUE TITLE
Brazilian Portuguese Asset Files + Translation

### ISSUE THREAD

**Issue by tavinus** [ONLYOFFICE/onlyoffice-owncloud#142]
Hi!

The current asset files (templates) for Brazilian Portuguese are not really in Brazilian Portuguese.
The new.x files are either in English or Portugal Portuguese.

I have created new files using a Brazilian Portuguese Microsoft Office 2016 install and replaced the old ones. Just created a new file and removed the Author before saving.

I am not sure if you guys want to create these files yourselves with onlyoffice, so I didn't really create a pull request for this. You may pull it from [this branch](https://github.com/tavinus/onlyoffice-owncloud/tree/assets-pt_BR) or just get the asset files there. [(commit)](https://github.com/tavinus/onlyoffice-owncloud/commit/e3f293e0e6a819812e9e02fb9efbe10bffc1791a)

I have also created a [Brazilian Portuguese translation on this branch](https://github.com/tavinus/onlyoffice-owncloud/tree/pt_BR).
This one has a PR: https://github.com/ONLYOFFICE/onlyoffice-owncloud/pull/141

PS: MS Office default font is Calibri for most programs, which is not installed by default (comes from Vista font pack). Not sure if onlyoffice uses another font as the default one. I have installed the vista fonts at my server anyways.

Cheers!
Gus

**Comment by LinneyS** [comment]
Thx
We used your translations

**Comment by alexandervnuchkov** [comment]
@tavinus You can also participate in the ONLYOFFICE translation (if you are interested in that, of course). Feel free to contact me using the documentation@onlyoffice.com email address, and I will send you all the information necessary to take part in the translation.

**Comment by tavinus** [comment]
Sent an email, cheers...
