### ISSUE TITLE
Spreadsheet location "memory" for close/open

### ISSUE THREAD

**Issue by tavinus** [ONLYOFFICE/onlyoffice-owncloud#143]
Hi there! Thanks for this great app!

I was wondering if it is possible to make OnlyOffice save the position inside a document like MS Office does (at least for spreadsheets).

For instance, if I open a large spreadsheet and do something at the 3rd sheet, line 13245 and then leave the selection there, that is not saved. So if I close and open the file again, it would go back to where it was before (possibly A1).

So, if it was a new file and that was on A1, you would go back to that position. But I had some files that had the position saved on MS Excel and they seem to always go back to the same position (that was saved on Excel).

I understand that because OnlyOffice can have more than one person connected this could be more tricky. We would probably need to save the last position of the last person. 

Not a serious bug but can be quite annoying if you are working with big spreadsheets and need to keep rolling thousand of lines and columns every time you open a document.

#### My install
Debian Jessie 8.10
NC: 12.0.4
OO Document Server: 5.0.6-14

BTW, is there an easy way to get the document server version? 
Had to get that with `apt-cache show onlyoffice-documentserver`

Cheers!
Gus

**Comment by ShockwaveNN** [comment]
@tavinus Hi, seems this issue have nothing to do with owncloud, so please duplicate it in https://github.com/ONLYOFFICE/DocumentServer
 
P.S. Yes, using `apt-cache` is the easiest way to get exact version. But version from `About` is UI is enough in most cases

**Comment by LinneyS** [comment]
ONLYOFFICE/DocumentServer#230
