### ISSUE TITLE
Creating files with an existing name

### ISSUE THREAD

**Issue by alexisrosano89** [ONLYOFFICE/onlyoffice-owncloud#147]
It happends in a location different to root.

Steps to reproduce:

1. Create a new document without setting a name in a folder different to the root folder (Using '+' in NC).
2. NC creates a new file called Document(1).docx
3. Add some text to the Document(1).docx
4. Back to the folder where is placed the Document(1).
5. Create new file without setting a name.
6. NC creates a new file called Document(1).docx too.
7. Edit this file.
8. NC overrides the first file with the text of the second file (same name)

Regards.

**Comment by LinneyS** [comment]
Thx
Fixed

**Comment by alexisrosano89** [comment]
Thank you.

When it's going to be released?
