### ISSUE TITLE
Issue saving as PDF from Nextcloud (Hidden letters)

### ISSUE THREAD

**Issue by BetaLeaf** [ONLYOFFICE/onlyoffice-owncloud#151]
I have an interesting issue. When I try to Save As PDF this same spreadsheet, there are issues rendering some letters. 

Testing Notes:
  - The first letter of the spreadsheet is always invisible (It's still there as I can search for it)
  - This doesn't happen on merged cells (If first letter of spreadsheet is within a merged cell, it is the next cell over that is affected)
  - The letter that is affected is  affects all cells that contain the same case-sensitive letter. (Doesn't have to be the first letter of the cell)
  - This issue occurs when creating a document from scratch within OnlyOffice and when importing existing documents created from other sources. (AKA It's the Save As PDF that is not working correctly)
  - This issue is not present when saved as PDF in another document reader and then viewed in Open Office (more proof its the Save As PDF that is not working correctly)
  - This issue is not present when viewed in another document reader (such as Excel)

## Screenshot
(The letter "S" is invisible)
![image](https://user-images.githubusercontent.com/7028351/35474087-2c601312-0357-11e8-8888-43288aade716.png)

## Links & Downloads
[Nintendo Switch.xlsx](https://github.com/ONLYOFFICE/onlyoffice-owncloud/files/1670256/Nintendo.Switch.xlsx)

The following links will take you to my Nextcloud Server.
Spreadsheet (Edit Mode) https://cloud.betaleaf.net/apps/onlyoffice/6370
Spreadsheet https://cloud.betaleaf.net/s/hC1LsnTTVJBW89W
PDF (OnlyOffice)https://cloud.betaleaf.net/s/bnqExmsytuQQdg0
PDF (Excel)https://cloud.betaleaf.net/s/6hOTNetNJRVHB7I

If prompted to log in, use guest:guest
Don't worry about messing up the spreadsheet, its a copy.

**Comment by ShockwaveNN** [comment]
@BetaLeaf Hi
I opened your link for PDF OnlyOffice https://cloud.betaleaf.net/s/bnqExmsytuQQdg0
And seems it used `pdfjs` as viewer. Or something else, from nextcloud team, I'm not sure. But this is not our product :)
I downloaded this pdf as file and opened in Chrome PDF Viewer, Onlyoffice DesktopEditors and Okular - and everything fine.
Seems this is bug in pdfjs.
Feel free to reopen the issue, if you disagree with me

**Comment by BetaLeaf** [comment]
@ShockwaveNN Alright, I will open an issue in the appropriate section. The reason I opened it here initially was because the PDF that Excel creates is like 220kb where as OnlyOffice is around 25kb file. That's a massive file size difference.

**Comment by ShockwaveNN** [comment]
@BetaLeaf Yeah, I can confirm size difference but can't find if we missed something, Onlyoffice PDF looks almost exactly the same with PDF visually
