### ISSUE TITLE
Problems with Onlyoffice on IPhone’s browser

### ISSUE THREAD

**Issue by PiotrIr** [ONLYOFFICE/onlyoffice-owncloud#152]
I’ve successfully integrated Nextcloud 13 (RC4) with Onlyoffice and everything is working fine on PC. however when I try to open document on my mobile browser (tried Safari and Chrome), it tries to open it, goes to 33% and then crashes with error message "A problem repeatedly occurred on “https://nexcloud.mydomin.com/index.php/apps/onlyoffice/318”.

**Comment by alexanderonlyoffice** [comment]
Hello @PiotrIr,

We have tried to reproduce the issue, unfortunately, we did not succeed. Please specify if the issue occurs with document or spreadsheet files.

**Comment by PiotrIr** [comment]
Hi Alexander,

I've just done some another tests and it does happen on both, document and spreadsheet. However it looks not all are affected. If I create very simple document I can open it without problems but more complex crashes. Please find attached example which causes problems.
[Server Alocation.xlsx](https://github.com/ONLYOFFICE/onlyoffice-owncloud/files/1694521/Server.Alocation.xlsx)

All opens fine on desktop's browser.

I'm on latest version of connector - 1.2.0
There is nothing in Nextcloud logs unfortunately. Perhaps there is something on onlyoffice which I can check but could you advise where to find it please?

**Comment by alexanderonlyoffice** [comment]
Hello @PiotrIr,

Could you please specify the version of the document server and the model of iPhone.

**Comment by PiotrIr** [comment]
Hi Alexander

Onyoffice - 5.0.7-38
Iphone 6 IOS 11.2.2

**Comment by alexanderonlyoffice** [comment]
Hello @PiotrIr,

Please try to clear browser's cache and check if the issue still persists.

We have performed tests on the same version of application and device, but could not reproduce the mentioned issue.

Could you please give us access to your NextCloud account.

**Comment by PiotrIr** [comment]
Hi Alexander,

Unfortunately it didn't help. Sending credentials.

**Comment by PiotrIr** [comment]
Hi Alexander,

I've sent the credentials but got reply from Eugenie not you.

**Comment by alexanderonlyoffice** [comment]
Hello @PiotrIr,

We received your account credentials. We will perform several tests and notify you as soon as there are results.

**Comment by alexanderonlyoffice** [comment]
Hello @PiotrIr,

Unfortunately, we cannot reproduce the issue. We opened the file in your Nextcloud account, on iPhone, in Google Docs and on MAC and everything works. Please specify if there are any other actions you did when the error occurred.

**Comment by PiotrIr** [comment]
Hi Alexander,
I just open the file in browser. I've tested it and is working fine on another iPhone but version 5. Just my 6 causes problem in some reason. I've tried it on directly after phone restart on two different browsers (Safari and Chrome). Effect is the same. Please see print screens attached.

![photo-2018-02-07-15-41-18_3854](https://user-images.githubusercontent.com/12460359/35925665-419a29b4-0c1e-11e8-8e34-ab3a8c4ff11c.PNG)
![photo-2018-02-07-15-44-51_3863](https://user-images.githubusercontent.com/12460359/35925684-4bf89e7c-0c1e-11e8-9cc9-58b4bfce9190.PNG)
![photo-2018-02-07-15-44-59_3864](https://user-images.githubusercontent.com/12460359/35925699-5419921e-0c1e-11e8-9084-c31504542f6a.PNG)
![photo-2018-02-07-15-41-43_3857](https://user-images.githubusercontent.com/12460359/35925706-5825b6e4-0c1e-11e8-84cd-d4ecae2e8292.PNG)

**Comment by alexanderonlyoffice** [comment]
Hello @PiotrIr,

Unfortunately, we cannot detect the reason of the issue, as we cannot reproduce it. Could you please give us access to your server, so we can check the configuration and look through the logs.  

If yes, please send the credentials to support@onlyoffice.com with a note "for technical support department".

**Comment by PiotrIr** [comment]
Hi Alexander,

I've just upgraded today IOS to 11.2.5 and the problem dispirited and I can open all documents. Perhaps it was kind of issue in 11.2.3. Any way it is working now - thank you for your help.

**Comment by alexanderonlyoffice** [comment]
Hello @PiotrIr,

We are glad the issue has been resolved.

**Comment by peio72** [comment]
+1 Same problem here. Our users can’t open their documents on ipad/iphone anymore. Please help.

**Comment by dliebchen** [comment]
+1 Same problem here. Devices updated to 11.3 can't open documents anymore. However this problem seems to concern Safari browser. You can install Firefox as workaround for till it got fixed.

**Comment by peio72** [comment]
Not working with Firefox ios here too. Only Office 5.1.0

**Comment by gt2416** [comment]
^ if it doesnt work on safari ios its not gonna work on firefox. It sthe same browser. Just like browsers on android all use chrome api's. 

It does not work on Mac 10.3.4 Safari browser on desktop I just found out. Which is interesting...

**Comment by LinneyS** [comment]
#173

**Comment by dliebchen** [comment]
@gt2416 yes, i was referring to desktop iOS on MacBooks. Safari won't open OfficeOnly documents while Firefox will.

**Comment by BigMackTech** [comment]
So what I am getting from this post is if you have IPAD with iOS 11.3 and above it breaks the ability to open spreadsheets and docs with OnlyOffice, correct?   I believe I am having the same issue.  I have a customer with 10 Ipads and the ones in the field are working and we can access docs from windows pc's and android phones and everything works.  Now we bought 2 more IPads and neither of them will open spreadsheets and/or docs in chrome browser or any browser on those two Ipads.  One has iOS 11.3.0 and one has 11.3.1.  I haven't verified it yet, but I would guess the other older Ipads have older versions of iOS on them.  Have we come up with a solution to this?  Can you roll back an IPad?  thanks

**Comment by gt2416** [comment]
There was an update to the document server a while ago that addressed this issue. Make sure your on the latest one.

**Comment by BigMackTech** [comment]
I just setup the server in February and I have to upgrade already.  Okay, I will give that a try.  Thanks.

**Comment by BigMackTech** [comment]
How can I tell what version of document server I have installed?  I did the upgrade I believe and it still not working.

**Comment by BigMackTech** [comment]
Information Icon says it's Spreadsheet editor is version 5.0.7CE.  So doesn't look like it upgraded.

**Comment by alexanderonlyoffice** [comment]
@BigMackTech, please specify OS of your server and the document server installation type (Docker or DEB/RPM). 

Please describe also the way you upgraded the document server (with the commands, if possible).

**Comment by BigMackTech** [comment]
Do you have a good way to update a docker install?

**Comment by BigMackTech** [comment]
I ran your script and everything looked like it was successful, but still not on the new version.  thanks.

**Comment by BigMackTech** [comment]
Looks like the script didn't upgrade my current install but created a new one. :(  How do I get it to upgrade my existing one?

**Comment by alexanderonlyoffice** [comment]
Please delete both containers and run a new one. You can find the latest docker image of the Document Server on [Hubdocker](https://hub.docker.com/r/onlyoffice/documentserver/) website.

> I am pretty new when it comes to Linux (really green when it comes to Docker) and I can't seem to find the commands I used to do the update last night.

Please contact us via our support system **https://helpdesk.onlyoffice.com**

**Comment by damago1** [comment]
I have the same problem on recenty IOS on iPad Pro. I have tested this on 2 different installations of Nextcloud with OnlyOffice under two different domains and on two different iPad devices. 

When loading anything but a very simple spreadsheet the document is stuck on 'Loading...' and it goes like this forever. You cannot open any excel document on Nexcloud on any browser on iOS because ALL of them are using the same engine (WebKit). 

Nexcloud version 20.0.11

I am NOT using containters, all is debian native.
