### ISSUE TITLE
Document Server Limitations

### ISSUE THREAD

**Issue by miglinux** [ONLYOFFICE/onlyoffice-owncloud#153]
Hi folks!

I'm thinking to use Owncloud + Only Office Document Server for a educational environment, around 10k users or a bit more.
Both solutions will be community edition.
Based on that scenario I'd like to know if there are any kind of limitation as number of connections or number of users simultaneously, etc. I'm asking because I've read there are limitations, however I don't know if it's a true information.

Cheers!

**Comment by ShockwaveNN** [comment]
You can see limitations here https://www.onlyoffice.com/integration-edition-prices.aspx
or contact our sales team directly via sales@onlyoffice.com

**Comment by ShockwaveNN** [comment]
@miglinux We have discussed your request internally and would be happy to provide you with a more powerfull test version. Please contact us at sales@onlyoffice.com if you are interested to test.
