### ISSUE TITLE
xlsm support?

### ISSUE THREAD

**Issue by stanelie** [ONLYOFFICE/onlyoffice-owncloud#154]
Hello.

I am unable to open .xlsm files through Onlyoffice. Is this on purpose?

As per the specifications here : "Currently the following document formats can be edited with this app: DOCX, XLSX, PPTX, TXT, CSV" https://api.onlyoffice.com/editors/owncloud. However, here in the config api, we see that Onlyoffice can open .xlsm https://api.onlyoffice.com/editors/config/ . Is this limitation on purpose or did someone just forget to include .xlsm files in the config file somewhere on the application server or the onlyoffice nextcloud app?

Thanks!

**Comment by stanelie** [comment]
Just noticed this : it does not open .xls files either...

**Comment by LinneyS** [comment]
add macro-enabled and template formats
fa1907abcf386e652e673609af506e81a7baa26f

**Comment by stanelie** [comment]
I just overwrote the lib/appconfig.php file with the new version and it still downloads the .xls files instead of opening them in the onlyoffice suite.

**Comment by stanelie** [comment]
Just pulled the whole ONLYOFFICE/onlyoffice-owncloud app from git and installed it on my Nextcloud, same issue...

**Comment by alexanderonlyoffice** [comment]
Hello @stanelie,

Please note that the file could not be opened from the action menu, it is being sent for conversion.

**Comment by stanelie** [comment]
Hello.

I am not sure I understand. When I clic on a .xls file within Nextcloud, I expect it to be opened with the OnlyOffice online editor, as is the case with .xlsm files, or with Collabora, for that matter. However, this is not the case, I get the dialog from my browser prompting me to download the file instead.

**Comment by alexanderonlyoffice** [comment]
Hello @stanelie,

Please open the administrator section of NC and choose ONLYOFFICE settings, there will be settings for default opening where you can choose formats. See the attached screenshot. 
![default](https://user-images.githubusercontent.com/30896337/38187232-6b5d30f0-365f-11e8-8455-ddd27b7ec140.png)


As for the formats not stated in the list they need to be conversed at first, that is why it is necessary to click on the action menu and choose "Open in ONLYOFFICE" option. The file will be converted and copied in the same folder.

**Comment by alexanderonlyoffice** [comment]
Hello @stanelie,

Please open a new issue or describe the problem in similar issues related to the conversion. 

Please do the following: click on the Save button in ONLYOFFICE address settings and attach the logs of Nextcloud after that.

**Comment by stanelie** [comment]
Hello.
Does this limitation of needing to convert .xls files to .xlsm files first before being able to edit them in OnlyOffice still exist?

Thanks!

**Comment by CarlOnlyoffice** [comment]
@stanelie 
Hello, yes, .xls files are opened in viewer only. In order to be able to edit them, you need to convert them to .xlsx.

**Comment by stanelie** [comment]
Are there plans to have this fixed?
To me, this is still a bug, since it is not the expected behavior of an Office suite. I expect an Office suite to be able to open "standard" (yeah, I know, locked into microsoft formats) office files.
With about 50 000 .xls files on our file server, converting them all is not something I look forward to.

**Comment by CarlOnlyoffice** [comment]
@stanelie 
This is not a bug. ONLYOFFICE editors work only with Open XML formats (docx/xlsx/pptx), so .xls files have to be converted.

**Comment by lumcab** [comment]
Alguna alternativa para formatos .xlsm en el trabajo usan los archivos con macros y no puedo modificarlos.
