### ISSUE TITLE
how make iis revese proxy access well?

### ISSUE THREAD

**Issue by carlsue** [ONLYOFFICE/onlyoffice-owncloud#159]
i have setuped the server at locale network,i want access it from internet.
i have set the iis rewrite rules and the nextcloud can open ,but when open a .docx etc will get errors.

windows server 2016 with iis host os (public ip) turn on the NAT.
centos7 with docker hypervm guest  os(privae ip 192.168.137.0/24)

the image is running on centos.

**Comment by agolybev** [comment]
Hi @jianbosu, you can find general information about proxying to document server 
[here](https://helpcenter.onlyoffice.com/server/document/document-server-proxy.aspx)
There isn't detailed instruction for iss but you can find some information [here](https://github.com/ONLYOFFICE/document-server-proxy/tree/master/iis/proxy-to-virtual-path)
