### ISSUE TITLE
white screen nextcloud \ onlyoffice same

### ISSUE THREAD

**Issue by LeandroLouvem** [ONLYOFFICE/onlyoffice-owncloud#160]
I have nextcloud with onlyoffice on the same server, but when I try to open documents the screen turns white. follows log nextcloud.log:

{"reqId":"Teiaunz19D1FSDy0GRHK","level":0,"time":"March 06, 2018 17:17:15","remoteAddr":"177.137.232.3","user":"leandro.louvem","app":"onlyoffice","method":"GET","url":"\/apps\/onlyoffice\/808","message":"Open: 808","userAgent":"Mozilla\/5.0 (Windows NT 6.1; WOW64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/57.0.2987.98 Safari\/537.36","version":"13.0.0.14"}
{"reqId":"2AZgGEoj6kIZnwxxk5PZ","level":3,"time":"March 06, 2018 17:24:28","remoteAddr":"177.137.232.3","user":"leandro.louvem","app":"no app in context","method":"GET","url":"\/settings\/admin","message":"issuetemplate","userAgent":"Mozilla\/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/64.0.3282.186 Safari\/537.36","version":"13.0.0.14"}
{"reqId":"IAZw1KGcYp25z9t5rlTz","level":3,"time":"March 06, 2018 17:24:40","remoteAddr":"177.137.232.3","user":"leandro.louvem","app":"no app in context","method":"GET","url":"\/settings\/user","message":"issuetemplate","userAgent":"Mozilla\/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/64.0.3282.186 Safari\/537.36","version":"13.0.0.14"}
{"reqId":"P7hlJiXYkc7ckj3NzYAV","level":3,"time":"March 06, 2018 17:24:51","remoteAddr":"177.137.232.3","user":"leandro.louvem","app":"no app in context","method":"GET","url":"\/settings\/user\/security","message":"issuetemplate","userAgent":"Mozilla\/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/64.0.3282.186 Safari\/537.36","version":"13.0.0.14"}
{"reqId":"KJQNPnpLt5JsgnzK88SL","level":3,"time":"March 06, 2018 17:25:01","remoteAddr":"177.137.232.3","user":"leandro.louvem","app":"no app in context","method":"GET","url":"\/settings\/user\/sync-clients","message":"issuetemplate","userAgent":"Mozilla\/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/64.0.3282.186 Safari\/537.36","version":"13.0.0.14"}
{"reqId":"8wBKhPVAPekYsfd5fNGc","level":3,"time":"March 06, 2018 17:25:03","remoteAddr":"177.137.232.3","user":"leandro.louvem","app":"no app in context","method":"GET","url":"\/settings\/user\/sharing","message":"issuetemplate","userAgent":"Mozilla\/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/64.0.3282.186 Safari\/537.36","version":"13.0.0.14"}
{"reqId":"wSaepXKzaG7iMelnz9kx","level":3,"time":"March 06, 2018 17:25:04","remoteAddr":"177.137.232.3","user":"leandro.louvem","app":"no app in context","method":"GET","url":"\/settings\/user\/additional","message":"issuetemplate","userAgent":"Mozilla\/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/64.0.3282.186 Safari\/537.36","version":"13.0.0.14"}
{"reqId":"Q7CNxJDIqLQzNUytYF8g","level":3,"time":"March 06, 2018 17:25:10","remoteAddr":"177.137.232.3","user":"leandro.louvem","app":"no app in context","method":"GET","url":"\/settings\/admin\/additional","message":"issuetemplate","userAgent":"Mozilla\/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/64.0.3282.186 Safari\/537.36","version":"13.0.0.14"}
{"reqId":"5tKbybE8HjyEucOYtW6B","level":3,"time":"March 06, 2018 17:25:21","remoteAddr":"177.137.232.3","user":"leandro.louvem","app":"no app in context","method":"GET","url":"\/settings\/admin\/logging","message":"issuetemplate","userAgent":"Mozilla\/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/64.0.3282.186 Safari\/537.36","version":"13.0.0.14"}
{"reqId":"1j8cngX1xR1nFg7042Wj","level":3,"time":"March 06, 2018 17:25:30","remoteAddr":"177.137.232.3","user":"leandro.louvem","app":"no app in context","method":"GET","url":"\/settings\/admin\/serverinfo","message":"issuetemplate","userAgent":"Mozilla\/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/64.0.3282.186 Safari\/537.36","version":"13.0.0.14"}
{"reqId":"78NFwz4lg1pwpbpZOzYl","level":0,"time":"March 06, 2018 17:26:01","remoteAddr":"177.137.232.3","user":"--","app":"core","method":"GET","url":"\/settings\/apps\/list?category=tools","message":"Scss is disabled for \/var\/www\/nextcloud\/core\/css\/jquery-ui-fixes.scss, ignoring","userAgent":"Mozilla\/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/64.0.3282.186 Safari\/537.36","version":"13.0.0.14"}
{"reqId":"78NFwz4lg1pwpbpZOzYl","level":0,"time":"March 06, 2018 17:26:01","remoteAddr":"177.137.232.3","user":"--","app":"core","method":"GET","url":"\/settings\/apps\/list?category=tools","message":"Scss is disabled for \/var\/www\/nextcloud\/core\/css\/server.scss, ignoring","userAgent":"Mozilla\/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/64.0.3282.186 Safari\/537.36","version":"13.0.0.14"}
{"reqId":"78NFwz4lg1pwpbpZOzYl","level":0,"time":"March 06, 2018 17:26:01","remoteAddr":"177.137.232.3","user":"--","app":"core","method":"GET","url":"\/settings\/apps\/list?category=tools","message":"Scss is disabled for \/var\/www\/nextcloud\/core\/css\/jquery.ocdialog.scss, ignoring","userAgent":"Mozilla\/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/64.0.3282.186 Safari\/537.36","version":"13.0.0.14"}
{"reqId":"GeyPGK8IJlMrUdQH5njS","level":0,"time":"March 06, 2018 17:26:48","remoteAddr":"177.137.232.3","user":"leandro.louvem","app":"core","method":"GET","url":"\/apps\/calendar\/","message":"\/apps\/calendar\/css\/public\/app.min.scss compiled and successfully cached","userAgent":"Mozilla\/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/64.0.3282.186 Safari\/537.36","version":"13.0.0.14"}
{"reqId":"AN2a5MTtwXGfQkW1A3Mr","level":0,"time":"March 06, 2018 17:27:22","remoteAddr":"177.137.232.3","user":"--","app":"core","method":"GET","url":"\/login","message":"Scss is disabled for \/var\/www\/nextcloud\/core\/css\/jquery-ui-fixes.scss, ignoring","userAgent":"Mozilla\/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/64.0.3282.186 Safari\/537.36","version":"13.0.0.14"}
{"reqId":"AN2a5MTtwXGfQkW1A3Mr","level":0,"time":"March 06, 2018 17:27:22","remoteAddr":"177.137.232.3","user":"--","app":"core","method":"GET","url":"\/login","message":"Scss is disabled for \/var\/www\/nextcloud\/core\/css\/server.scss, ignoring","userAgent":"Mozilla\/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/64.0.3282.186 Safari\/537.36","version":"13.0.0.14"}
{"reqId":"AN2a5MTtwXGfQkW1A3Mr","level":0,"time":"March 06, 2018 17:27:22","remoteAddr":"177.137.232.3","user":"--","app":"core","method":"GET","url":"\/login","message":"Scss is disabled for \/var\/www\/nextcloud\/core\/css\/share.scss, ignoring","userAgent":"Mozilla\/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/64.0.3282.186 Safari\/537.36","version":"13.0.0.14"}
{"reqId":"AN2a5MTtwXGfQkW1A3Mr","level":0,"time":"March 06, 2018 17:27:22","remoteAddr":"177.137.232.3","user":"--","app":"core","method":"GET","url":"\/login","message":"Scss is disabled for \/var\/www\/nextcloud\/core\/css\/jquery.ocdialog.scss, ignoring","userAgent":"Mozilla\/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/64.0.3282.186 Safari\/537.36","version":"13.0.0.14"}
{"reqId":"Arm5lYfZBWnPecRMaxoZ","level":0,"time":"March 06, 2018 17:27:31","remoteAddr":"177.137.232.3","user":"leandro.louvem","app":"onlyoffice","method":"GET","url":"\/apps\/onlyoffice\/808","message":"Open: 808","userAgent":"Mozilla\/5.0 (Windows NT 6.1; WOW64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/57.0.2987.98 Safari\/537.36","version":"13.0.0.14"}
{"reqId":"OsEwRd04lJKdvFd43ukk","level":0,"time":"March 06, 2018 17:29:55","remoteAddr":"177.168.78.9","user":"leandro.louvem","app":"onlyoffice","method":"GET","url":"\/apps\/onlyoffice\/807","message":"Open: 807","userAgent":"Mozilla\/5.0 (Linux; Android 7.1.1; Moto G (5S) Build\/NPPS26.102-49-4) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/64.0.3282.137 Mobile Safari\/537.36","version":"13.0.0.14"}
{"reqId":"CMEZJmqTbUWmjuyHg34J","level":0,"time":"March 06, 2018 17:29:58","remoteAddr":"177.168.78.9","user":"leandro.louvem","app":"onlyoffice","method":"GET","url":"\/apps\/onlyoffice\/ajax\/config\/807","message":"Config is generated for: 807 with key 807_1520347369","userAgent":"Mozilla\/5.0 (Linux; Android 7.1.1; Moto G (5S) Build\/NPPS26.102-49-4) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/64.0.3282.137 Mobile Safari\/537.36","version":"13.0.0.14"}
{"reqId":"X2tmELyTbAQgYfx1xhfI","level":0,"time":"March 06, 2018 17:30:04","remoteAddr":"172.17.0.2","user":"--","app":"onlyoffice","method":"POST","url":"\/apps\/onlyoffice\/track?doc=eVp3ZmpHaTI5cXZhK2Y5STJLMGRKSDY1aTdSRGNlSkdQUU1BVTMvWGt0bz0\/eyJmaWxlSWQiOjgwNywidXNlcklkIjoibGVhbmRyby5sb3V2ZW0iLCJhY3Rpb24iOiJ0cmFjayJ9","message":"Track: 807 status 1","userAgent":"--","version":"13.0.0.14"}
{"reqId":"q3fcZC1BaO9AYsr0kX1a","level":0,"time":"March 06, 2018 17:30:29","remoteAddr":"172.17.0.2","user":"--","app":"onlyoffice","method":"POST","url":"\/apps\/onlyoffice\/track?doc=eVp3ZmpHaTI5cXZhK2Y5STJLMGRKSDY1aTdSRGNlSkdQUU1BVTMvWGt0bz0\/eyJmaWxlSWQiOjgwNywidXNlcklkIjoibGVhbmRyby5sb3V2ZW0iLCJhY3Rpb24iOiJ0cmFjayJ9","message":"Track: 807 status 4","userAgent":"--","version":"13.0.0.14"}
{"reqId":"JAWUqNDm6TzfqDaC8WS8","level":0,"time":"March 06, 2018 17:54:04","remoteAddr":"177.137.232.3","user":"--","app":"core","method":"GET","url":"\/login","message":"Scss is disabled for \/var\/www\/nextcloud\/core\/css\/jquery-ui-fixes.scss, ignoring","userAgent":"Mozilla\/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/64.0.3282.186 Safari\/537.36","version":"13.0.0.14"}
{"reqId":"JAWUqNDm6TzfqDaC8WS8","level":0,"time":"March 06, 2018 17:54:04","remoteAddr":"177.137.232.3","user":"--","app":"core","method":"GET","url":"\/login","message":"Scss is disabled for \/var\/www\/nextcloud\/core\/css\/server.scss, ignoring","userAgent":"Mozilla\/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/64.0.3282.186 Safari\/537.36","version":"13.0.0.14"}
{"reqId":"JAWUqNDm6TzfqDaC8WS8","level":0,"time":"March 06, 2018 17:54:04","remoteAddr":"177.137.232.3","user":"--","app":"core","method":"GET","url":"\/login","message":"Scss is disabled for \/var\/www\/nextcloud\/core\/css\/share.scss, ignoring","userAgent":"Mozilla\/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/64.0.3282.186 Safari\/537.36","version":"13.0.0.14"}
{"reqId":"JAWUqNDm6TzfqDaC8WS8","level":0,"time":"March 06, 2018 17:54:04","remoteAddr":"177.137.232.3","user":"--","app":"core","method":"GET","url":"\/login","message":"Scss is disabled for \/var\/www\/nextcloud\/core\/css\/jquery.ocdialog.scss, ignoring","userAgent":"Mozilla\/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/64.0.3282.186 Safari\/537.36","version":"13.0.0.14"}
{"reqId":"tDERfAwwMz9GEzbGU8z4","level":0,"time":"March 06, 2018 17:54:04","remoteAddr":"177.137.232.3","user":"--","app":"core","method":"GET","url":"\/login","message":"Scss is disabled for \/var\/www\/nextcloud\/core\/css\/jquery-ui-fixes.scss, ignoring","userAgent":"Mozilla\/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/64.0.3282.186 Safari\/537.36","version":"13.0.0.14"}
{"reqId":"tDERfAwwMz9GEzbGU8z4","level":0,"time":"March 06, 2018 17:54:04","remoteAddr":"177.137.232.3","user":"--","app":"core","method":"GET","url":"\/login","message":"Scss is disabled for \/var\/www\/nextcloud\/core\/css\/server.scss, ignoring","userAgent":"Mozilla\/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/64.0.3282.186 Safari\/537.36","version":"13.0.0.14"}
{"reqId":"tDERfAwwMz9GEzbGU8z4","level":0,"time":"March 06, 2018 17:54:04","remoteAddr":"177.137.232.3","user":"--","app":"core","method":"GET","url":"\/login","message":"Scss is disabled for \/var\/www\/nextcloud\/core\/css\/share.scss, ignoring","userAgent":"Mozilla\/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/64.0.3282.186 Safari\/537.36","version":"13.0.0.14"}

**Comment by LeandroLouvem** [comment]
my settings:
nextcloud 13
hyper-v
docker.io
onlyoffice
the strange one and that has a PC that works without problem.

**Comment by alexanderonlyoffice** [comment]
Hello @LeandroLouvem,

As we can see from the log, there is a problem when opening file in browser on Windows server, and the file is being opened without issues on your mobile device on Android. 

Please try to check the accessibility of the document server in your browser on your Windows server. Enter the following address to the address bar in browser: **http://your_documentserver_domain/web-apps/apps/api/documents/api.js** 

Please send us a screenshot.

**Comment by LeandroLouvem** [comment]
Many thanks for the reply. When typing the url that was passed by the sir appeared the screen that the certificate was not valid, I added the browser exceptions and everything worked correctly. I think that by having the nextcloud and docker on the same server I have 2 certificates, one had already added the list of browser exceptions, which was referring to nextcloud, but I had not yet added any exceptions to the docker script.
Problem solved.

**Comment by alexanderonlyoffice** [comment]
Hello @LeandroLouvem,

We are glad the issue has been resolved.
