### ISSUE TITLE
OwnCloud Not able to create new spread sheet/text docs

### ISSUE THREAD

**Issue by qtechsandesh** [ONLYOFFICE/onlyoffice-owncloud#161]
Not able to create new spreadsheet/documents/presentation/text file in owncloud.
while creating new sheets it will open a new tab in browser and showing only "Loading Please wait"

**Comment by alexanderonlyoffice** [comment]
Hello @qtechsandesh,

Please specify the following information: 

1) OS of your server where ONLYOFFICE document server is installed;
2) Installation type (Docker, DEB/RPM);
3) Version of the document server;
4) Please check if the document server is accessible for Owncloud and vice versa. Use wget command to do it. For example: wget http://your_document_server_address 
5) Please send us the screenshot of ONLYOFFICE document server address settings in Administration section of Owncloud.

**Comment by LinneyS** [comment]
This issue was closed due to no response.
