### ISSUE TITLE
Onlyoffice App does not work with nextcloud 13

### ISSUE THREAD

**Issue by gema2007** [ONLYOFFICE/onlyoffice-owncloud#162]
After Upgrade on Nextcloud 13 on Ubuntu 16.04 no office documents are opened in the browser and no new documents can be made. Onlyoffice runs with docker.

I think the app ins’t working properly. If you klick on the “+” on the top of the page there is no icon any more for office documents.

The logfile says: "file_get_contents(https://…de:8443/coauthoring/CommandService.ashx): failed to open stream: Connection timed out at /www/…de/nextcloud/apps/onlyoffice/lib/documentservice.php#351
CommandRequest on check error: Bad Request oder Timeout Fehlermeldung

Onlyoffice Server is still running.

I reinstalled the App.

**Comment by vjernej** [comment]
I have the same problem.
There is no timeout because there is no connection generated at all.

**Comment by ibnpetr** [comment]
@vjernej The NC server address must be accessible from ONLYOFFICE Document Server and vice versa. If you access Nextcloud/Owncloud via HTTPS, please make sure that the certificate can be verified from the server itself and from inside the container with Document Server.
@gema2007 just try wget https://…de:8443 
Similar issues #74 or #85

**Comment by gema2007** [comment]
wget https://lokal.gesamtschule-marienheide.de:8443
--2018-03-12 17:25:24--  https://lokal.gesamtschule-marienheide.de:8443/
Auflösen des Hostnamens lokal.gesamtschule-marienheide.de (lokal.gesamtschule-marienheide.de)… 78.94.96.115
Verbindungsaufbau zu lokal.gesamtschule-marienheide.de (lokal.gesamtschule-marienheide.de)|78.94.96.115|:8443 … verbunden.
HTTP-Anforderung gesendet, auf Antwort wird gewartet … 302 Moved Temporarily
Platz: https://lokal.gesamtschule-marienheide.de:8443/welcome/ [folgend]
--2018-03-12 17:25:24--  https://lokal.gesamtschule-marienheide.de:8443/welcome/
Wiederverwendung der bestehenden Verbindung zu lokal.gesamtschule-marienheide.de:8443.
HTTP-Anforderung gesendet, auf Antwort wird gewartet … 200 OK
Länge: 4592 (4,5K) [text/html]
Wird in »index.html« gespeichert.

index.html                      100%[=======================================================>]   4,48K  --.-KB/s    in 0s      

2018-03-12 17:25:25 (286 MB/s) - »index.html« gespeichert [4592/4592]

I think there is no problem with certificates

**Comment by alexanderonlyoffice** [comment]
@gema2007, go to the Administration section in Nextcloud and try to save ONLYOFFICE address settings once again. Please send us a screenshot, if there are any issues when saving the settings.

**Comment by gema2007** [comment]
A timeout happens
![screen](https://user-images.githubusercontent.com/37214347/37332319-a156fc04-26a6-11e8-8226-b962e5250f67.png)

**Comment by alexanderonlyoffice** [comment]
Hello @gema2007,

We connected your document server to our Nextcloud instance and the settings were successfully saved, files can be opened and edited. 

It seems that the document server is inaccessible for your Nextcloud.

**Comment by gema2007** [comment]
Now it works!
There was a wrong entry in my /etc/hosts

Thank you!

**Comment by alexanderonlyoffice** [comment]
@gema2007, we are glad the issue has been resolved.

@vjernej please specify if the issue still exists.

**Comment by arnowelzel** [comment]
Can you tell me, if shared editing works in your environment? If two users open the same document - do they see each other in the user list and are the changes from one user visible by the other?

**Comment by alexanderonlyoffice** [comment]
Hello @arnowelzel,

Yes, it works. Please see #164

**Comment by arnowelzel** [comment]
@alexanderonlyoffice the question was directed to the issue opener, @gema2007 - since I am curious if I am the only user with problems in spreadsheets.

**Comment by gema2007** [comment]
I don't know, didn't try it.


--
Gesamtschule Marienheide
André Becker
Pestalozzistraße 7
51709 Marienheide
Tel.: 02264/45860
________________________________
Von: Arno Welzel <notifications@github.com>
Gesendet: Donnerstag, 15. März 2018 16:49
An: ONLYOFFICE/onlyoffice-owncloud
Cc: Becker, André; Mention
Betreff: Re: [ONLYOFFICE/onlyoffice-owncloud] Onlyoffice App does not work with nextcloud 13 (#162)


Can you tell me, if shared editing works in your environment? If two users open the same document - do they see each other in the user list and are the changes from one user visible by the other?

-

**Comment by vjernej** [comment]
@ibnpetr sorry for late response. 
I still have issue.

After I click on save button the error message comes up: "Error when trying to connect (Bad Request or timeout error)"

I entered the following URI address in "Document Editing Service address" field: https://office.domain.com:8000.

I'm capturing traffic on office.domain.com in the mean time: no packet comes to the server.

If I run "telnet office.domain.com 8000" from nextcloud's CLI session I get the response from Onlyoffice server.

If I run php curl script on nextcloud's web server I get the response from onlyoffice server.

I don't see any error message in web server's  error log fle.

I'm running php5. Is php7 required for connector to run successfuly?

**Comment by vjernej** [comment]
Eh, I found the issue: allow_url_fopen was blocking the connection.

**Comment by alexanderonlyoffice** [comment]
Hello @vjernej,

As far as we understood, the issue is resolved at the moment. Is that right?

**Comment by vjernej** [comment]
Hi @alexanderonlyoffice, yes, the problem is solved. Thank you for your concern.
