### ISSUE TITLE
Shared editing of spreadsheets does not work in Nextcloud 13

### ISSUE THREAD

**Issue by arnowelzel** [ONLYOFFICE/onlyoffice-owncloud#164]
Environment:

Ubuntu Server 16.04
Apache 2.4
PHP 7
Nextcloud 13.0.0
OnlyOffice 1.2.0
Spreedsheet Editor 5.0.7 CE in a Docker image as described in https://github.com/ONLYOFFICE/Docker-DocumentServer running 

The issue:

When multiple users open the same spreadsheet with OnlyOffice in Nextcloud 13 they don't see the other users at all and also not the changes by other users.

Even after leaving a spreadsheet and opening it again the changes by other users are not visible. It looks like every user only sees a local cached version of the spreadsheet. It is also not clear, what exacly is stored on the server - probably the version of the user which did the last edit.

Text documents and presentations work fine, only spreadsheets don't work properly.

**Comment by alexanderonlyoffice** [comment]
Hello @arnowelzel,

Please specify if this issue also occurs in document editor or only with spreadsheet files. 

We are going to make some tests to detect the reason of the issue.

**Comment by arnowelzel** [comment]
Yes, this only happens with spreadsheet files. In text documents or presentations there is no problem.

**Comment by arnowelzel** [comment]
The latest release of the app (1.3.0) fixed this issue for me. It works now without any problems so far.
