### ISSUE TITLE
Integrating with Community Server

### ISSUE THREAD

**Issue by nickian** [ONLYOFFICE/onlyoffice-owncloud#165]
I have NextCloud and ONLYOFFICE running successfully on two separate servers, both with SSL. However, I have the ONLYOFFICE community server installed as well as the document server and they running on Docker. 

NextCloud is saying "Error when trying to connect (Bad Request or timeout error)" When I put in the URL ("docs.mydomain.com" that goes to my community server).

Do I have to somehow set up a separate URL that is for the document server? Or should the community server URL work?

Thanks

**Comment by ibnpetr** [comment]
Set Document Editing Service address `https://docs.mydomain.com/ds-vpath/`
You also should insert the Secret Key, as JWT is enabled by default in the Enterprise Edition
(the value can be found in the file /var/www/onlyoffice/WebStudio/web.appsettings.config in the container with Community Server)
The string  `<add key="files.docservice.secret" value="M3gMHOVPTY5C" />`
Also make sure that the ONLYOFFICE 'jwt_header' in the /var/www/nextcloud/config/config.php  is the same as in Community Server, `<add key="files.docservice.secret.header" value="AuthorizationJwt" />`

**Comment by nickian** [comment]
Thank you!

What is the purpose of setting the secret key? Does this just mean anyone can access and use my document server without it? But they cannot access files I assume, right?

**Comment by nickian** [comment]
Also, where does this value come from: "M3gMHOVPTY5C"? Does it matter what that string is, or does it just have to match on both ends?
