### ISSUE TITLE
Add Nextcloud specific server side encryption support

### ISSUE THREAD

**Issue by CitoplasmaX** [ONLYOFFICE/onlyoffice-owncloud#168]
I will reference this topic of a colective that are using Nextcloud:
https://forum.disroot.org/t/what-do-you-think-about-use-onlyoffice-instead-collabora-online/3132

**Comment by alexanderonlyoffice** [comment]
Hello @CitoplasmaX, please see issue #26 for answer.

**Comment by CitoplasmaX** [comment]
Okay

**Comment by alexanderonlyoffice** [comment]
Duplicate of #26
