### ISSUE TITLE
[SOLVED] Only office does not work since new  Nextcloud 13 release

### ISSUE THREAD

**Issue by Bschalck** [ONLYOFFICE/onlyoffice-owncloud#170]
Hy , 

I have a mistake since I upgraded to onlyoffice 1.3.0.
The log tells this : 

CommandRequest on check error: Bad Request or timeout error

file_get_contents(https://collabora.devloprog.org/ConvertService.ashx): failed to open stream: HTTP request failed! HTTP/1.1 502 Bad Gateway at /var/www/nextcloud/apps/onlyoffice/lib/documentservice.php#351

Regards,

**Comment by ExaconAT** [comment]
Confirmed, same error!

**Comment by alexanderonlyoffice** [comment]
Hello @Bschalck,

Please check the accessibility of the document server from the server where NC is installed. Use wget command to do it: wget https://your_document_server_address

**Comment by Bschalck** [comment]
Thanks for the return.
I modify the file /etc/hosts and now the NC can do the wget command.
But now I got this error : 

 file_get_contents(https://collabora.devloprog.org/ConvertService.ashx):  failed to open stream: HTTP request failed! HTTP/1.1 502 Bad Gateway   at /var/www/nextcloud/apps/onlyoffice/lib/documentservice.php#351

**Comment by Bschalck** [comment]
I found this issue , and your comment : 
https://github.com/ONLYOFFICE/onlyoffice-owncloud/issues/162#issuecomment-372943278

However, I can make a wget on https://collabora.devloprog.org/ConverSrvice.ashx, but I got this error : <?xml version="1.0" encoding="utf-8"?><FileResult><Error>-1</Error></FileResult>

**Comment by Bschalck** [comment]
For information, here is my apache conf : 
```
<VirtualHost *:443>
                        ServerName collabora.devloprog.org
                loglevel warn
                ErrorLog ${APACHE_LOG_DIR}/onlyoffice_error.log
                CustomLog ${APACHE_LOG_DIR}/onlyoffice_access.log combined
                        # SSL configuration, you may want to take the easy route instead and use Lets Encrypt!
                        SSLEngine on
                        SSLCertificateFile /etc/letsencrypt/live/collabora.devloprog.org/fullchain.pem
                        SSLCertificateKeyFile /etc/letsencrypt/live/collabora.devloprog.org/privkey.pem
                        #SSLCertificateChainFile /path/to/intermediate_certificate
                        SSLProtocol             all -SSLv2 -SSLv3
                        SSLCipherSuite ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA:ECDHE-ECDSA-DES-CBC3-SHA:ECDHE-RSA-DES-CBC3-SHA:EDH-RSA-DES-CBC3-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:DES-CBC3-SHA:!DSS
                        SSLHonorCipherOrder     on

                        # Encoded slashes need to be allowed
                        #AllowEncodedSlashes NoDecode

                        # Container uses a unique non-signed certificate
                        #SSLProxyEngine On
                        #SSLProxyVerify None
                        #SSLProxyCheckPeerCN Off
                        #SSLProxyCheckPeerName Off
                        #SSLProxyCheckPeerExpire off

                        # keep the host
                        ProxyPreserveHost On
SetEnvIf Host "^(.*)$" THE_HOST=$1
RequestHeader set X-Forwarded-Proto https
ProxyAddHeaders Off

                        ProxyPassMatch (.*)(\/websocket)$ "ws://127.0.0.1:10010/$1$2"
                        ProxyPass / "http://127.0.0.1:10010/"
                        ProxyPassReverse / "http://127.0.0.1:10010/"
</VirtualHost>
```

**Comment by Bschalck** [comment]
Hy ,
I found a solution . 

I chnage my ISP provider, and the localloop is not activate .
So from my docker instance, I can not ping my Nexctloud Server WAN name ( nextcloud.devloprog.org ).

The solution is to put, into the DS docker, the **LOCAL** ip for : 
 - nexctloud server  and DS server  ( the same LOCAL IP ) 

Now it works

**Comment by jbescudie** [comment]
Bschalck, can you please detail how to change the LOCAL ip in the DS docker ?

**Comment by Bschalck** [comment]
Hy jbescudie.
My explain is not very clear, sorry.
I mean , I have , on **AN ONLY SERVER** , nextcloud and onlyoffice-docker.
So they have together the same local IP ( the servr local IP ) .
In my /etc/hosts, I juste add , in docker **and** in my server : 
local_ip nexcloude.devloprog collabora.devloprog.org

I expect it's clarify the explaination :)

**Comment by jbescudie** [comment]
Thanks for the details. 
I don't think that's my issue, I'm using the owncloud+onlyoffice docker image as [in this guide](https://www.linuxbabe.com/docker/onlyoffice-nextcloud-integration-docker)
