### ISSUE TITLE
Open openDocument files (.odt, .ods, ...) with onlyoffice

### ISSUE THREAD

**Issue by mrflos** [ONLYOFFICE/onlyoffice-owncloud#174]
Hello,
Thanks for this really nice online office program, it's great!

I can associate .docx, .xlsx with onlyoffice to open them online (in the settings those extensions are checked), but I cannot do it for openDocuments (.ods, .odt), I don't have the filetype available in the settings.

Is there a way to open those files ? If not is this feature planned?

Thanks a lot!

**Comment by alexanderonlyoffice** [comment]
Hello @mrflos,

.ods and .odt files can be opened for viewing or conversed from the action menu (three dots icon). After the conversion the file will be copied to the same folder.

**Comment by mrflos** [comment]
Ok, thanks for the answer, do you think that onlyoffice could support opendocument without converting to docx or other closed formats? Some administrations like the english gouvernment acknowledge openDocument as an official standard. Thanks à lot.

**Comment by CitoplasmaX** [comment]
Sorry but, Microsoft Office XML is an open format:

https://en.wikipedia.org/wiki/Office_Open_XML

**Comment by mrflos** [comment]
To clarify, my issue is that i would like to handle (edit and save) .ods and .odt files in onlyoffice like it is done now for Office_Open_XML .  
I would like to have the choice of the format, so that i can share docs and collaborate in a groups favorite format of documents.

**Comment by ibnpetr** [comment]
> I would like to have the choice of the format,


Thanks a lot for the feedback.
We do not currently plan to include ods and odt into the list of supported output formats for the NC/OC connector.

**Comment by LinneyS** [comment]
dfc880b016aad22129255f3625b0032b07ea69ac
