### ISSUE TITLE
Cannot upgrade to Nextcloud integration app

### ISSUE THREAD

**Issue by rollanders** [ONLYOFFICE/onlyoffice-owncloud#175]
I have NC 13.0 in docker with Onlyoffice, nginx and MariaDB. Works well. I get a notification that there is a new version 1.3 of the integration app. Click on that - it shows upgrading. But when I get back no upgrade has taken place. 

Maybe same issue as "App (files_pdfviewer) update do not work properly #288" https://github.com/nextcloud/docker/issues/288

**Comment by LinneyS** [comment]
Please try `chown -R www-data:www-data app/`
where `app/` is directory with installed applications

**Comment by rollanders** [comment]
It worked. Thanks.

**Comment by rollanders** [comment]
Sorry - it did not work...

**Comment by alexanderonlyoffice** [comment]
Hello @rollanders,

Try to contact Nextcloud support. The reason might be in the market.

**Comment by alexanderonlyoffice** [comment]
Hello @rollanders, please specify if the issue still exists.

**Comment by LinneyS** [comment]
This issue was closed due to no response.
