### ISSUE TITLE
services.CoAuthoring.autoAssembly not working

### ISSUE THREAD

**Issue by duckhawk** [ONLYOFFICE/onlyoffice-owncloud#176]
I've tried enable forcesave, like described in https://api.onlyoffice.com/editors/save#forcesave

`      "autoAssembly": {
        "enable": true,
        "interval": "5m",
        "step": "1m"
      }
`

But whatever, onlyoffice saves files only if all users close editors.
Or this is an expected behavior?

**Comment by LinneyS** [comment]
Forcesave is not available at the moment
Dublicated #116
