### ISSUE TITLE
some collaboration features missing (NextCloud 11.0.2)

### ISSUE THREAD

**Issue by DavidPatShuiFong** [ONLYOFFICE/onlyoffice-owncloud#18]
Unable to see, in the activity feed, any editing activity done by people other than the primary owner of the file.

When the document is open, and clicking the 'person' tab on the left hand side, can only see an icon representing the person currently opening the file, and none of the other collaborators.

**Comment by JohnPerkin** [comment]
Hello!
Please attach screenshots of the document which is opened by different users where we can see users' list. Also attach screenshot of the last part of source code like on [this](http://take.ms/csBu0) screenshot.

**Comment by DavidPatShuiFong** [comment]
My apologies, it looks like the user list shows several users, as in the following screenshot

![image](https://cloud.githubusercontent.com/assets/8335820/24071723/30e952c6-0c2d-11e7-9ebe-53f05aa6db7a.png)

**Comment by DavidPatShuiFong** [comment]
However, the modification/activity list still only lists the changes by 'vkelim' (who was the original creator of the document). It doesn't list the activities/changes made by the current user shown in this screenshot (who is firehand), although it does mention the 'comment'.

My apologies, I couldn't figure out what to do with the sourcecode provided by JohnPerkin!

![image](https://cloud.githubusercontent.com/assets/8335820/24071747/bf9c8cc2-0c2d-11e7-8858-37d6b61466f0.png)

**Comment by JohnPerkin** [comment]
Hello @DavidPatShuiFong 
Open a document which is being edited by several persons, highlight its URL and press Ctrl + U. At the end of the opened page you will find the part of code that you need. Attach it here.

**Comment by JohnPerkin** [comment]
Hello @DavidPatShuiFong 
On the current moment is released integration app 1.0.4. Please update ownCloud/Nextcloud app to the latest version and tell us if it helped or did not.

**Comment by LinneyS** [comment]
Could you please specify if the problem recurs or we can close the topic.
