### ISSUE TITLE
Bad Request or timeout within Nextcloud 13.0.1

### ISSUE THREAD

**Issue by riegercloud** [ONLYOFFICE/onlyoffice-owncloud#180]
I made a fresh installation of Ubuntu 16.04.4 LTS 64Bit and OO-Document Server following your instructions: [Link](https://helpcenter.onlyoffice.com/de/server/linux/document/linux-installation.aspx) 

The document server is working properly and reachable using SSL:

![grafik](https://user-images.githubusercontent.com/20593693/39305792-8f1e8176-495e-11e8-9aba-530c75483440.png)

https://cloudsoffice.luft-it.de 
IP: 192.x.y.24

The modified "onlyoffice-documentserver.conf"

```
include /etc/nginx/includes/onlyoffice-http.conf;
server {
  listen 0.0.0.0:80;
  listen [::]:80 default_server;
  server_name cloudsoffice.luft-it.de cloudsoffice;
  server_tokens off;
  root /nowhere;
  rewrite ^ https://$host:443$request_uri? permanent;
}
server {
  listen 127.0.0.1:80;
  listen [::1]:80;
  server_name localhost;
  server_tokens off;
  include /etc/nginx/includes/onlyoffice-documentserver-common.conf;
  include /etc/nginx/includes/onlyoffice-documentserver-docservice.conf;
}
server {
  listen 0.0.0.0:443 ssl;
  listen [::]:443 ssl default_server;
  server_name cloudsoffice.luft-it.de cloudsoffice;
  server_tokens off;
  root /usr/share/nginx/html;
  ssl_certificate /etc/ssl/luft-it.de/fullchain.pem;
  ssl_certificate_key /etc/ssl/luft-it.de/privkey.pem;
  ssl_protocols TLSv1.2;
  ssl_ciphers 'ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256';
  ssl_prefer_server_ciphers on;
  add_header Strict-Transport-Security max-age=15768000;
  ssl_session_cache builtin:1000 shared:SSL:10m;
  add_header X-Content-Type-Options nosniff;
  location ~ /.well-known/acme-challenge {
     root /var/www/onlyoffice/;
     allow all;
  }
  include /etc/nginx/includes/onlyoffice-documentserver-*.conf;
}
```

On a separate server 
IP IP: 192.x.y.25
a Nextcloud 13.0.1 with the latest OO-App from Nextcloud App-Repository is running properly either.

But trying to connect Nextcloud to the OO-DS failed:

![grafik](https://user-images.githubusercontent.com/20593693/39306008-3b3ac2e4-495f-11e8-8306-c91a742efde6.png)

The following errors were thrown in the nextcloud.log:

![grafik](https://user-images.githubusercontent.com/20593693/39306550-c1d36706-4960-11e8-8636-4cf4f0db18ae.png)

`{"reqId":"n7OPb869e74vb70rfK5n","level":3,"time":"2018-04-26T14:39:48+02:00","remoteAddr":"x.y.z.a","user":"MYUSER","app":"PHP","method":"PUT","url":"\/apps\/onlyoffice\/ajax\/settings","message":"file_get_contents(https:\/\/cloudsoffice.luft-it.de\/coauthoring\/CommandService.ashx): failed to open stream: Connection timed out at \/var\/www\/cloud.luft-it.de\/apps\/onlyoffice\/lib\/documentservice.php#351","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:59.0) Gecko\/20100101 Firefox\/59.0","version":"13.0.1.1"}
{"reqId":"n7OPb869e74vb70rfK5n","level":3,"time":"2018-04-26T14:39:48+02:00","remoteAddr":"46.253.79.107","user":"MYUSER","app":"onlyoffice","method":"PUT","url":"\/apps\/onlyoffice\/ajax\/settings","message":"CommandRequest on check error: Bad Request oder Timeout Fehlermeldung","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:59.0) Gecko\/20100101 Firefox\/59.0","version":"13.0.1.1"}
{"reqId":"ICRSmH9ZcmQ5d8q6A2tu","level":3,"time":"2018-04-26T14:41:48+02:00","remoteAddr":"46.253.79.107","user":"MYUSER","app":"PHP","method":"PUT","url":"\/apps\/onlyoffice\/ajax\/settings","message":"file_get_contents(https:\/\/cloudsoffice.luft-it.de\/coauthoring\/CommandService.ashx): failed to open stream: Connection timed out at \/var\/www\/cloud.luft-it.de\/apps\/onlyoffice\/lib\/documentservice.php#351","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:59.0) Gecko\/20100101 Firefox\/59.0","version":"13.0.1.1"}
{"reqId":"ICRSmH9ZcmQ5d8q6A2tu","level":3,"time":"2018-04-26T14:41:48+02:00","remoteAddr":"46.253.79.107","user":"MYUSER","app":"onlyoffice","method":"PUT","url":"\/apps\/onlyoffice\/ajax\/settings","message":"CommandRequest on check error: Bad Request oder Timeout Fehlermeldung","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:59.0) Gecko\/20100101 Firefox\/59.0","version":"13.0.1.1"}
`

Nextcloud is built of:
PHP 7.2 (fpm)
MariaDB
Ubuntu 16.04.4 LTS 64 Bit

I would really appreciate your assistance.
Cheers, Carsten!

**Comment by riegercloud** [comment]
I also added

>   'onlyoffice' =>
  array (
    'verify_peer_off' => TRUE,
  ),

to /var/www/nextcloud/config.php

**Comment by riegercloud** [comment]
Hi Alexander,
i tried both, the IP-Adresses as well the FQDN.
With the ip mentioned above i just wanted to point out, that two different servers are in place.

Thank you for your assistance  - Carsten

**Comment by riegercloud** [comment]
We made furthe investigation and found the cause:
Sophos firewall blocked traffic (DMZ). We added a rule.
Now it works as expected.

**Comment by jocarren** [comment]
> I also added
> 
> ```
>     'onlyoffice' =>
>     array (
>     'verify_peer_off' => true,
>     ),
> ```
> 
> to /var/www/nextcloud/config.php

This worked for me, thanks @riegercloud
