### ISSUE TITLE
OnlyOffice makes settings page crash (nextcloud 13.0.1)

### ISSUE THREAD

**Issue by olinox14** [ONLYOFFICE/onlyoffice-owncloud#182]
After having updated nextcloud to the version 13.0.1, i could'nt access to the settings page anymore. I foud out in the logs it was caused by this App. Here are the error message from the log:

`{"reqId":"UjuUSHkVysbwMTE8hrvt","level":3,"time":"2018-05-02T11:35:28+02:00","remoteAddr":"xxxxxx","user":"olinox14","app":"index","method":"GET","url":"\/index.php\/settings\/user","message":"Exception: {\"Exception\":\"OCP\\\\AutoloadNotAllowedException\",\"Message\":\"Autoload path not allowed: \\\/var\\\/www\\\/html\\\/nextcloud\\\/apps\\\/onlyoffice\\\/lib\\\/adminsection.php\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/autoloader.php(158): OC\\\\Autoloader->isValidPath('\\\/var\\\/www\\\/html\\\/n...')\\n#1 [internal function]: OC\\\\Autoloader->load('OCA\\\\\\\\Onlyoffice\\\\\\\\...')\\n#2 [internal function]: spl_autoload_call('OCA\\\\\\\\Onlyoffice\\\\\\\\...')\\n#3 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Utility\\\/SimpleContainer.php(95): ReflectionClass->__construct('OCA\\\\\\\\Onlyoffice\\\\\\\\...')\\n#4 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Utility\\\/SimpleContainer.php(118): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->resolve('OCA\\\\\\\\Onlyoffice\\\\\\\\...')\\n#5 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/ServerContainer.php(132): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->query('OCA\\\\\\\\Onlyoffice\\\\\\\\...')\\n#6 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/Settings\\\/Manager.php(346): OC\\\\ServerContainer->query('OCA\\\\\\\\Onlyoffice\\\\\\\\...')\\n#7 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/Settings\\\/Manager.php(374): OC\\\\Settings\\\\Manager->query('OCA\\\\\\\\Onlyoffice\\\\\\\\...')\\n#8 \\\/var\\\/www\\\/html\\\/nextcloud\\\/settings\\\/Controller\\\/CommonSettingsTrait.php(100): OC\\\\Settings\\\\Manager->getAdminSections()\\n#9 \\\/var\\\/www\\\/html\\\/nextcloud\\\/settings\\\/Controller\\\/CommonSettingsTrait.php(51): OC\\\\Settings\\\\Controller\\\\PersonalSettingsController->formatAdminSections('personal', 'personal-info')\\n#10 \\\/var\\\/www\\\/html\\\/nextcloud\\\/settings\\\/Controller\\\/CommonSettingsTrait.php(125): OC\\\\Settings\\\\Controller\\\\PersonalSettingsController->getNavigationParameters('personal', 'personal-info')\\n#11 \\\/var\\\/www\\\/html\\\/nextcloud\\\/settings\\\/Controller\\\/PersonalSettingsController.php(57): OC\\\\Settings\\\\Controller\\\\PersonalSettingsController->getIndexResponse('personal', 'personal-info')\\n#12 [internal function]: OC\\\\Settings\\\\Controller\\\\PersonalSettingsController->index('personal-info')\\n#13 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(161): call_user_func_array(Array, Array)\\n#14 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(91): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OC\\\\Settings\\\\Controller\\\\PersonalSettingsController), 'index')\\n#15 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(115): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OC\\\\Settings\\\\Controller\\\\PersonalSettingsController), 'index')\\n#16 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main('OC\\\\\\\\Settings\\\\\\\\Con...', 'index', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#17 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#18 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/Route\\\/Router.php(297): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#19 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/base.php(998): OC\\\\Route\\\\Router->match('\\\/settings\\\/user')\\n#20 \\\/var\\\/www\\\/html\\\/nextcloud\\\/index.php(37): OC::handleRequest()\\n#21 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/autoloader.php\",\"Line\":134}","userAgent":"Mozilla\/5.0 (Windows NT 6.1; Win64; x64; rv:59.0) Gecko\/20100101 Firefox\/59.0","version":"13.0.1.1"}
{"reqId":"UjuUSHkVysbwMTE8hrvt","level":3,"time":"2018-05-02T11:35:28+02:00","remoteAddr":"86.202.171.241","user":"olinox14","app":"PHP","method":"GET","url":"\/index.php\/settings\/user","message":"Cannot modify header information - headers already sent by (output started at \/var\/www\/html\/nextcloud\/apps\/passman\/personal.php:1) at \/var\/www\/html\/nextcloud\/lib\/private\/legacy\/response.php#108","userAgent":"Mozilla\/5.0 (Windows NT 6.1; Win64; x64; rv:59.0) Gecko\/20100101 Firefox\/59.0","version":"13.0.1.1"}
`

**Comment by alexanderonlyoffice** [comment]
Hello @olinox14,

Unfortunately, we cannot reproduce the mentioned issue. Please send us a screenshot that illustrates the issue.

**Comment by alexanderonlyoffice** [comment]
@olinox14, we are glad the issue has been resolved.

**Comment by noamanahmed** [comment]
I am having the same issue

I need only office to work
