### ISSUE TITLE
new create a PPT , and PPT is displayed as Chinese garbled.

### ISSUE THREAD

**Issue by hymany** [ONLYOFFICE/onlyoffice-owncloud#189]

**Comment by hymany** [comment]
![123](https://user-images.githubusercontent.com/19706331/41275496-a1bb743c-6e53-11e8-8f11-4f8c6a08ddd6.png)

**Comment by hymany** [comment]
Do you have any solutions to this problem？

**Comment by Rita-Bubnova** [comment]
Hello, @hymany.
Thank you. I can confirm - this is a bug, issue 37927 in our internal issue tracker.

**Comment by hymany** [comment]
Hello, can the next version of this bug be solved？

**Comment by Rita-Bubnova** [comment]
It will be released in next bugfix in several months.
