### ISSUE TITLE
Apache Reverse Proxy; Connector wont load

### ISSUE THREAD

**Issue by StanESmith** [ONLYOFFICE/onlyoffice-owncloud#19]
I'm having trouble with getting NC to load the connector. My setup is: Docker -->Apache Reverse Proxy (Handles HTTPS certs as well) --> Outside world. When going to https://onlyoffice.mydomain.com the page loads and says everything is well and good. Now when putting that direct address into NC, the connector never loads, doesn't give any error message or anything. It shows up with a blank white page. One other thing to note, when I go to NC on the internal IP address and then put the Docker internal IP address into the NC connector admin page, everything loads and works 100% as it should. That makes me believe it is something to do with my reverse proxy setup. Here is that code:

    <IfModule mod_ssl.c>
    <VirtualHost *:80>
        ServerName onlyoffice.mydomain.com
        ServerAdmin myemail@mydomaim.com
        RewriteEngine on
        RewriteCond %{SERVER_NAME} =onlyoffice.mydomain.com
        RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,QSA,R=permanent]
    </VirtualHost>
    <VirtualHost *:443>
        ServerName onlyoffice.mydomain.com
        ServerAdmin myemail@mydomaim.com
        <proxy *>
        AddDefaultCharset off
        Order Allow,Deny
        Allow from all
        </proxy>
        ProxyRequests     Off
        ProxyPreserveHost On
        <location />
        RequestHeader unset Accept-Encoding
        ProxyPass http://192.168.0.22:78/
        ProxyPassReverse http://192.168.0.22:78/
        Order allow,deny
        Allow from All
        </location>
        ProxyPass "/websocket" "wss://192.168.0.22:78/websocket"
        ProxyPassReverse "/websocket" "wss://192.168.0.22:78/websocket"
        SSLCertificateFile /usr/local/etc/letsencrypt/live/onlyoffice.mydomain.com/fullchain.pem
        SSLCertificateKeyFile /usr/local/etc/letsencrypt/live/onlyoffice.mydomain.com/privkey.pem
    </VirtualHost>
    </IfModule>

**Comment by rafilkmp3** [comment]
Sames here with traefik i can see api.js over https, follow error
![image](https://cloud.githubusercontent.com/assets/12433667/23922863/f55a3416-08e2-11e7-8b77-f07edb319271.png)

and my docker compose
version: '2'
services:
  onlyoffice-documentserver-data:
    container_name: onlyoffice-documentserver-data
    image: onlyoffice/documentserver:latest
    environment:
      - ONLYOFFICE_DATA_CONTAINER=true
      - POSTGRESQL_SERVER_HOST=onlyoffice-postgresql
      - POSTGRESQL_SERVER_PORT=5432
      - POSTGRESQL_SERVER_DB_NAME=onlyoffice
      - POSTGRESQL_SERVER_USER=onlyoffice
      - RABBITMQ_SERVER_HOST=onlyoffice-rabbitmq
      - RABBITMQ_SERVER_USER=guest
      - RABBITMQ_SERVER_PASS=guest
      - REDIS_SERVER_HOST=onlyoffice-redis
      - REDIS_SERVER_PORT=6379
    stdin_open: true
    restart: always
    networks:
      - onlyoffice
    volumes:
       - /var/www/onlyoffice/Data
       - /var/log/onlyoffice
       - /var/lib/onlyoffice/documentserver/App_Data/cache/files
       - /var/www/onlyoffice/documentserver-example/public/files
       - /usr/share/fonts
       
  onlyoffice-documentserver:
    image: onlyoffice/documentserver:latest
    depends_on:
      - onlyoffice-documentserver-data
      - onlyoffice-postgresql
      - onlyoffice-redis
      - onlyoffice-rabbitmq
    labels:
      - "traefik.enable=true"
      - "traefik.backend=onlyoffice"
      - "traefik.frontend.rule=Host:onlyoffice.mydomain.com"
      - "traefik.docker.network=reverseproxy_default"
      - "traefik.port=80"
    environment:
      - ONLYOFFICE_DATA_CONTAINER_HOST=onlyoffice-documentserver-data
      - BALANCE=uri depth 3
      - EXCLUDE_PORTS=443
      - HTTP_CHECK=GET /healthcheck
      - EXTRA_SETTINGS=http-check expect string true
      # Uncomment the string below to redirect HTTP request to HTTPS request.
      - FORCE_SSL=true
    stdin_open: true
    restart: always
    networks:
      - onlyoffice
      - "reverseproxy_default"
    expose:
      - '80'
    volumes_from:
     - onlyoffice-documentserver-data
       
  onlyoffice-redis:
    container_name: onlyoffice-redis
    image: redis
    restart: always
    networks:
     - onlyoffice
    expose:
      - '6379'

  onlyoffice-rabbitmq:
    container_name: onlyoffice-rabbitmq
    image: rabbitmq
    restart: always
    networks:
     - onlyoffice
    expose:
      - '5672'

  onlyoffice-postgresql:
    container_name: onlyoffice-postgresql
    image: postgres:9.5
    environment:
      - POSTGRES_DB=onlyoffice
      - POSTGRES_USER=onlyoffice
    networks:
      - onlyoffice
    restart: always
    expose:
      - '5432'
    volumes:
      - postgresql_data:/var/lib/postgresql

networks:
  onlyoffice:
    driver: 'bridge'
  reverseproxy_default:
    external:
      name: reverseproxy_default    

volumes:
  postgresql_data:

**Comment by JohnPerkin** [comment]
@StanESmith 
Please replace internal IP-addresses in your configuration with the domain name.

**Comment by StanESmith** [comment]
The apache server configuration or on the server that onlyoffice is installed too?

**Comment by JohnPerkin** [comment]
In apache server configuration

**Comment by StanESmith** [comment]
If I do that then the onlyoffice website will not populate. The Document server is only accessible directly from an internal IP. All external websites for my services are served access through an apache webserver. This keeps flow of traffic to only one server and IP address. Nginx on the document server is not accessible or serving up the domain for onlyoffice-document server.

**Comment by evilstiefel** [comment]
I'm having the exakt same problem. Unknown error shows up when opening any office document through nextcloud. I'm also using an Apache Reverse Proxy to make the Docker Container running onlyoffice/documentserver available.

**Comment by emresaracoglu** [comment]
I'm having the exact same problem..

**Comment by TomTeeJay** [comment]
Mmm strange I am running in similar problems but my Onlyoffice even doesn't appear cause iFrame is blocked... here is my config:

Firewall with Port Forwarding 80, 443 to Nextcloud Host (cloud.xyz.de). On this host I've setup reverse proxy (office.xyz.de) pointing to internal Onlyoffice Server. I've installed a let's encrypt SSL cert on my Apache forcing everything to https. This works pretty good and when calling from the Web the "Document Server is running" on welcome page is shown properly.

I've installed the App in my Nextcloud and put the public domain link (office.xyz.de). The secret passpharse is left blank. But when trying to edit a document I see a blank window with blocked iframe content. 

![blocked](https://cloud.githubusercontent.com/assets/25870631/24851167/fa9dbeb6-1dd2-11e7-982e-034485d96790.jpg)
![html-content](https://cloud.githubusercontent.com/assets/25870631/24851168/fac226c0-1dd2-11e7-9cc5-4b2ef272555f.jpg)

I've updated my Content-Security-Policy and added the office.xyz.de Server but still not working due uncrypted http:// Link. But https:// was assigned to DocumentServerUrl in Settings.

![admin-oo](https://cloud.githubusercontent.com/assets/25870631/24851250/4b30420e-1dd3-11e7-8a5f-0e1450a5da90.jpg)

**Comment by emresaracoglu** [comment]
Hi @TomTeeJay Can you share the code of `Content-Security-Policy`?

**Comment by TomTeeJay** [comment]
of course, i replace my domain with xxx and left out everything above Do-Not-Change-Anything line in Nextclouds Default htaccess:

`
#### DO NOT CHANGE ANYTHING ABOVE THIS LINE ####
ErrorDocument 403 //core/templates/403.php
ErrorDocument 404 //core/templates/404.php
Header set Content-Security-Policy "frame-ancestors 'self' cloud.xxx.de office.xxx.de; default-src 'self' office.xxx.de; img-src 'self' office.xxx.de; object-src 'self' office.xxx.de; style-src 'self' 'unsafe-inline' office.xxx.de; script-src 'self' 'unsafe-eval' 'unsafe-inline' office.xxx.de"
Header set Strict-Transport-Security "max-age=63072000;"
`

**Comment by TomTeeJay** [comment]
just got the hint to try this in another browser and yes firefox behaves in a different way: Now I get nginx error page... interestingly when clicking on iframe link my onlyoffice document window opens up.

![2](https://cloud.githubusercontent.com/assets/25870631/24852628/84fd6be2-1dd8-11e7-8669-fb4031f05da9.jpg)


![1](https://cloud.githubusercontent.com/assets/25870631/24852630/87b8c9bc-1dd8-11e7-9722-215cda5f5c7d.jpg)

**Comment by TomTeeJay** [comment]
I am the Apache Woodo master! :-)

It runs but you need to put a private cert on your OO server and modify your apache config file.

![heureka](https://cloud.githubusercontent.com/assets/25870631/24864379/4e32595c-1e04-11e7-8fcf-32f7d4e43d40.jpg)

**Comment by StanESmith** [comment]
Would you elaborate more on the steps you took to fix this issue?

**Comment by Twilek-de** [comment]
Especially in the light that by using the reverse proxy in Apache you want to avoid giving OO its own certificate. Could you please show the modifications to your apache config... Thanks...

**Comment by Twilek-de** [comment]
Ok I think I recreated to dirty trick you pulled ;-) 
I am using lets encrypt. First I created a directory in /var/onlyoffice-certs/ into which I hardlinked the letsencrypt live symlinks to onlyoffice.crt and onlyoffice.key (somehow docker won´t accept symbolic links in mapped directories). Then I started docker with `docker run -i -t -d -v /var/onlyoffice-certs/:/var/www/onlyoffice/Data/certs/  -p 88:80 -p 448:443 onlyoffice/documentserver`.

My apache config looks like this (I call this dirty because as far as I understand it OO will encrypt the data, then apache will decrypt it and re-encrypt it again with the same certificate):

```
<VirtualHost  *:80>
    ServerName oof.xxx.de
    RewriteEngine on
    RewriteCond %{SERVER_NAME} =oof.xxx.de
    RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,QSA,R=permanent]
</VirtualHost>
<VirtualHost *:443>
        ServerName oof.xxx.de
        SSLEngine On
        SSLProxyEngine On
        ProxyPreserveHost On
        ProxyRequests Off
        SSLProxyCheckPeerCN off
        SSLProxyCheckPeerExpire off
        SSLInsecureRenegotiation on
        SSLProxyVerify none
        SSLVerifyClient none
        SSLCertificateFile /etc/letsencrypt/live/oof.xxx.de/fullchain.pem
        SSLCertificateKeyFile /etc/letsencrypt/live/oof.xxx.de/privkey.pem
        SSLProxyCheckPeerName off
        RequestHeader unset Accept-Encoding
        ProxyPass / https://localhost:448/
        ProxyPassReverse / https://localhost:448/
        ProxyPass "/websocket" "wss://localhost:448/websocket"
        ProxyPassReverse "/websocket" "wss://localhost:448/websocket"
    <proxy *>
       AddDefaultCharset off
       Order Allow,Deny
       Allow from all
    </proxy>
</VirtualHost>
```
As I gobbled this up from different sources I am not sure that all parameters are really needed but it works. I may have to restart the docker container when the certificate gets updated but we will see.

**Comment by JohnPerkin** [comment]
Please try to update ownCloud/Nextcloud ONLYOFFICE integration app to the latest version

**Comment by emresaracoglu** [comment]
Hi again @TomTeeJay 
I getting still errors for OO and Nextcloud.
Can you share your Apache file? Maybe he can help me to solve the problem :)

**Comment by Twilek-de** [comment]
@JohnPerkin Could you tell us what was changed in the latest version regarding Apache integration. For me it is working as before. Is there something new we should try out?

**Comment by LinneyS** [comment]
Could you please specify if the problem recurs or we can close the topic.

**Comment by StanESmith** [comment]
I have up on onlyoffice a month Sadie since I could not get it to work. The
issue stemmed from passing on certificates from my apache setup. I'd have
to start from scratch with onlyoffice again to try and recreate the issue.

**Comment by alexanderonlyoffice** [comment]
@StanESmith, please specify how it is going with ONLYOFFICE and if the issue with apache proxy still exists.

**Comment by StanESmith** [comment]
It isn't, I never got it to work and uninstalled it from my setup.
