### ISSUE TITLE
Error when trying to connect (Error occurred in the document service: Invalid token)

### ISSUE THREAD

**Issue by pixel75** [ONLYOFFICE/onlyoffice-owncloud#193]
when I try to integrate Onwcloud to Onlyoffice I receive this error back:
Error when trying to connect (Error occurred in the document service: Invalid token)

which should be the issue?

regards,

**Comment by alexanderonlyoffice** [comment]
Hello @pixel75,

Please specify OS of the server where Document Server is installed and its installation type (Docker or DEB/RPM). 

It seems that the problem is in JWT, but we need to know your OS and installation type to tell you where to find required configs. 

Send us also a screenshot of ONLYOFFICE address settings in Owncloud.

**Comment by pixel75** [comment]
Thanks for the reply.

Owncloud :Linux owncloud 3.16.0-6-amd64 #1 SMP Debian 3.16.56-1+deb8u1 (2018-05-08) x86_64 GNU/Linux

Onlyoffice: Linux onlyoffice 4.15.0-23-generic #25-Ubuntu SMP Wed May 23 18:02:16 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

On onlyoffice default.json I change:

 "secret": {
        "browser": {
          "string": "SECRET",
          "file": "",
          "tenants": {}
        },
        "inbox": {
          "string": "SECRET",
          "file": "",
          "tenants": {}
        },
        "outbox": {
          "string": "SECRET",
          "file": ""
        },
        "session": {
          "string": "SECRET",
          "file": ""
        }
      },
      "token": {
        "enable": {
          "browser": true,
          "request": {
            "inbox": true,
            "outbox": true
          }
        },

attached both onlyoffice DS & OC settings
thanks,

![onlyoffice](https://user-images.githubusercontent.com/29924678/41969623-605726c4-7a08-11e8-8c50-7a0c659fd4a2.PNG)
![owncloud](https://user-images.githubusercontent.com/29924678/41969776-cbd3560c-7a08-11e8-8b3f-64aaa8477bdb.PNG)

**Comment by pixel75** [comment]
Thanks,
now I've got this:
"CommandRequest on check error: Error occurred in the document service: Error while downloading the document file to be converted."


This is the log on OC:
{"reqId":"YZuxSGov2GqAhydJNAIY","level":1,"time":"June 27, 2018 15:33:18","remoteAddr":"proxy","user":"admin","app":"onlyoffice","method":"PUT","url":"\\/index.php\\/apps\\/onlyoffice\\/ajax\\/settings","message":"SetDocumentServerUrl: https:\\/\\/onlyoffice.<domain>.eu\\/"}
{"reqId":"YZuxSGov2GqAhydJNAIY","level":1,"time":"June 27, 2018 15:33:18","remoteAddr":"proxy","user":"admin","app":"onlyoffice","method":"PUT","url":"\\/index.php\\/apps\\/onlyoffice\\/ajax\\/settings","message":"SetDocumentServerInternalUrl: https:\\/\\/onlyoffice.<domain>.eu\\/"}
{"reqId":"YZuxSGov2GqAhydJNAIY","level":1,"time":"June 27, 2018 15:33:18","remoteAddr":"proxy","user":"admin","app":"onlyoffice","method":"PUT","url":"\\/index.php\\/apps\\/onlyoffice\\/ajax\\/settings","message":"SetStorageUrl: "}
{"reqId":"YZuxSGov2GqAhydJNAIY","level":1,"time":"June 27, 2018 15:33:18","remoteAddr":"proxy","user":"admin","app":"onlyoffice","method":"PUT","url":"\\/index.php\\/apps\\/onlyoffice\\/ajax\\/settings","message":"Set secret key"}
{"reqId":"YZuxSGov2GqAhydJNAIY","level":0,"time":"June 27, 2018 15:33:18","remoteAddr":"proxy","user":"admin","app":"onlyoffice","method":"PUT","url":"\\/index.php\\/apps\\/onlyoffice\\/ajax\\/settings","message":"CommandRequest on check: {\\"error\\":0,\\"version\\":\\"5.1.4.22\\"}"}
{"reqId":"K0eLtDwZvFzVMUvH0HIL","level":0,"time":"June 27, 2018 15:33:18","remoteAddr":"proxy","user":"--","app":"onlyoffice","method":"GET","url":"\\/index.php\\/apps\\/onlyoffice\\/empty?doc=SGloTVgxME1kVVlvZkJ0cGUxbkFZUmptZW15ZXAyN0pndG9kM2lzYnZkYz0\\/eyJhY3Rpb24iOiJlbXB0eSJ9","message":"Download empty"}
{"reqId":"K0eLtDwZvFzVMUvH0HIL","level":1,"time":"June 27, 2018 15:33:18","remoteAddr":"proxy","user":"--","app":"onlyoffice","method":"GET","url":"\\/index.php\\/apps\\/onlyoffice\\/empty?doc=SGloTVgxME1kVVlvZkJ0cGUxbkFZUmptZW15ZXAyN0pndG9kM2lzYnZkYz0\\/eyJhY3Rpb24iOiJlbXB0eSJ9","message":"Download empty with invalid jwt: Cannot handle token prior to 2018-06-27T15:33:21+0000"}
{"reqId":"SSS1g4xMbKIzFD7vKaQH","level":0,"time":"June 27, 2018 15:33:19","remoteAddr":"proxy","user":"--","app":"onlyoffice","method":"GET","url":"\\/index.php\\/apps\\/onlyoffice\\/empty?doc=SGloTVgxME1kVVlvZkJ0cGUxbkFZUmptZW15ZXAyN0pndG9kM2lzYnZkYz0\\/eyJhY3Rpb24iOiJlbXB0eSJ9","message":"Download empty"}
{"reqId":"SSS1g4xMbKIzFD7vKaQH","level":1,"time":"June 27, 2018 15:33:19","remoteAddr":"proxy","user":"--","app":"onlyoffice","method":"GET","url":"\\/index.php\\/apps\\/onlyoffice\\/empty?doc=SGloTVgxME1kVVlvZkJ0cGUxbkFZUmptZW15ZXAyN0pndG9kM2lzYnZkYz0\\/eyJhY3Rpb24iOiJlbXB0eSJ9","message":"Download empty with invalid jwt: Cannot handle token prior to 2018-06-27T15:33:22+0000"}
{"reqId":"6mpKDgdNfENfIHqPcWsM","level":0,"time":"June 27, 2018 15:33:21","remoteAddr":"proxy","user":"--","app":"onlyoffice","method":"GET","url":"\\/index.php\\/apps\\/onlyoffice\\/empty?doc=SGloTVgxME1kVVlvZkJ0cGUxbkFZUmptZW15ZXAyN0pndG9kM2lzYnZkYz0\\/eyJhY3Rpb24iOiJlbXB0eSJ9","message":"Download empty"}
{"reqId":"6mpKDgdNfENfIHqPcWsM","level":1,"time":"June 27, 2018 15:33:21","remoteAddr":"proxy","user":"--","app":"onlyoffice","method":"GET","url":"\\/index.php\\/apps\\/onlyoffice\\/empty?doc=SGloTVgxME1kVVlvZkJ0cGUxbkFZUmptZW15ZXAyN0pndG9kM2lzYnZkYz0\\/eyJhY3Rpb24iOiJlbXB0eSJ9","message":"Download empty with invalid jwt: Cannot handle token prior to 2018-06-27T15:33:23+0000"}

**Comment by pixel75** [comment]
Fixed. the issue was on ngnix proxy setup, now I can create, edit Docx, xls, pptx.
thank you @alexanderonlyoffice

**Comment by Login-out** [comment]
@pixel75  I have the same problem, how is your nginx setup

**Comment by pixel75** [comment]
@sta-zot I'm behind an HA proxy so not easy to show my conf.

HA issue the ssl and proxy to the OO in http.

which is your configuration?
