### ISSUE TITLE
OnlyOffice can't convert doc, xsl to docx, xslx

### ISSUE THREAD

**Issue by FuckToReal** [ONLYOFFICE/onlyoffice-owncloud#195]
Hi. My issue:
OnlyOffice can't save changes in doc|xsl|ppt files to NextCloud, because can't convert it to docx|xslx|pptx.
Logs:
/var/log/nextcloud/nextcloud.log

> {"reqId":"Wz7dmrgWJuB8krY7L82f@AAAAAQ","level":3,"time":"2018-07-06T03:10:20+00:00","remoteAddr":"172.17.0.2","user":"admin","app":"onlyoffice","method":"POST","url":"\/index.php\/apps\/onlyoffice\/track?doc=cW9sYVUvcFQreHZ4d3F6SVR1OE51R3dneE54Tk0zazZQKzZrWHhpYmZ4bz0\/eyJmaWxlSWQiOjIwMzIxLCJvd25lcklkIjoiYWRtaW4iLCJ0b2tlbiI6bnVsbCwiYWN0aW9uIjoidHJhY2sifQ%3D%3D","message":"GetConvertedUri on save error: Error occurred in the document service: Conversion error","userAgent":"--","version":"13.0.4.0"}

/var/log/onlyoffice/documentserver/docservice/out.log

>[ERROR] nodeJS - sendServerRequest error: docId = 20321_1515635330;url = https://cloud.barnaul.avantel.ru/index.php/apps/onlyoffice/track?doc=cW9sYVUvcFQreHZ4d3F6SVR1OE51R3dneE54Tk0zazZQKzZrWHhpYmZ4bz0/eyJmaWxlSWQiOjIwMzIxLCJvd25lcklkIjoiYWRtaW4iLCJ0b2tlbiI6bnVsbCwiYWN0aW9uIjoidHJhY2sifQ%3D%3D;data = {"key":"20321_1515635330","status":2,"url":"https://onlyoffice.barnaul.avantel.ru:32443/cache/files/20321_1515635330_8672/output.xlsx/output.xlsx?md5=Si7EkHnY3QAdbQ-20NHcAg==&expires=1530851091&disposition=attachment&ooname=output.xlsx","changesurl":"https://onlyoffice.barnaul.avantel.ru:32443/cache/files/20321_1515635330_8672/changes.zip/changes.zip?md5=q53uUBGiv5BTUS49eXytAA==&expires=1530851091&disposition=attachment&ooname=output.zip","history":{"serverVersion":"5.1.4","changes":[{"created":"2018-07-06 04:09:40","user":{"id":"admin","name":"admin"}}]},"users":["admin"],"actions":[{"type":0,"userid":"admin"}],"lastsave":"2018-07-06T04:09:40.732Z","notmodified":false}
Error: Error response: statusCode:500 ;body:
{"message":"Error occurred in the document service: Conversion error"}
    at Request._callback (/var/www/onlyoffice/documentserver/server/Common/sources/utils.js:283:18)
    at Request.self.callback (/var/www/onlyoffice/documentserver/server/Common/node_modules/request/request.js:185:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/var/www/onlyoffice/documentserver/server/Common/node_modules/request/request.js:1157:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/var/www/onlyoffice/documentserver/server/Common/node_modules/request/request.js:1079:12)
    at IncomingMessage.g (events.js:292:16)
    at emitNone (events.js:91:20)

/var/log/onlyoffice/documentserver/converter/err.log

> [ERROR] nodeJS - stdout (id=conv_4003041758_xls):
> [ERROR] nodeJS - stderr (id=conv_4003041758_xls):
> [ERROR] nodeJS - ExitCode (code=80;signal=null;error:-80;id=conv_4003041758_xls)

OnlyOffice runs in docker on the same server as NextCloud, both works through https with Let's Encrypt certs.

Can you help me? Thanks.

**Comment by flaminestone** [comment]
Hello @FuckToReal . Can you attach any file that is not converted? And specify version of nextcloud and documentserver, please

**Comment by FuckToReal** [comment]
[test.zip](https://github.com/ONLYOFFICE/onlyoffice-owncloud/files/2169387/test.zip)
I have updated to the latest available versions
nextcloud 13.0.4
documentserver 5.1.4

**Comment by flaminestone** [comment]
We need more informations about problem.
Can you enable saving files in documentserver before convertion?
Open file` /etc/onlyoffice/documentserver/default.json` in documentserver and find `"FileConverter"` part
```
"FileConverter": {
"converter": {
 "errorfiles": ""
```
Change value for errorfiles to any string(example: `"errorfiles": "folder_name"`) and restart documentserver
`supervisorctl restart all`
Then, need to trying convert doc(xls, or ppt) file from nextcloud again.
Folder with errors will be created in `/var/lib/onlyoffice/documentserver/App_Data/cache/files/folder_name`. Attach this folder, please

**Comment by FuckToReal** [comment]
Ok
[errorfiles.zip](https://github.com/ONLYOFFICE/onlyoffice-owncloud/files/2169730/errorfiles.zip)

**Comment by flaminestone** [comment]
@FuckToReal , Can you enable debug log level in nextcloud, trying to convert doc(xls, or ppt) file from nextcloud again, and attach new logs from nextcloud?
Instruction for log enabling: 
https://docs.nextcloud.com/server/13/admin_manual/configuration_server/logging_configuration.html
Need to set `loglevel = 0`

**Comment by FuckToReal** [comment]
[nextcloud.log](https://github.com/ONLYOFFICE/onlyoffice-owncloud/files/2170434/nextcloud.log)

**Comment by flaminestone** [comment]
@FuckToReal ,  What type(format) of file you trying to open?

**Comment by FuckToReal** [comment]
Doc or xls. And it's all right about opening but saving doesn't work.

**Comment by flaminestone** [comment]
@FuckToReal ,Are you make changes to onlyoffice are nextcloud initial code? And if do - what the changes? Can you record video(gif) with opening doc file?

**Comment by FuckToReal** [comment]
No, there's no changes.
I just clicking file with left mouse button, make some changes and press ctrl+S (or "Save" button). Changes saving in onlyoffice cache but not in nextcloud.

**Comment by flaminestone** [comment]
@FuckToReal There are no ability to open doc, xls are ppt file in ONLYOFFICE. You can only download it or convert to ooxml format(docx, xlsx, pptx), and then open file.
And I don't know, how you did opened doc file.
Please, attach video with opening, or gif file

**Comment by FuckToReal** [comment]
Oh, you are right. I deleted "conv => true" for doc, xsl and ppt in apps/onlyoffice/lib/appconfig.php. But I thought it is same as press "No"  in dialog "Convert and open document". Am I mistake?

**Comment by flaminestone** [comment]
@FuckToReal Yes)), you can not edшt doc, xls or ppt files by onlyoffice. You have to convert it to ooxml format

**Comment by FuckToReal** [comment]
But what happens, when I press "No" in "Convert and open document" dialog? Because editor opens and saves document, but only in cache.

**Comment by flaminestone** [comment]
@FuckToReal , If you press "No", onlyoffice document viewer opens by default.

**Comment by FuckToReal** [comment]
No, editor opens. And I can edit and save file.
![screencast](https://user-images.githubusercontent.com/8565396/42389263-4fa8cc6c-8172-11e8-839d-99c5bded56e2.gif)

**Comment by FuckToReal** [comment]
Sorry, I compare my apps/onlyoffice/lib/appconfig.php and github version. I also added "edit" => true for doc, xls and ppt.

**Comment by flaminestone** [comment]
@FuckToReal , File will be converted if documentserver needed it. And nextcloud config describes cases for saving. 
You marked "doc" file like "can be edited and saved to doc" in your changes. Documentserver tried to save to "doc", but it is not possible.  Do not change configs for correct work of documentserver

**Comment by bseclier** [comment]
Hi,
I'll add some details and a warning : it is possible to open doc, xls or ppt files from nextcloud to onlyoffice by modifying the appconfig file (forcing edit => true). 

Problem is : you will be able to modify the file but it'll stay in onlyoffice cache and never sent back to nextcloud (without any error). So after a reboot of onlyoffice (database or redis, idk), all changes will be lost forever. It happened here, we lost 2 months of works for doc, xls and ppt files...
I hope this message will avoid problems :)
Cheers,

**Comment by ibnpetr** [comment]
@bseclier We also hope that this message will avoid problems.

> it is possible to open doc, xls or ppt files from nextcloud to onlyoffice by **modifying the appconfig file (forcing edit => true).**

As @flaminestone said, do not force DocumentServer to work with doc files as if they were docx.
The preferred way is to convert them to docx.

**Comment by xinyuwang** [comment]
> Hi,
> I'll add some details and a warning : it is possible to open doc, xls or ppt files from nextcloud to onlyoffice by modifying the appconfig file (forcing edit => true).
> Problem is : you will be able to modify the file but it'll stay in onlyoffice cache and never sent back to nextcloud (without any error). So after a reboot of onlyoffice (database or redis, idk), all changes will be lost forever. It happened here, we have lost 2 months of works for doc, xls and ppt files...
> 
> I hope this message will avoid problems :)
> Cheers,

Thanks a lot for your kind reminder! That's really a big problem.
