### ISSUE TITLE
[FEATURE REQUEST] Add doc/xls/ppt file formats to open automatically in Nextcloud

### ISSUE THREAD

**Issue by djermann** [ONLYOFFICE/onlyoffice-owncloud#196]
It would be helpful to have also the older MS-Office file formats to be opened automatically in OwnCloud/Nextcloud. The current solution does not provide a good workflow.

**Comment by LinneyS** [comment]
#179

**Comment by djermann** [comment]
I am aware of this feature request that covers OpenDocument formats. However, this feature request is only about the support for the older MS-Office file formats (doc/xls/ppt). As ONLYOFFICE is supporting MS-Office file formats, it should also be compatible with doc/xlx/ppt file formats.

**Comment by alexanderonlyoffice** [comment]
Hello @djermann, unfortunately, we are planning to work with old formats the same as we are working with the current ones. Even if we add possibility to open them for review, it will be impossible to save them.

**Comment by LinneyS** [comment]
[Please note](https://api.onlyoffice.com/editors/owncloud#editable)
