### ISSUE TITLE
502 Proxy Error on Documentserver

### ISSUE THREAD

**Issue by Rick26L** [ONLYOFFICE/onlyoffice-owncloud#197]
### Steps to reproduce
1. Have Onlyoffice installed as Docker on your NC
1. Try to Access the url of your document server
2. Try to connect nextcloud app to onlyoffice

### Expected behaviour
App should connect or you could see that the document server is up and running

### Actual behaviour
App Error Bad Request or Timeout 
Nextcloud Log: 
Info | onlyoffice | Set opening in a same tab: false | 2018-07-12T15:12:07+0200
-- | -- | -- | --
Info | onlyoffice | Set default formats: {"docx":"true","xlsx":"true","pptx":"true","ppsx":"true","txt":"false","csv":"true"} | 2018-07-12T15:12:07+0200
Error | onlyoffice | CommandRequest on check error: Bad Request oder Timeout Fehlermeldung | 2018-07-12T15:12:07+0200
Error | PHP | file_get_contents(https://office.*********.de/coauthoring/CommandService.ashx): failed to open stream: HTTP request failed! HTTP/1.1 502 Proxy Error  at /var/www/nextcloud/apps/onlyoffice/lib/documentservice.php#351 | 2018-07-12T15:12:07+0200
Info | onlyoffice | Clear secret key | 2018-07-12T15:12:07+0200
Info | onlyoffice | SetStorageUrl: | 2018-07-12T15:12:07+0200
Info | onlyoffice | SetDocumentServerInternalUrl: | 2018-07-12T15:12:07+0200
Info | onlyoffice | SetDocumentServerUrl: https://office.**********.de/

Website Error: 
502 Proxy Error 
Proxy Error
The proxy server received an invalid response from an upstream server.
The proxy server could not handle the request GET /.

Reason: Error reading from remote server

Apache/2.4.18 (Ubuntu) Server at office.***********.de Port 443

## Server configuration detail

**Operating system:** Linux 4.4.0-116-generic #140-Ubuntu SMP Mon Feb 12 21:23:04 UTC 2018 x86_64

**Webserver:** Apache/2.4.18 (Ubuntu) (apache2handler)

**Database:** mysql 10.2.13

**PHP version:** 7.0.28-0ubuntu0.16.04.1
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, apache2handler, redis, mysqlnd, PDO, xml, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, imagick, imap, intl, json, ldap, exif, mcrypt, mysqli, pdo_mysql, pdo_pgsql, pdo_sqlite, pgsql, Phar, posix, readline, shmop, SimpleXML, smbclient, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, libsmbclient, Zend OPcache

**Nextcloud version:** 13.0.2 - 13.0.2.1

**Where did you install Nextcloud from: Tech and Me 

<details><summary>Signing status</summary>

Array
</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - activity: 2.6.1
 - admin_audit: 1.3.0
 - bruteforcesettings: 1.0.3
 - caniupdate: 0.1.2
 - comments: 1.3.0
 - dav: 1.4.6
 - federatedfilesharing: 1.3.1
 - federation: 1.3.0
 - files: 1.8.0
 - files_external: 1.4.1
 - files_fulltextsearch: 0.7.0
 - files_pdfviewer: 1.2.1
 - files_rightclick: 0.8.4
 - files_sharing: 1.5.0
 - files_texteditor: 2.5.1
 - files_trashbin: 1.3.0
 - files_versions: 1.6.0
 - firstrunwizard: 2.2.1
 - fulltextsearch: 0.7.1
 - fulltextsearch_elasticsearch: 0.7.0
 - impersonate: 1.0.4
 - issuetemplate: 0.3.0
 - logreader: 2.0.0
 - lookup_server_connector: 1.1.0
 - nextcloud_announcements: 1.2.0
 - notifications: 2.1.2
 - oauth2: 1.1.0
 - onlyoffice: 1.3.0
 - password_policy: 1.3.0
 - previewgenerator: 1.0.9
 - provisioning_api: 1.3.0
 - serverinfo: 1.3.0
 - sharebymail: 1.3.0
 - survey_client: 1.1.0
 - systemtags: 1.3.0
 - theming: 1.4.1
 - twofactor_backupcodes: 1.2.3
 - updatenotification: 1.3.0
 - user_ldap: 1.3.1
 - workflowengine: 1.3.0
Disabled:
 - calendar
 - contacts
 - encryption
 - files_videoplayer
 - gallery
 - passman
 - user_external

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "localhost",
        "192.168.202.2",
        "cloud.**********.de",
        "office.**********.de"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "https:\/\/cloud.**********.de\/",
    "dbtype": "mysql",
    "version": "13.0.2.1",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "maintenance": false,
    "mail_smtpmode": "smtp",
    "log_rotate_size": "10485760",
    "memcache.local": "\\OC\\Memcache\\Redis",
    "filelocking.enabled": true,
    "memcache.distributed": "\\OC\\Memcache\\Redis",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 0,
        "timeout": 0,
        "dbindex": 0,
        "password": "***REMOVED SENSITIVE VALUE***"
    },
    "htaccess.RewriteBase": "\/",
    "loglevel": "0",
    "log_type": "file",
    "logfile": "\/var\/ncdata\/nextcloud.log",
    "logtimezone": "Europe\/Berlin",
    "ldapIgnoreNamingRules": false,
    "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
    "theme": "",
    "data-fingerprint": "60a3bf463e787295b6bfaefe50b04866",
    "updater.release.channel": "production"
}
```
</details>

**Are you using external storage, if yes which one:** local/smb

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory

</details>

**Comment by alexanderonlyoffice** [comment]
Hello @Rick26L, please specify some additional information about the issue: 

1. Is the Document Server installed on the same server where NC or on different servers;
2. Do you see Document Server Welcome page when entering Document Server address in address tab of the browser?;
3. Send us a screenshot of the address settings of ONLYOFFICE application from your NC;
4. Try to check the accessibility of NC from inside of docker container with the Document Server (`wget https://nextcloud_address`). Then, if they are installed on different machines, from the server where Document Server is installed (`wget https://nextcloud_address`). Check also the accessibility of the Document Server from the server where NC is installed (`wget https://documentserver_address`).

**Comment by Rick26L** [comment]
Hey @alexanderonlyoffice , 
1. The Document Server is installed on the same server as a docker container. 
2. I didn't see the Welcome Page. I get "502 Proxy Error" 
----Proxy Error
----The proxy server received an invalid response from an upstream server.
----The proxy server could not handle the request GET /.
----Reason: Error reading from remote server
----Apache/2.4.18 (Ubuntu) Server at office.*********.de Port 443
3. 
- Document Editing Service address: https://office.********.de/
- Document Editing Service address for internal requests from the server: Blank (https://<documentserver>/)
- Server address for internal requests from the Document Editing Service: Blank (https://cloud.********.de)
- Secret: Blank
4. 
Docker DS to NC: Ok 
Docker DS to Docker DS: 502: Proxy Error 
NC to NC: Ok 
NC to Docker DS: 502: Proxy Error 

502 Proxy Error: 
--2018-07-13 08:34:44--  https://office.***********.de/
Resolving office.***********.de (office.***********.de)... 192.168.202.2
Connecting to office.***********.de (office.***********.de)|192.168.202.2|:443... connected.
HTTP request sent, awaiting response... 502 Proxy Error
2018-07-13 08:34:44 ERROR 502: Proxy Error.

**Comment by nvgoldendog** [comment]
I am getting the same error and my setup is very similar. Using distro from Techandme.

**Comment by Rick26L** [comment]
Hi @alexanderonlyoffice , 

do you have any other ideas? 

Thanks in advance!

**Comment by alexanderonlyoffice** [comment]
Hi @Rick26L, I can see on the screenshot that address of the Document Editing Service for internal requests in the advanced server settings is blank. 
![502 proxy error on documentserver issue 197 onlyoffice_onlyoffice-owncloud - mozilla firefox 2018-08-06 11 12 31](https://user-images.githubusercontent.com/30896337/43705071-435fb262-996a-11e8-943f-45283d7728c8.png)

Please try to add the address of the Document Server in this field, because when you use advanced server settings, only these settings are being used and it is not enough to specify just the Document Editing Service address.

**Comment by alexanderonlyoffice** [comment]
Hello @nvgoldendog, please describe the issue in more details, send also a screenshot of the Document Server address settings.

**Comment by Rick26L** [comment]
Hi @alexanderonlyoffice , 
i have some NC with Onlyoffice running without using the advanced settings. There is nothing entered. It is blank. Should I try to enter the name or the internal ip adress

**Comment by Rick26L** [comment]
Hi, 
i have updated the nextcloud to 13.0.4, deleted the onlyoffice app, installed a new docker container, reinstalled the onlyoffice app.... and now its working. 

Thanks for your help!
