### ISSUE TITLE
No secret key - Bad request / Timeout when saving settings in Nextcloud

### ISSUE THREAD

**Issue by waazdakka** [ONLYOFFICE/onlyoffice-owncloud#207]
Hello !

I just activated my Nextcloud's OnlyOffice extension to test it in real situation but... 
First of all, I can't find how to generate the secret key and what I have to set into the differents fields.

The other issue is a "bad request or timeout" error when saving settings on my Nextcloud :(

I'm on Nextcloud 13.0.2 self hosted, and trying to connect the https://crfparis13.onlyoffice.eu/ Only Office instance.

Thanks for your help !

<img width="540" alt="capture d ecran 2018-08-06 a 14 48 54" src="https://user-images.githubusercontent.com/9380081/43717491-0c0146f0-9988-11e8-9b8a-8ef75bdd026b.png">

**Comment by ibnpetr** [comment]
@waazdakka 
> trying to connect the https://crfparis13.onlyoffice.eu/ Only Office instance.

crfparis13.onlyoffice.eu is your [ONLYOFFICE cloud](https://www.onlyoffice.com/cloud-office.aspx) portal address. It cannot be connected to your Nextcloud.
Please install your own local instance of [Document Server](https://www.onlyoffice.com/connectors.aspx) and use it for editing documents within NC.
