### ISSUE TITLE
Onlyoffice Document Server not working with two NC

### ISSUE THREAD

**Issue by Floflobel** [ONLYOFFICE/onlyoffice-owncloud#208]
**Do you want to request a *feature* or report a *bug*?**
Bug reported https://github.com/ONLYOFFICE/DocumentServer/issues/256

**What is the current behavior?**
I can't connect two Nextcloud to my Onlyoffice Document Server

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
- Install two Nextcloud with package
- Add the application Onlyoffice
- Configure the onlyoffice key into the settings
- Check on two onlyoffice if the welcome page is accessible (OK)
- The last server is configured, can't access to onlyoffice when try to edit a file 

![image](https://user-images.githubusercontent.com/13889750/43718282-756fe860-998a-11e8-8c27-0961e680e0eb.png)

**Did this work in previous versions of DocumentServer?**
it worked well in an old version (I do not know which one exactly)

**DocumentServer version:**
onlyoffice-documentserver 5.1.5-59

**Nextcloud version:**
13.0.5

**Operating System:**
Ubuntu 16.04.4 LTS

**Browser version:**
Tested with chrome firefox and internet explorer

**Comment by alexanderonlyoffice** [comment]
Hello @Floflobel, in the previous opened issue you specified Document Server version 5.1.2-9. Please confirm that you have now a newer version 5.1.5-59. 

As we understood, everything is working fine on one of the instances. Please send us screenshot of ONLYOFFICE integration app address settings from both NC instances, so we can compare the settings. 

Click on the 'Save' button on the page with address settings in NC instance where integration is not working and send us a screenshot, so we can see the caption that the settings are successfully saved or there is an error.

**Comment by Floflobel** [comment]
Hello @alexanderonlyoffice,

Actually I have the latest version 5.1.5-59.

I can not send screenshots because I want to keep this information confidential. The fields are exactly the same on both nextcloud, nothing changes.

I filled in the "Document Editing Service address" with the address of onlyoffice and "Secret key (leave blank to disable)" with the key that is the same on both. I did not fill the other fields.

When I click the save button no error appears on either nextcloud.

**Comment by alexanderonlyoffice** [comment]
Hello @Floflobel, have you tried to add the following section to the NC instance where you have problems: 
```
'onlyoffice' =>
  array (
    "jwt_secret" => "secret",
    "jwt_header" => "header"
	) 
```

> When I click the save button no error appears on either nextcloud.

If I understand it right, you have caption that the settings has been successfully updated, like on the screenshot below? 
![settings - nextcloud - mozilla firefox 2018-08-08 08 37 22](https://user-images.githubusercontent.com/30896337/43818275-8b4a5f64-9ae6-11e8-91fc-29877364f444.png)

**Comment by alexanderonlyoffice** [comment]
Hello @Floflobel, could you please send us all logs of Nextcloud and Document Server to support@onlyoffice.com with a note for technical support.

**Comment by LinneyS** [comment]
This issue was closed due to no response.
