### ISSUE TITLE
SSL Error while connecting to documentserver

### ISSUE THREAD

**Issue by kwmkjf** [ONLYOFFICE/onlyoffice-owncloud#209]
Hi guys,

I want to connect my Nextcloud Server to the Documentserver. I have two different servers for nextcloud and onlyoffice. When I try to connect to the server it syays

```
Error | onlyoffice | CommandRequest on check error: Bad Request oder Timeout Fehlermeldung | 2018-08-07T15:44:16+0200
Error | PHP | file_get_contents(https://onlyoffice.domain.net/coauthoring/CommandService.ashx):  failed to open stream: operation failed at  /var/www/html/apps/onlyoffice/lib/documentservice.php#351 | 2018-08-07T15:44:16+0200
Error | PHP | file_get_contents(): Failed to enable crypto at /var/www/html/apps/onlyoffice/lib/documentservice.php#351 | 2018-08-07T15:44:16+0200
Error | PHP | file_get_contents():  SSL operation failed with code 1. OpenSSL Error messages: error:14090086:SSL routines:ssl3_get_server_certificate:certificate  verify failed at  /var/www/html/apps/onlyoffice/lib/documentservice.php#351

```

I'm using a wildcard certificate for my domain which works in firefox and all other browsers too. The Nextcloud uses an apache2, onlyoffice is configured with nginx.

**Comment by ibnpetr** [comment]
Hello
Please try adding the certificate to ca-bundle of the server with NC (preferred way)
If that is not possible try [this](https://github.com/ONLYOFFICE/onlyoffice-owncloud/issues/180) solution, i.e. add
```
'onlyoffice' =>
array (
'verify_peer_off' => true,
),
```

to /var/www/nextcloud/config.php

**Comment by kwmkjf** [comment]
Works with the config.php parameters.
