### ISSUE TITLE
"Unknown Error."

### ISSUE THREAD

**Issue by Schroedingers-Cat** [ONLYOFFICE/onlyoffice-owncloud#21]
I've installed OnlyOffice from the official repository on Ubuntu 16.04 and have it running via nginx on port 81 in a VM. I also have the latest Nextcloud 11 with the latest OnlyOffice-App.

The link between the app and the OnlyOffice-Server seems to work as I can create spreadsheets, word files and presentation files via Nextclouds File-App. I can also open the OnlyOffice app by clicking on one of these files which opens a new browser tab the the OnlyOffice UI. However, it brings up the error message "Unknown Error.". Is this a known issue? What can I do to track down the problem?

**Comment by JohnPerkin** [comment]
Hello!
Current version of Document Server supports listening only to 80 port. Running on custom port will be implemented in 4.3 release. You may monitor it in our [Change log](https://github.com/ONLYOFFICE/DocumentServer/blob/master/CHANGELOG.md).
Best regards
John
ONLYOFFICE support team
