### ISSUE TITLE
File permissions on load from ownCloud

### ISSUE THREAD

**Issue by tomneedham** [ONLYOFFICE/onlyoffice-owncloud#210]
Hi,

I wanted to check in with you about how a file is loaded from ownCloud, and what permissions are retrieved. I notice here is the controller where you load the file: https://github.com/ONLYOFFICE/onlyoffice-owncloud/blob/master/controller/editorcontroller.php#L490 and you are loading the file directly fro the root view. What is the current user authenticated during this process? The permissions of the returned file depend on the session, and how the FS is setup. For example, if it is some 'admin' user, they may have overall permissions, but not some specific user-share permissions granted to the receiving user. 

I would recommend using `IRootFolder->getUserFolder($userId)->getById()` to clearly get the file from a users folder. Additionally, it is sensible to do a `\OC_Util::setupFS($userId)` to make sure the FS is setup for the correct perspective of the editing user.

Thanks,
Tom

**Comment by cdamken** [comment]
Any news here?

**Comment by tomneedham** [comment]
I did some further analysis - you shouldn't need this actually, the getUserFolder should setup the necessary user mounts to make it resolve correctly.

**Comment by LinneyS** [comment]
[getFile in callbackcontroller](https://github.com/ONLYOFFICE/onlyoffice-owncloud/blob/v2.0.1/controller/callbackcontroller.php#L436) is used by the request handler from the editing service. Here the `getUserFolder` function is used.

[getFile in editorcontroller](https://github.com/ONLYOFFICE/onlyoffice-owncloud/blob/v2.0.1/controller/editorcontroller.php#L510) is used in the ajax-request from the page of only authorized user  to collect the configuration of the editing page.  `getUserFolder` function added.

**Comment by tomneedham** [comment]
Awesome! For reference, here is what happens when you call `getUserFolder` https://github.com/owncloud/core/blob/5f0af496626b957aff38730b5771ec0a33effe31/lib/private/Files/Node/Root.php#L345 its the initMountPoints which helps here as it loads in the shares with the right permissions.
