### ISSUE TITLE
problem with ssl certificate

### ISSUE THREAD

**Issue by kozliatko** [ONLYOFFICE/onlyoffice-owncloud#218]
Hello

I have a problem with integration app from apps store. My OnlyOffice server ssl certificate is signed by "snake oil" CA. When I want to connect from nextcloud to onlyoffice I get timeout message.
Solution was in [documentservice.php:372](https://github.com/ONLYOFFICE/onlyoffice-owncloud/blob/master/lib/documentservice.php#L372) comment out ```&& $this->config->TurnOffVerification()```. And main question is where I can set this config verification option?

The function is defined in [appconfig.php:434](https://github.com/ONLYOFFICE/onlyoffice-owncloud/blob/master/lib/appconfig.php#L434) but I cannot find GUI part for set this option.

I think this is probably PEBKAC, but I need some hint :(

Thank you

**Comment by alexanderonlyoffice** [comment]
Hello @kozliatko, open the config file /nextcloud/config/config.php and add a section below:

```
'onlyoffice' =>
  array (
    'verify_peer_off' => TRUE,
  )
```

**Comment by alexanderonlyoffice** [comment]
@kozliatko, please specify if the mentioned above solution helped you.
