### ISSUE TITLE
Next Cloud & OO problem

### ISSUE THREAD

**Issue by smiralles** [ONLYOFFICE/onlyoffice-owncloud#219]
hello world, 
I am stumped at the moment and for the life of me i can't figure this out! i keep getting this: HealthcheckRequest on check error: Bad Request or timeout error

attached are some screenshots. Please point me in the right direction. 

![ncoo1](https://user-images.githubusercontent.com/12898430/45554723-07341080-b805-11e8-8d91-a6f255dcd897.PNG)
![ncoo2](https://user-images.githubusercontent.com/12898430/45554737-0ef3b500-b805-11e8-88a3-148abcd740b7.PNG)

**Comment by soundzgoood** [comment]
Hi smiralles,
I keep getting a similar error. I tried to setup nextcloud and onlyoffice behind a jwilder nginx-proxy.
When I get into the nextcloud container, I am not able to reach the office.domain.tld/helthcheck via wget.

But if I use the internal IP of the container I can get the healthcheck. 

So I added the internal IP of the onlyoffice container in the app settings of nextcloud. But now I am getting an error like:

GetConvertedUri on check error: Im Dokumentenservice ist ein Fehler aufgetreten: Error while downloading the document file to be converted.

I read about problems with ssl certificates... But also from here I have no clue what to do next. 

It seems to me, that the docker container is not able to make a loopback to the office.domain.tld

Would be happy for some help tooo!

**Comment by berlevdv** [comment]
I get the same error.

owncloud.log:
```
{"reqId":"S8GD9R5uFdjWQKHAdEHi","level":3,"time":"2018-09-17T12:20:13+00:00","remoteAddr":"172.16.50.100","user":"admin","app":"PHP","method":"PUT","url":"\/index.php\/apps\/onlyoffice\/ajax\/settings","message":"file_get_contents(http:\
/\/172.16.50.102\/healthcheck): failed to open stream: HTTP request failed! HTTP\/1.1 502 Bad Gateway\r\n at \/var\/www\/owncloud\/apps\/onlyoffice\/lib\/documentservice.php#381"}
{"reqId":"S8GD9R5uFdjWQKHAdEHi","level":3,"time":"2018-09-17T12:20:13+00:00","remoteAddr":"172.16.50.100","user":"admin","app":"onlyoffice","method":"PUT","url":"\/index.php\/apps\/onlyoffice\/ajax\/settings","message":"HealthcheckReques
t on check error: \u041e\u0448\u0438\u0431\u043a\u0430 \u0437\u0430\u043f\u0440\u043e\u0441\u0430 \u0438\u043b\u0438 \u0442\u0430\u0439\u043c\u0430\u0443\u0442"}
```

If open http:\\172.16.50.102\healthcheck in browser we will get "502 Bad Gateway" from nginx.
It does not matter from what address we go to this page, or using https or FQDN.

If check Onlyoffice nginx configuration, we found this secion in nginx/includes/onlyoffice-communityserver-services.conf

```
location /healthcheck {
        rewrite /healthcheck(.*) /$1  break;
        proxy_pass http://localhost:9810;
        proxy_redirect ~*/(.*) /healthcheck/$1;
         client_max_body_size 100m;
         proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
         proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Host $server_name;
        proxy_set_header X-Forwarded-Proto $scheme;
}
```

But there is no process listen port 9810 on Onlyoffice server.

**Comment by alexanderonlyoffice** [comment]
@smiralles, please specify the installation type of the Document Server and if it is installed on the same server with Nextcloud or on a different one. 

Please try to use wget command to check the accessibility of the Document Server for Nextcloud and vice versa.  

Please try also to disable verification of the SSL certificate by the Document Server. Open /etc/onlyoffice/documentserver/default.json and find the line below and changed its value to false: 

` "rejectUnauthorized": true`

@soundzgoood, the error below means that the Document Server cannot download the file (Nextcloud is inaccessible for the Document Server) 

> Error while downloading the document file to be converted.

Please try to add the internal IP of the container with Nextcloud in the second address field in advanced server settings. 

@berlevdv, please specify which exact product you are using. As we can see that you are looking at the Community Server config. 

Send us also a screenshot of the address settings of ONLYOFFICE integration app in ownCloud. 

Try also to disable verification of the SSL certificates in ownCloud config.php by adding the following section to it: 

```
 'onlyoffice' =>
  array (
    'verify_peer_off' => TRUE,
  )
```

**Comment by alexanderonlyoffice** [comment]
@soundzgoood, we are glad you found a solution. Yes, please notify us about the result.

**Comment by LinneyS** [comment]
@smiralles 
Could you please specify if the problem recurs or we can close the topic?

**Comment by soundzgoood** [comment]
Yes you can close the issue!
In order to prevent that after restarting the docker images the ip is changing and messing up your settings you should use an internal domain for your nextcloud and for your onlyoffice containers in your local network:

nextcloud_app:
...
networks:
      intern:
        aliases:
          - nextcloud.local
      extern:

Also don't forget to add the domain of nextcloud.local in your config.php of nextcloud as trusted domain.
