### ISSUE TITLE
Support custom ports

### ISSUE THREAD

**Issue by oparoz** [ONLYOFFICE/onlyoffice-owncloud#22]
When adding a server with a custom port in the settings, OnlyOffice simply ignores it and makes a request to a non-existent server.

It would be great if you could fix this and not filter out the port entered in the settings.

**Comment by oparoz** [comment]
Will only work with the next update of the DocumentServer, due to be release in April 2017.
Keeping this opened until it's confirmed as fixed.

**Comment by JohnPerkin** [comment]
Document Server 4.3 is realesed. You may see its [ChangeLog](https://github.com/ONLYOFFICE/DocumentServer/releases/tag/ONLYOFFICE-DocumentServer-4.3.0)
