### ISSUE TITLE
ONLYOFFICE cannot be reached. Please contact admin ERR

### ISSUE THREAD

**Issue by asoliman** [ONLYOFFICE/onlyoffice-owncloud#225]
I am using ownCloud 9.1 on freenas. I am using OnlyOffice Document server running on Debian Jessie.
Here's my NGINX configuration:
```root@onlyoffice:~# nginx -V
nginx version: nginx/1.6.2
TLS SNI support enabled
configure arguments: --with-cc-opt='-g -O2 -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2' --with-ld-opt=-Wl,-z,relro --prefix=/usr/share/nginx --conf-path=/etc/nginx/nginx.conf --http-log-path=/var/log/nginx/access.log --error-log-path=/var/log/nginx/error.log --lock-path=/var/lock/nginx.lock --pid-path=/run/nginx.pid --http-client-body-temp-path=/var/lib/nginx/body --http-fastcgi-temp-path=/var/lib/nginx/fastcgi --http-proxy-temp-path=/var/lib/nginx/proxy --http-scgi-temp-path=/var/lib/nginx/scgi --http-uwsgi-temp-path=/var/lib/nginx/uwsgi --with-debug --with-pcre-jit --with-ipv6 --with-http_ssl_module --with-http_stub_status_module --with-http_realip_module --with-http_auth_request_module --with-http_addition_module --with-http_dav_module --with-http_flv_module --with-http_geoip_module --with-http_gzip_static_module --with-http_image_filter_module --with-http_mp4_module --with-http_perl_module --with-http_random_index_module --with-http_secure_link_module --with-http_spdy_module --with-http_sub_module --with-http_xslt_module --with-mail --with-mail_ssl_module --add-module=/build/nginx-1.6.2/debian/modules/headers-more-nginx-module --add-module=/build/nginx-1.6.2/debian/modules/nginx-auth-pam --add-module=/build/nginx-1.6.2/debian/modules/nginx-cache-purge --add-module=/build/nginx-1.6.2/debian/modules/nginx-dav-ext-module --add-module=/build/nginx-1.6.2/debian/modules/nginx-development-kit --add-module=/build/nginx-1.6.2/debian/modules/nginx-echo --add-module=/build/nginx-1.6.2/debian/modules/ngx-fancyindex --add-module=/build/nginx-1.6.2/debian/modules/nginx-http-push --add-module=/build/nginx-1.6.2/debian/modules/nginx-lua --add-module=/build/nginx-1.6.2/debian/modules/nginx-upload-progress --add-module=/build/nginx-1.6.2/debian/modules/nginx-upstream-fair --add-module=/build/nginx-1.6.2/debian/modules/ngx_http_substitutions_filter_module
```

This error is happening on both HTTP and HTTPS.

**Comment by asoliman74** [comment]
Here's the error I am getting on owncloud

![image](https://user-images.githubusercontent.com/13020927/47323702-c0aab080-d611-11e8-9548-b36e4e5f46e6.png)

**Comment by asoliman74** [comment]
The screenshots below shows document server running on both http and https
![image](https://user-images.githubusercontent.com/13020927/47323755-f354a900-d611-11e8-9d92-5e3947bb3330.png)
![image](https://user-images.githubusercontent.com/13020927/47323765-010a2e80-d612-11e8-821c-4682d99d98a6.png)

**Comment by asoliman74** [comment]
Here's the content of my /etc/nginx/conf.d/onlyoffice-documentserver.conf file


`include /etc/nginx/includes/onlyoffice-http.conf;
## Normal HTTP host
server {
listen 0.0.0.0:80;
listen [::]:80;
server_tokens off;
include /etc/nginx/includes/onlyoffice-documentserver-*.conf;
}

## HTTPS host
server {
listen 0.0.0.0:443 ssl;
listen [::]:443 ssl default_server;
server_tokens off;
include /etc/nginx/includes/onlyoffice-documentserver-*.conf;

ssl on;
ssl_certificate /etc/nginx/ssl/self.crt;
ssl_certificate_key /etc/nginx/ssl/self.key;

ssl_prefer_server_ciphers on;
}
`

**Comment by LinneyS** [comment]
> Here's the error I am getting on owncloud

What message is shown in the browser console?

**Comment by LinneyS** [comment]
This issue was closed due to no response.
