### ISSUE TITLE
The "Convert with ONLYOFFICE" action is also required for publicshare (.doc, .xls, .ppt)

### ISSUE THREAD

**Issue by pomu0326** [ONLYOFFICE/onlyoffice-owncloud#227]
With logged in ownCloud, the "Convert with ONLYOFFICE" menu will be displayed.

![image](https://user-images.githubusercontent.com/8056227/47882976-ae7d0d80-de6e-11e8-9fc0-6f08396292f5.png)

When I publishhare a folder with "Read & Write" and access the URL, "Convert with ONLYOFFICE" menu will not be displayed.

![image](https://user-images.githubusercontent.com/8056227/47883158-5db9e480-de6f-11e8-9620-0d743b00b419.png)

I expect that it will function similarly in publicshare.
 
Thanks.

**Comment by alexanderonlyoffice** [comment]
@pomu0326, thank you for the provided information. We will take it into consideration.
