### ISSUE TITLE
[Feature request] Share link view/edit

### ISSUE THREAD

**Issue by Stibila** [ONLYOFFICE/onlyoffice-owncloud#23]
When I share link with people outside Nextcloud, they can only download the file. It would be great to allow them to see and edit file with ONLYOFFICE. Something like this https://nextcloud.com/blog/nextcloud-introduces-anonymous-editing-with-collabora-online/

**Comment by JohnPerkin** [comment]
https://github.com/ONLYOFFICE/onlyoffice-owncloud/issues/20#issuecomment-287050633
