### ISSUE TITLE
Nextcloud to OnlyOffice - larger than 100MB word document - Download failed

### ISSUE THREAD

**Issue by jaschrock** [ONLYOFFICE/onlyoffice-owncloud#237]
I am running Nextcloud 13.0.8 integrated with OnlyOffice (on a separate server). The integration is working fine, overall. However, if I try to open a document that is larger than 100MB it shows a download failed. 96MB is fine. I read somewhere a hint this might be a limitation with onlyoffice or the integration. Is this a hard limit or something that can be configured in OnlyOffice and/or NextCloud? I already tweaked the php on Nextcloud to get larger files uploaded. 

Thanks
Alan

**Comment by jaschrock** [comment]
OK, I found in the out.log for the converter the following: 
  at Request.onSizeError (/var/www/onlyoffice/documentserver/server/Common/sources/utils.js:235:19)
    at Request.<anonymous> (/var/www/onlyoffice/documentserver/server/Common/sources/utils.js:256:21)

when  looking at that code, there is a variable optLimit that is being used. Is there a place I can set this value?

**Comment by jaschrock** [comment]
Found the answer. Two values can affect this in /etc/onlyoffice/documentserver/default.json
in the "FileConverter": "converter" section
maxDownloadBytes
downloadTimeout

If you increase either of these it will increase the maximum filesize.  the downloadTimeout is multiplied by 1000 to determine the maximum size. the maxDownloadBytes is a raw number and these are checked and if one is favorable it continues.

**Comment by LinneyS** [comment]
#127
