### ISSUE TITLE
Can't configure "Restrict access to editors to following groups"

### ISSUE THREAD

**Issue by va1entin** [ONLYOFFICE/onlyoffice-owncloud#239]
When I tick the checkbox "Restrict access to editors to following groups" I'm unable to actually specify any group. I don't see any text field or drop down to choose a group. I have this problem in Firefox and Chrome. Also, when I tick the checkbox, click "Save" and reload the page, the checkbox is unticked again.
If I'm not mistaken this feature was introduced just recently. Could it be that it's not intended to work at the moment? If so, feel free to close this issue.
![image](https://user-images.githubusercontent.com/31535155/50230962-fe2b8000-03ad-11e9-9a9e-74ec2f061799.png)

**Comment by LinneyS** [comment]
There are messages in the browser console?

**Comment by LinneyS** [comment]
This issue was closed due to no response.
