### ISSUE TITLE
Error while downloading the document file to be converted

### ISSUE THREAD

**Issue by fgarpe** [ONLYOFFICE/onlyoffice-owncloud#241]
Hi,
This is my scenario

![onlyoffice](https://user-images.githubusercontent.com/18012023/50864142-695ee580-13a1-11e9-983c-0598084d9100.png)

Document Server Version: 5.2
OwnCloud Version: 10.0.10
Integration APP: 2.0.3
OS: Debian Stretch

I have deployed the Document Server using deb packages, all traffic is encrypted with SSL certificates from letsencrypt, all works fine except when I set the secret key in OwnCloud, after that I see the subject error in OwnCloud. In /var/log/onlyoffice/documentserver/converter/out.log appears this error:

`[2019-01-08T22:44:48.055] [ERROR] nodeJS - error downloadFile:url=https://myowncloud.domain/index.php/apps/onlyoffice/empty?doc=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhY3Rpb24iOiJlbXB0eSJ9.2-1oi_x4mbFuEGeaRCJwoFvbYQWgglVicjye_M8P_2Y;attempt=3;code:null;connect:null;(id=conv_check_501103595_docx)
Error: Error response: statusCode:403 ;body:
{"message":"Access denied"}
    at Request._callback (/var/www/onlyoffice/documentserver/server/Common/sources/utils.js:250:18)
    at Request.self.callback (/var/www/onlyoffice/documentserver/server/Common/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/var/www/onlyoffice/documentserver/server/Common/node_modules/request/request.js:1161:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/var/www/onlyoffice/documentserver/server/Common/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
`
This error appears in owncloud.log

`{"reqId":"VR0YDhRtGpnrmVHwjqLB","level":3,"time":"2019-01-09T00:11:34+00:00","remoteAddr":"192.168.2.93","user":"--","app":"onlyoffice","method":"GET","url":"\/index.php\/apps\/onlyoffice\/empty?doc=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhY3Rpb24iOiJlbXB0eSJ9.ivCERHb8zFHWi0YwNs2EEu4RqKOv0mdKmIky-WXzwR8","message":"Download empty without jwt"}
{"reqId":"Dl0wnhbowqLAYuq77dZB","level":3,"time":"2019-01-09T00:11:35+00:00","remoteAddr":"192.168.2.93","user":"--","app":"onlyoffice","method":"GET","url":"\/index.php\/apps\/onlyoffice\/empty?doc=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhY3Rpb24iOiJlbXB0eSJ9.ivCERHb8zFHWi0YwNs2EEu4RqKOv0mdKmIky-WXzwR8","message":"Download empty without jwt"}
{"reqId":"MjJZ1qNmLbE09TlGp4r8","level":3,"time":"2019-01-09T00:11:36+00:00","remoteAddr":"192.168.2.93","user":"--","app":"onlyoffice","method":"GET","url":"\/index.php\/apps\/onlyoffice\/empty?doc=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhY3Rpb24iOiJlbXB0eSJ9.ivCERHb8zFHWi0YwNs2EEu4RqKOv0mdKmIky-WXzwR8","message":"Download empty without jwt"}
{"reqId":"9OioMhCN8XtvIEswfNMS","level":3,"time":"2019-01-09T00:11:38+00:00","remoteAddr":"192.168.2.60","user":"admin","app":"onlyoffice","method":"PUT","url":"\/index.php\/apps\/onlyoffice\/ajax\/settings","message":"GetConvertedUri on check error: Se ha producido un error en el servicio de documentos: Error while downloading the document file to be converted."}`

This is my /etc/onlyoffice/documentserver/local.json
`{
  "services": {
    "CoAuthoring": {
      "sql": {
        "dbHost": "localhost",
        "dbName": "onlyoffice",
        "dbUser": "onlyoffice",
        "dbPass": "onlyoffice"
      },
      "redis": {
        "host": "localhost"
      },
      "token": {
        "enable": {
          "request": {
            "inbox": true,
            "outbox": true
          },
          "browser": true 
        },
        "inbox": {
          "header": "Authorization"
        },
        "outbox": {
          "header": "Authorization"
        }
      },
      "secret": {
        "inbox": {
          "string": "MYSECRETKEY"
        },
        "outbox": {
          "string": "MYSECRETKEY"
        },
        "session": {
          "string": "MYSECRETKEY"
        }
      }
    }
  },
  "rabbitmq": {
    "url": "amqp://guest:guest@localhost"
  }
}
`
This is my IntegrationApp config:
![screenshot_2019-01-09 ajustes - owncloud](https://user-images.githubusercontent.com/18012023/50866291-ab8c2500-13a9-11e9-8de3-58f89151cec8.png)

**Comment by LinneyS** [comment]
Did you restart ONLYOFFICE services after changing `local.json`?
```supervisorctl restart all```

**Comment by fgarpe** [comment]
> Did you restart ONLYOFFICE services after changing `local.json`?
> `supervisorctl restart all`

Yes :(

**Comment by fgarpe** [comment]
> Try changing the header:
> ONLYOFFICE local.json
> 
> ```
> "inbox": {
>   "header": "AuthorizationJwt"
> },
> "outbox": {
>   "header": "AuthorizationJwt"
> }
> ```
> 
> ownCloud config.php
> 
> ```
> 'onlyoffice' => array (
>     'jwt_header' => "AuthorizationJwt"
> )
> ```

is working!!!. Thank you very much!

**Comment by fgarpe** [comment]
I'm going to close the issue because it's solved. Again thank you very much, onlyoffice It's an impressive piece of software.
