### ISSUE TITLE
Nextcloud ONLYOFFICE integration app 

### ISSUE THREAD

**Issue by qiaoxy** [ONLYOFFICE/onlyoffice-owncloud#246]
Nextcloud version : v15.0.4
ONLYOFFICE version : v2.1.3

ONLYOFFICE app can not enable in Nextcloud. The warning message is blow:

    This app has no minimum Nextcloud version assigned. This will be an error in the future.
    This app has no maximum Nextcloud version assigned. This will be an error in the future.
    This app cannot be installed because the following dependencies are not fulfilled:
        Server version 10 or lower is required.

**Comment by ibnpetr** [comment]
Please describe step by step your actions when installing the ONLYOFFICE app.
Do you try to install it from the Nextcloud App Store?

**Comment by qiaoxy** [comment]
@ibnpetr 

1. install onlyoffice using docker, the parameter is show below and test result is OK:

```
sudo docker run -i -t -d -p 8081:80 --restart=always \
    --name onlyoffice \
    -v /home/docker/onlyoffice/DocumentServer/logs:/var/log/onlyoffice  \
    -v /home/docker/onlyoffice/DocumentServer/data:/var/www/onlyoffice/Data  \
    -v /home/docker/onlyoffice/DocumentServer/lib:/var/lib/onlyoffice \
    -v /home/docker/onlyoffice/DocumentServer/db:/var/lib/postgresql \
    onlyoffice/documentserver
```

2. install nextcloud using docker, the parameter is show below:

```
sudo docker run -i -t -d -p 9090:80 --restart=always \
    --name nextcloud \
    -v /home/docker/nextcloud/config:/var/www/html/config \
    -v /home/docker/nextcloud/data:/var/www/html/data \
    -v /home/docker/nextcloud/apps:/var/www/html/apps \
    nextcloud
```

3. I just follow the steps from README.md file of https://github.com/ONLYOFFICE/onlyoffice-nextcloud project.

```
cd /home/docker/nextcloud/apps
git clone https://github.com/ONLYOFFICE/onlyoffice-nextcloud.git onlyoffice
chown -R www-data:www-data onlyoffice
```

4. Nextcloud version : v15.0.4
ONLYOFFICE version : v2.1.3

ONLYOFFICE app can not enable in Nextcloud. The warning message is blow:

```
This app has no minimum Nextcloud version assigned. This will be an error in the future.
This app has no maximum Nextcloud version assigned. This will be an error in the future.
This app cannot be installed because the following dependencies are not fulfilled:
    Server version 10 or lower is required.
```

**Comment by LinneyS** [comment]
@qiaoxy 
> ONLYOFFICE version : v2.1.3

ONLYOFFICE Nextcloud app v2.1.3 does not exist. You have installed ownCloud app.

**Comment by qiaoxy** [comment]
oh, I messed up.  thank you, I got it.
@LinneyS
