### ISSUE TITLE
Save files as PDFs

### ISSUE THREAD

**Issue by rollanders** [ONLYOFFICE/onlyoffice-owncloud#264]
Pdfs are faster to view and have advantages when shared. It would be handy if the file could be saved as a pdf. I can write out as a pdf on my local computer but not directly in the cloud.

**Comment by alexanderonlyoffice** [comment]
Hello @rollanders, thank you for your feedback. We will take it into consideration.

**Comment by LinneyS** [comment]
Maybe the "save as" feature will help you?
Check [current app](https://github.com/ONLYOFFICE/onlyoffice-owncloud/blob/master/CHANGELOG.md#301)

**Comment by LinneyS** [comment]
07d4a0f4ec22a9198cb67fcd1b4e28be999483a3
