### ISSUE TITLE
$editable = $file->isUpdateable(), should be isUpdatable()

### ISSUE THREAD

**Issue by Peterede** [ONLYOFFICE/onlyoffice-owncloud#265]
https://github.com/ONLYOFFICE/onlyoffice-owncloud/blob/33753bca3421ada0041694088a46d44c72901257/controller/editorcontroller.php#L541

The function call is incorrect, according to the docs and source the function is isUpdatable() without the 'e'.

**Comment by alexanderonlyoffice** [comment]
Hello @Peterede, thank you for the information. We will check it.

**Comment by LinneyS** [comment]
This is a question for the ownCloud developers.
https://doc.owncloud.org/phpdoc/classes/OCP.Files.FileInfo.html#method_isUpdateable

https://github.com/owncloud/core/blob/2de709ee929ff8ffd480019c82e09929134ad41d/lib/private/Files/FileInfo.php#L248
