### ISSUE TITLE
Error downloading file to be converted

### ISSUE THREAD

**Issue by Sarcasthik** [ONLYOFFICE/onlyoffice-owncloud#269]
Hello,

After installing UCS4.4, let's encrypt, owncloud and onlyoffice I'm getting an error when I'm trying to configure onlyoffice

And the log file simply says : 

[2019-06-05T13:47:49.248] [ERROR] nodeJS - error downloadFile:url=https://10.0.1.33/owncloud/apps/onlyoffice/empty?doc=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhY3Rpb24iOiJlbXB0eSJ9.8Xxno0drgo6gkkmYFYtSDppopeJvVpqLfY31X7e98N4;attempt=3;code:null;connect:null;(id=conv_check_1107174278_docx)
Error: Hostname/IP doesn't match certificate's altnames: "IP: 10.0.1.33 is not in the cert's list: "

By no mean I am a pro regarding all this, but I did this kind of installation quite a few times already and this never happened. Any idea anyone ?

**Comment by ibnpetr** [comment]
Hello 
Do you use ONLYOFFICE installed as an app in the UCS environment?
Then use servername/onlyoffice-documentserver/
BTW please note that you have a public link to your UCS on your screenshot.
P.S. Just checked, you do not have documentserver in UCS, so I would recommend to [install it first](https://www.univention.com/products/univention-app-center/app-catalog/onlyoffice-ds/) or try using preconfigured appliance [owncloud + onlyoffice](https://www.univention.com/products/univention-app-center/onlyoffice-document-server-with-owncloud/)

**Comment by Sarcasthik** [comment]
Hi !

Yes we do use it as an app in UCS.
Thanks for the warning I was kind of in a hurry and did not pay attention to the links, removed it.

I'll try it by setting the servername instead and get back to you.

Thanks !

**Comment by Sarcasthik** [comment]
Setting it to the server name doesn't change much it seems, I still get the same error.

One thing I did not say is that it was working perfectly fine before I updated the plugin, then we started getting blank pages when opening a document and now nothing

**Comment by Sarcasthik** [comment]
Leaving this here.

Support team helped me understand what was going on. I had to change some config files to make it work again. The default plugin config still doesn't work for me but with some tweaking ONLYOFFICE is back online. 

Thanks for the support guys.
