### ISSUE TITLE
ownCloud missing entries for Activities and Versions 

### ISSUE THREAD

**Issue by GandalfUFR** [ONLYOFFICE/onlyoffice-owncloud#27]
While everything else (ownCloud 9.1.4 to OnlyOffice 4.2.11 integration, online collaborative document editing, etc.) working as expected I do not see any entries in the details section of the ownCloud documents showing me new file versions or user activities. Not even sure if this is behavior by design, a bug or should go to the wish list for future improvements.

**Comment by GandalfUFR** [comment]
More info: just found out that it works in the same environment for my own files but not for files shared with me (via internal ownCloud group). Seems that only changes by owner of the file are tracked / logged.

**Comment by doooggyy** [comment]
Hi,
I have the same problem.

I have integrated NC 12.0.2+ onlyoffice 1.1.3, I open a document I edit, I close the document and I check the versions of the document and I find nothing.

Thank you

**Comment by doooggyy** [comment]
Hi,
I have the same problem.

I have integrated NC 12.0.2+ onlyoffice 1.1.3, I open a document I edit, I close the document and I check the versions of the document and I find nothing. If it is saved but the document versions do not.

Thank you

**Comment by ibnpetr** [comment]
The file will be saved in about 10 sec when the editing session is closed.
Then Nextcloud will update the version of the file
Please try downloading the file from the Nextcloud interface and check if the changes are written to the file.

**Comment by alexanderonlyoffice** [comment]
Hello @doooggyy,

Could you please specify if the problem recurs or we can close the topic.

**Comment by doooggyy** [comment]
Hello how are you

when I edit the file there are no versions of the document, if two people edit the same document at the same time there are no versions of the document, this is to rewind the changes made in the document, it does not work.
versions or revisions does not work.

Thank you!!

**Comment by alexanderonlyoffice** [comment]
Hello @doooggyy,

Could you please verify by sending a screenshot that the size of the file and its change date are changing, but the new version doesn't appear.

**Comment by doooggyy** [comment]
Hi, @alexanderonlyoffice 

When I create an OnlyOffice file and online edit it and after that close the file.

Nextcloud doesn't create a version file. Also if edit it again it also doesn't create a new version of it.

* screenshot:

https://ibb.co/nLJNWR

Thks

**Comment by alexanderonlyoffice** [comment]
Hello @doooggyy,

It seems that the URL addresses in the NextCloud admin panel are incorrect. Please do the following to check: Go to the NextCloud admin panel -> Section with ONLYOFFICE addresses -> Click '**Save**' button and check if there is a notification at the top of the page that addresses are successfully saved.

**Comment by doooggyy** [comment]
hello @alexanderonlyoffice 

Displays the following:
Error attempting to establish connection (Bad request or time limit error)Nextcloud

* screenshot Onlyoffice configuration on nextcloud : https://ibb.co/detCY6
* screenshot service Onlyoffice: https://ibb.co/eM3J6R

**Comment by doooggyy** [comment]
solved, enter the code in the config.php of nextcloud:


'onlyoffice' =>
        array (
            'verify_peer_off' => TRUE,
        )
