### ISSUE TITLE
2.2.1 blank screen when trying to open document

### ISSUE THREAD

**Issue by teknoprep** [ONLYOFFICE/onlyoffice-owncloud#270]
2.2.1 updated today. Had no issues previously. Upgrades to latest community of docker image and still nothing working... just a blank screen when i go to edit files.

need to know where to get logs to post so i can get a fix going.

don't know how to downgrade the application back to 2.1.7

**Comment by HelenBelova17** [comment]
Hello, @**teknoprep**, what version Owncloud do you use?

**Comment by teknoprep** [comment]
lastest stable version as of July 6th per the updater

**Comment by HelenBelova17** [comment]
@**teknoprep**, specify the version in numbers please.

**Comment by amarildosertorio** [comment]
We are having the same problem after upgrading to 2.2.1.

owncloud version => 10.0.9.5

![error](https://user-images.githubusercontent.com/51493844/59130034-b93bdb80-8944-11e9-88a7-076d51675c80.png)

**Comment by amarildosertorio** [comment]
For more information

![zray](https://user-images.githubusercontent.com/51493844/59135771-9b777200-8956-11e9-8613-e01eeee0e0cb.png)

**Comment by LinneyS** [comment]
Fixed b429d15aa40b8dac0fe19f3e424d5819a0c32e80

**Comment by amarildosertorio** [comment]
> Fixed [b429d15](https://github.com/ONLYOFFICE/onlyoffice-owncloud/commit/b429d15aa40b8dac0fe19f3e424d5819a0c32e80)

@LinneyS, 

Thanks!

**Comment by teknoprep** [comment]
great shit... i just git checkout b429d15 and it worked great.. i really appreciate you checking this out and fixing it
