### ISSUE TITLE
Running Onlyoffice on Port 8080 via HTTP

### ISSUE THREAD

**Issue by MaBurn** [ONLYOFFICE/onlyoffice-owncloud#28]
Hello,

i have installed OnlyOffice and want to use ist with Owncloud. After configuring ip:8080 at the Owncloud admin Page i get the Error: 
ONLYOFFICE app not configured. Please contact admin

I can creat documents but i cannot edit them.
Is it not Possible to run OnlyOffice via port 8080?

**Comment by JohnPerkin** [comment]
Hello! Earlier we have answered that current version of Document Server doesn't support listening to custom ports  https://github.com/ONLYOFFICE/onlyoffice-owncloud/issues/9#issuecomment-284364955
This function will be implemented in the 4.3.0 release
