### ISSUE TITLE
POST /apps/onlyoffice/ajax/new 403 Forbidden

### ISSUE THREAD

**Issue by romale** [ONLYOFFICE/onlyoffice-owncloud#288]
Hi,
i've installed onlyoffice (OO) and owncloud (OC) on 2 docker containers on same virtual machine (VM), centos 7.
Then i've configured apache proxy (wproxy hostname) for SSL termination on differrent VM. 

**So, my environment:**
OC OO plugin version 3.0.1
OC version 10.2.1 (stable)
OO version ? (how to check?)

OO and OC on VM with IP 172.16.0.5
wproxy on VM with IP 10.1.1.10
docs.example.com resolves to 10.1.1.10
cloud.example.com resolves to 10.1.1.10

**Apache configs**
for docs
```
<VirtualHost _default_:443>

ServerName docs.example.com

ProxyPreserveHost On
SSLProxyEngine On
SSLProxyCheckPeerCN off
SSLProxyCheckPeerName off

SetEnvIf Host "^(.*)$" THE_HOST=$1
RequestHeader set X-Forwarded-Proto https
RequestHeader set X-Forwarded-Host %{THE_HOST}e
ProxyAddHeaders Off

ProxyPassMatch (.*)(\/websocket)$ "ws://172.16.0.5/$1$2"
ProxyPass /.well-known !
ProxyPass / "http://172.16.0.5/"
ProxyPassReverse / "http://172.16.0.5/"
...
other ssl params
</VirtualHost>
```
for cloud
```
<VirtualHost _default_:443>

ServerName cloud.example.com

ProxyPreserveHost On
SSLProxyEngine On
SSLProxyCheckPeerCN off
SSLProxyCheckPeerName off

ProxyPass /.well-known !
ProxyPass / http://172.16.0.5:8080/
ProxyPassReverse / http://172.16.0.5:8080/
...
other ssl params
</VirtualHost>
```

In OC onlyoffice configuration:

> 
> ONLYOFFICE Document Service Location specifies the address of the server with the document services installed. Please change the '<documentserver>' for the server address in the below line.
> 
> Document Editing Service address
> https://docs.example.com/
> 
> Secret key (leave blank to disable)
> EMPTY
> 
> Advanced server settings
> 
> Document Editing Service address for internal requests from the server
> https://docs.example.com/
> 
> Server address for internal requests from the Document Editing Service
> https://cloud.example.com/

All work fine, but I can't create Document file and edit it. If I click on "PLUS" in OC interface and select Document, then new browser page opens and has only text "Loading, please wait.", no happens.
In browser console i see:
`POST XHR https://cloud.example.com/apps/onlyoffice/ajax/new [HTTP/1.1 403 Forbidden 197мс]`

After that, in OC interface I see file "Document.docx" 0KB

I've checked date and time on all servers, the same. SSL certs for "docs" and "cloud" is valid, from Lets'encrypt.

**I was try this solutions:**

1. https://github.com/ONLYOFFICE/onlyoffice-owncloud/issues/74#issuecomment-328530121
2. SetEnvIf Authorization "(.*)" HTTP_AUTHORIZATION=$1

But not worked.

**Comment by romale** [comment]
Solved.
After chaning in /var/www/owncloud/config/config.php

from
```
  'trusted_domains' =>
  array (
    0 => 'cloud.example.com',
  ),
```
to
```
  'trusted_domains' =>
  array (
    0 => 'cloud.example.com',
    1 => 'docs.example.com',
  ),
```

**Comment by romale** [comment]
Also, if you have owncloud antivirus app enabled, but owncloud can't access it, you will have this issue too.

**Comment by alexanderonlyoffice** [comment]
@romale thank you for the provided information, we will check it.

**Comment by LinneyS** [comment]
The problem with the trusted domain and antivirus is separate tasks.
Trusted domain - you decide.
I will add error handling from the antivirus application in the next version.
