### ISSUE TITLE
Cron: Error PHP Undefined index: REQUEST_URI at /var/www/cloud/apps/onlyoffice/appinfo/application.php#65

### ISSUE THREAD

**Issue by sosed213** [ONLYOFFICE/onlyoffice-owncloud#29]
Nextcloud 11.0.2 (stable)

PHP
Version: 7.1.3
Memory Limit: 512.0 MB
Max Execution Time: 3600
Upload max size: 10.0 GB

Database
Type: mysql
Version: 10.1.15
Size: 344.1 MB

APP Onlyoffice 1.0.1

OnlyOffice Document Server in Docker

All Last version!

Error	PHP	Undefined index: REQUEST_URI at /var/www/cloud/apps/onlyoffice/appinfo/application.php#65	2017-03-30T07:45:02+0600
Error	PHP	Undefined index: REQUEST_URI at /var/www/cloud/apps/onlyoffice/appinfo/application.php#65	2017-03-30T07:30:01+0600
Error	PHP	Undefined index: REQUEST_URI at /var/www/cloud/apps/onlyoffice/appinfo/application.php#65	2017-03-30T07:15:01+0600
Error	PHP	Undefined index: REQUEST_URI at /var/www/cloud/apps/onlyoffice/appinfo/application.php#65	2017-03-30T07:00:02+0600
Error	PHP	Undefined index: REQUEST_URI at /var/www/cloud/apps/onlyoffice/appinfo/application.php#65	2017-03-30T07:00:02+0600
Error	PHP	Undefined index: REQUEST_URI at /var/www/cloud/apps/onlyoffice/appinfo/application.php#65	2017-03-30T06:45:01+0600
Error	PHP	Undefined index: REQUEST_URI at /var/www/cloud/apps/onlyoffice/appinfo/application.php#65	2017-03-30T06:30:01+0600
Error	PHP	Undefined index: REQUEST_URI at /var/www/cloud/apps/onlyoffice/appinfo/application.php#65	2017-03-30T06:15:01+0600
Error	PHP	Undefined index: REQUEST_URI at /var/www/cloud/apps/onlyoffice/appinfo/application.php#65	2017-03-30T06:00:01+0600
Error	PHP	Undefined index: REQUEST_URI at /var/www/cloud/apps/onlyoffice/appinfo/application.php#65	2017-03-30T05:45:02+0600
Error	PHP	Undefined index: REQUEST_URI at /var/www/cloud/apps/onlyoffice/appinfo/application.php#65	2017-03-30T05:45:02+0600
Error	PHP	Undefined index: REQUEST_URI at /var/www/cloud/apps/onlyoffice/appinfo/application.php#65	2017-03-30T05:30:01+0600
Error	PHP	Undefined index: REQUEST_URI at /var/www/cloud/apps/onlyoffice/appinfo/application.php#65	2017-03-30T05:15:02+0600
Error	PHP	Undefined index: REQUEST_URI at /var/www/cloud/apps/onlyoffice/appinfo/application.php#65	2017-03-30T05:00:01+0600
Error	PHP	Undefined index: REQUEST_URI at /var/www/cloud/apps/onlyoffice/appinfo/application.php#65	2017-03-30T04:45:02+0600
Error	PHP	Undefined index: REQUEST_URI at /var/www/cloud/apps/onlyoffice/appinfo/application.php#65	2017-03-30T04:45:02+0600
Error	PHP	Undefined index: REQUEST_URI at /var/www/cloud/apps/onlyoffice/appinfo/application.php#65	2017-03-30T04:30:01+0600
Error	PHP	Undefined index: REQUEST_URI at /var/www/cloud/apps/onlyoffice/appinfo/application.php#65	2017-03-30T04:15:02+0600
Error	PHP	Undefined index: REQUEST_URI at /var/www/cloud/apps/onlyoffice/appinfo/application.php#65	2017-03-30T04:00:01+0600
Error	PHP	Undefined index: REQUEST_URI at /var/www/cloud/apps/onlyoffice/appinfo/application.php#65	2017-03-30T03:45:02+0600
Error	PHP	Undefined index: REQUEST_URI at /var/www/cloud/apps/onlyoffice/appinfo/application.php#65	2017-03-30T03:30:01+0600
Error	PHP	Undefined index: REQUEST_URI at /var/www/cloud/apps/onlyoffice/appinfo/application.php#65	2017-03-30T03:30:01+0600
Error	PHP	Undefined index: REQUEST_URI at /var/www/cloud/apps/onlyoffice/appinfo/application.php#65	2017-03-30T03:15:01+0600
Error	PHP	Undefined index: REQUEST_URI at /var/www/cloud/apps/onlyoffice/appinfo/application.php#65	2017-03-30T03:00:01+0600
Error	PHP	Undefined index: REQUEST_URI at /var/www/cloud/apps/onlyoffice/appinfo/application.php#65	2017-03-30T02:45:01+0600
Error	PHP	Undefined index: REQUEST_URI at /var/www/cloud/apps/onlyoffice/appinfo/application.php#65	2017-03-30T02:30:01+0600
Error	PHP	Undefined index: REQUEST_URI at /var/www/cloud/apps/onlyoffice/appinfo/application.php#65	2017-03-30T02:15:01+0600
Error	PHP	Undefined index: REQUEST_URI at /var/www/cloud/apps/onlyoffice/appinfo/application.php#65	2017-03-30T02:15:01+0600
Error	PHP	Undefined index: REQUEST_URI at /var/www/cloud/apps/onlyoffice/appinfo/application.php#65	2017-03-30T02:00:01+0600
Error	PHP	Undefined index: REQUEST_URI at /var/www/cloud/apps/onlyoffice/appinfo/application.php#65	2017-03-30T01:45:01+0600
Error	PHP	Undefined index: REQUEST_URI at /var/www/cloud/apps/onlyoffice/appinfo/application.php#65	2017-03-30T01:30:02+0600
Error	PHP	Undefined index: REQUEST_URI at /var/www/cloud/apps/onlyoffice/appinfo/application.php#65	2017-03-30T01:15:17+0600
Error	PHP	Undefined index: REQUEST_URI at /var/www/cloud/apps/onlyoffice/appinfo/application.php#65	2017-03-30T01:15:01+0600
Error	PHP	Undefined index: REQUEST_URI at /var/www/cloud/apps/onlyoffice/appinfo/application.php#65	2017-03-30T01:04:02+0600
Error	PHP	Undefined index: REQUEST_URI at /var/www/cloud/apps/onlyoffice/appinfo/application.php#65	2017-03-30T01:04:02+0600
Error	PHP	Undefined index: REQUEST_URI at /var/www/cloud/apps/onlyoffice/appinfo/application.php#65	2017-03-30T01:00:02+0600
Error	PHP	Undefined index: REQUEST_URI at /var/www/cloud/apps/onlyoffice/appinfo/application.php#65	2017-03-30T00:45:02+0600
Error	PHP	Undefined index: REQUEST_URI at /var/www/cloud/apps/onlyoffice/appinfo/application.php#65	2017-03-30T00:30:02+0600

**Comment by JohnPerkin** [comment]
Добрый день!
Данная проблема уже обсуждалась https://github.com/ONLYOFFICE/onlyoffice-owncloud/issues/12  
Правки уже внесены в ветке develop. В следующей версии они будут включены в master.
