### ISSUE TITLE
Menu not showing all the tabs when editing .odt and .doc

### ISSUE THREAD

**Issue by tubia** [ONLYOFFICE/onlyoffice-owncloud#293]
Hi,

I successfully installed OnlyOffice document server, however, while I am able to see the full menu when editing a `.docx` file (changing the styles of the text and so on), I am only able to see "File" and "Plugin" tab when editing `.doc` or `.odt` files.

`.doc` and `.odt` are flagged in the "The default application for opening the format" setting.

If I flag `.odt` in the ` Open the file for editing (due to format restrictions, the data might be lost when saving to the formats from the list below)` I am also able to see the tabs when editing an `.odt` file but still missing for `.doc`.

Am I missing something?

Any help would be greatly appreciated!

**Comment by HelenBelova17** [comment]
Hello, @**tubia**,
in the list of settings 'Open the file for editing...' there is no .doc. It means .doc file can not be open for edit by default.
