### ISSUE TITLE
Nextcloud 11 compatibility?

### ISSUE THREAD

**Issue by poVoq** [ONLYOFFICE/onlyoffice-owncloud#3]
Please make sure this also works with Nextcloud11. Normally the Owncloud apps work, but Nextcloud 11 as it's own app store and some other small changes.

Best would be if this could be published for Nextcloud as well.

**Comment by nommaz** [comment]
+1

**Comment by geiseri** [comment]
+1 :)

**Comment by dionysiusmarquis** [comment]
+1

**Comment by ibnpetr** [comment]
Dear friends
Thanks a lot for your interest in our product, your opinion is important for us.
You will be informed as soon as a version for Nextcloud is published.
Please keep in touch

**Comment by Ludovicis** [comment]
+1

**Comment by nopeee535** [comment]
i changed the max-version in .../Nextcloud/apps/onlyoffice/appinfo/info.xml like this:

<dependencies>
        <owncloud min-version="9.0" max-version=**"11.1"** />

**Comment by thfree** [comment]
+1

**Comment by thfree** [comment]
Вообщем на (11.0.1) с наскока не заработало, пустой экран при редактирование. Сервер документов вроде работает, так же подкручен SSL. 

В логах это:
```
{"reqId":"RX0k068EAe\/UH7wE1LNz","remoteAddr":"","app":"PHP","message":"Undefined index: REQUEST_URI at \/****************\/apps\/onlyoffice\/appinfo\/application.php#65","level":3,"time":"21 February 2017 21:30:01","method":"--","url":"--","user":"--","version":"11.0.1.2"}
```

**Comment by Orhideous** [comment]
It wold be nice to have compatibility with Nextcloud.

**Comment by nommaz** [comment]
@nopeee535 is your download issue still existing? if the only issue is chanhing info.xml then i will go ahead and move to nextcloud...

**Comment by nopeee535** [comment]
it work but only in safari (on my mac) ... 
on chrome or firefox i get a contet security problem : 'unsafe-eval' (nothing happend -> white screen)
i found something like that:
https://content-security-policy.com/ 
im not sure if it is an apache reverse proxy problem or something diffrent ...
actual i found no way to fix it, maybe someone else ?
thats the output of the firefox console:

Content Security Policy: Die Einstellungen der Seite haben das Laden einer Ressource auf self blockiert ("script-src 'nonce-.......=' https://my.domain.de  'unsafe-eval'").

**Comment by mabe-at** [comment]
I have adapted the app to work with Nextcloud 11.0.2 https://github.com/mabe-at/onlyoffice-nextcloud

**Comment by JohnPerkin** [comment]
@mabe-at 
We appreciate your insterest in our product, but for For Nextcloud 10 the admin settings page got reworked. Detailed information you may see [here](https://docs.nextcloud.com/server/11/developer_manual/app/settings.html).
We are releasing nextcloud integration application. Enjoy it!

**Comment by mabe-at** [comment]
@JohnPerkin
You are welcome!
