### ISSUE TITLE
Error occurred in the document service: Error convertation unknown

### ISSUE THREAD

**Issue by sosed213** [ONLYOFFICE/onlyoffice-owncloud#30]
Nextcloud 11.0.2 (stable)

PHP
Version: 7.1.3
Memory Limit: 512.0 MB
Max Execution Time: 3600
Upload max size: 10.0 GB

Database
Type: mysql
Version: 10.1.15
Size: 344.1 MB

APP Onlyoffice 1.0.1

OnlyOffice Document Server in Docker

All Last version!

Error:
Sample File ABC.doc to convertation.

![screen0](https://cloud.githubusercontent.com/assets/16791649/24491989/86bad572-154b-11e7-8cfe-5af68beabaa1.png)
![screen1](https://cloud.githubusercontent.com/assets/16791649/24485440/4c0abd36-1526-11e7-8dfd-485f985565c6.png)
![screen2](https://cloud.githubusercontent.com/assets/16791649/24485441/4c0c4b10-1526-11e7-9a6c-4d78b00d4b32.png)

Error occurred in the document service: Error convertation unknown

**Comment by moonkir** [comment]
На первом скрине внизу видно адрес сервера
Не конвертируется потому что на папку которую тебе расшарили нет доступа на запись

**Comment by sosed213** [comment]
Странно. Я владелец папки. т.е. полные права.

**Comment by moonkir** [comment]
На внешних хранилищах еще не конвертится

**Comment by sosed213** [comment]
это обычная папка, не монтированая. или я чего то не понимаю

**Comment by moonkir** [comment]
Судя по скрину - у тебя документ лежит в папке Test
Эта папка либо кем то тебе расшарена - либо внешнее хранилище - судя по значку возле названия
Попробуй в другой папке конвертнуть этот документ

**Comment by JohnPerkin** [comment]
Добрый день!
1) Проверьте, работает ли у Вас редактирование на файлах **.docx**. Происходит ли сохранение документов?
2) Как у Вас открываются другие файлы **.doc**? Есть ли проблемы с **.xls**?
3) В командной строке Document Server введите команду **supervisorctl** и выложите результат ее выполнения

**Comment by sosed213** [comment]
1. *.docx, *.xlsx и *.pptx открываются, редактируются и сохраняются замечательно, я в восторге!

**Comment by sosed213** [comment]
А если просто тыкнуть по .doc и .xls то предлагается скачать. Через меню можно принудительно открыть через OnlyOffice, но ошибка конвертирования.

**Comment by sosed213** [comment]
чтобы выполнить команду supervisorctl, мне нужно войти в контейнер?

**Comment by JohnPerkin** [comment]
Команду supervisorctl можно не выполнять, проблема явно в самом файле. Прикрепите его здесь или, если в нем содержится приватная информация, отправьте на email support@onlyoffice.com.

**Comment by sosed213** [comment]
На всякий случай:

root@7dda980aa702:/# **supervisorctl**
onlyoffice-documentserver:converter RUNNING    pid 488, uptime 2 days, 1:01:20
onlyoffice-documentserver:docservice RUNNING    pid 465, uptime 2 days, 1:01:23
onlyoffice-documentserver:gc     RUNNING    pid 372, uptime 2 days, 1:01:26
onlyoffice-documentserver:metrics RUNNING    pid 369, uptime 2 days, 1:01:26
onlyoffice-documentserver:spellchecker RUNNING    pid 370, uptime 2 days, 1:01:26

**Comment by sosed213** [comment]
**JohnPerkin**, отправил на почту. Здесь не прикрепляется, ни *.doc, ни *.zip

**Comment by JohnPerkin** [comment]
Отправьте нам логи из директории **/var/log/onlyoffice/documentserver/** внутри контейнера DS

**Comment by sosed213** [comment]
**JohnPerkin**, так же отправил на почту.

**Comment by JohnPerkin** [comment]
У Вас установлен Document Server 4.1, который не поддерживает конвертацию файлов. Эта функция появилась в релизе 4.2. Пожалуйста, обновите ONLYOFFICE до актуальной версии.
