### ISSUE TITLE
collaboration issue on xlsx-files

### ISSUE THREAD

**Issue by Lujansen** [ONLYOFFICE/onlyoffice-owncloud#304]
Hello

we have trouble getting online collaboration to work on filetype:xlsx (Excel) files. PPT and DOCx work fine, but as soon as we start to work on xlsx filetype neither collaboration, nor saving data as a single user does work as expected.

We changed the application-Server also to the test-config, which is available - no change.

We have assessed the method of collaboration (fast or formal) - we have used different browsers etc - may I kindly ask for support here - as it looks very strange

**Comment by alexanderonlyoffice** [comment]
@Lujansen, please specify some additional information, so we are able to reproduce the issue on our side:

1. OS of the server where ONLYOFFICE Document Server is installed;
2. Its installation type (Docker or deb/rpm);
3. Currently installed version of the Document Server;
4. Version of the ONLYOFFICE integration app for ownCloud;
5. Version of ownCloud;
6. Could you please make a video or a .gif of the issue?

**Comment by Lujansen** [comment]
Hello Alexander

 

Sure – let me help you with the reference Info:

1.)    OS of the server where ONLYOFFICE Document Server is installed;

This is a linux MINT 19.3 Linux 5.3.0-40-generic #32~18.04.1-Ubunto SMP x86_64 GNU/Linux

2.)    Its installation type (Docker or deb/rpm);

Dedicated standalone server with independent DSL Router / Inet Access

3.)    Currently installed version of the Document Server;

The most actual one – let me know the unix command to confirm the installed version – supervisorctl just confirmes all processes running and the erroneous behavior happens not only on my server, but also on the test-server, which is provided in the owncloud admin module …

4.)    Version of the ONLYOFFICE integration app for ownCloud;

4.1.3

5.)    Version of ownCloud;

10.3.2.2 (last stable)

6.)    Could you please make a video or a .gif of the issue?

Sure have a recording – be my guest https://xlab3.jansen2.de/index.php/s/unsbX43HRuZcBy0

 

 

Yours Lutz

Tel +491718529123

 

 

Von: Alexander Zozulya [mailto:notifications@github.com] 
Gesendet: Mittwoch, 4. März 2020 13:48
An: ONLYOFFICE/onlyoffice-owncloud
Cc: Lutz Jansen; Mention
Betreff: Re: [ONLYOFFICE/onlyoffice-owncloud] collaboration issue on xlsx-files (#304)

 

 <https://github.com/Lujansen> @Lujansen, please specify some additional information, so we are able to reproduce the issue on our side:

1.	OS of the server where ONLYOFFICE Document Server is installed;
2.	Its installation type (Docker or deb/rpm);
3.	Currently installed version of the Document Server;
4.	Version of the ONLYOFFICE integration app for ownCloud;
5.	Version of ownCloud;
6.	Could you please make a video or a .gif of the issue?

**Comment by alexanderonlyoffice** [comment]
@Lujansen, could you please send us all logs of the Document Server to support@onlyoffice.com with a note 'For technical support'. Logs can be found in folder /var/log/onlyoffice/documentserver/logs for package installation.

**Comment by Lujansen** [comment]
Done

 



 

Von: Alexander Zozulya [mailto:notifications@github.com] 
Gesendet: Donnerstag, 5. März 2020 13:21
An: ONLYOFFICE/onlyoffice-owncloud
Cc: Lutz Jansen; Mention
Betreff: Re: [ONLYOFFICE/onlyoffice-owncloud] collaboration issue on xlsx-files (#304)

 

@Lujansen <https://github.com/Lujansen> , could you please send us all logs of the Document Server to support@onlyoffice.com with a note 'For technical support'. Logs can be found in folder /var/log/onlyoffice/documentserver/logs for package installation.

**Comment by alexanderonlyoffice** [comment]
@Lujansen, we received the logs, but I see only logs of nginx. Please make sure there are folders for converter, docservice and other Document Server services in folder /var/log/onlyoffice/documentserver/logs.

**Comment by Lujansen** [comment]
Alexander

 

We submitted all logfiles sameday last week.

What kind of response did the technical team come up with ?

 

The issue also happens with the complimentary test-server, which is offered for setup-purposes – so I doubt it has to do with the document-server…

 

Also it only happens with Filetyp:xlsx =Excel – the other office formats are not affected (…)

 

Looking forward the “resolution”

Yours Lutz

**Comment by alexanderonlyoffice** [comment]
@Lujansen, we received the logs, but I can't see errors related to co-editing. The only errors I see are about the license file. Could you please create a test account for us, so we check the issue with co-editing of the .xlsx files? If yes, please send us the email to support@onlyoffice.com.

**Comment by Lujansen** [comment]
Done – credentials provided

Lutz

**Comment by alexanderonlyoffice** [comment]
@Lujansen, thank you for the provided access, we managed to reproduce the mentioned issue on your instance. Could you please specify some more informaion:

1. Are you using commercial product Integration Edition or open source (free) version of the Document Server?
2. Please upload also fresh logs of the Document Server.

**Comment by Lujansen** [comment]
Hello Team

 

Done – I uploaded the Logfiles from 11:46 (UTC+1) to the Folder “Test-Scenario”

We are using the community edition (free)

 

Thank You

Lutz

 

 

 

Von: Alexander Zozulya [mailto:notifications@github.com] 
Gesendet: Dienstag, 24. März 2020 11:36
An: ONLYOFFICE/onlyoffice-owncloud
Cc: Lutz Jansen; Mention
Betreff: Re: [ONLYOFFICE/onlyoffice-owncloud] collaboration issue on xlsx-files (#304)

 

@Lujansen <https://github.com/Lujansen> , thank you for the provided access, we managed to reproduce the mentioned issue on your instance. Could you please specify some more informaion:

1.	Are you using commercial product Integration Edition or open source (free) version of the Document Server?
2.	Please upload also fresh logs of the Document Server.

**Comment by alexanderonlyoffice** [comment]
@Lujansen, we suppose problem might be in ownCloud instance. Is there a possibility to deploy test ownCloud instance and check the integration on it? If yes, please do it and specify also the way you deployed this instance of ownCloud - send me a link to the installation guide you used.

**Comment by Lujansen** [comment]
Hello

 

Logfiles are uploaded as requested into a logfile-2 folder next to the first one

 

The Owncloud instance is an installation from the root repository provided by owncloud and recently updated. Any install and update typically erases every file except config and data-directories, plus runs a compatibility-test / plausibility test, if any file is not according to standard.

 

So the only variable I can offer you is the PHP-Version and the .htaccess file. Beside the Owncloud-log, which I will upload also fresh

 

But – I can offer you a screen-sharing exercise, by which we can isolate the potential root of the problem without longer ping and pong J

 

How about scheduling a zoom-call and we stick the heads together – this is by far easier, than trying to make me run for a test-instance with webadmins and hoster… (beside the costs to it)

 

Kindest regards

 

Yours Lutz

**Comment by alexanderonlyoffice** [comment]
@Lujansen, please connect our Document Server to your ownCloud instance to make sure the problem is in ownCloud, as we can't reproduce the issue on our side.

Try to reproduce the issue and then upon the result we will consider what to do next. Please make a video, if the problem can be reproduced with our Document Server. I have sent you the email with the address of the Document Server.

**Comment by Lujansen** [comment]
Hello Alexander

 

The issue seems tob e solved with your configuration.

 

I just created a new file and the function works as expected. Will continue to edit with more users – 

However it would be fair to assume, it has no issue related to the owncloud instance – 

 

Lutz

**Comment by Lujansen** [comment]
Hello All

 

Confirmed – using the different Servers fixes the issue from a user-perspective, parallel editing on XLSx and asynchronous editing from different Users (with different setups) works as expected.

 

Let me know, what can be done to isolate the root cause on the OO-Server 

 

Yours Lutz

**Comment by alexanderonlyoffice** [comment]
@Lujansen, please confirm that the problem was solved by re-installation of the Document Server.

**Comment by Lujansen** [comment]
Hello Alex

 

Sure – however the final solution was to reinstall it without the addendum “rebuilding the spellchecker”, hence we reinstalled on 3 different Servers prior – with similar problem.

Only the reinstallation with a new and “virgin” Iso 19.3 Tricia Cinnamon and NOT applying the Spellchecker-Add on was the final solution.

This learning took elapsed 1 week of business-time and unavailability locally, I hope it adds your KDB and improves the experience to other members in the community

 

Kindest regards

 

Lutz

 

 

 

Von: Alexander Zozulya [mailto:notifications@github.com] 
Gesendet: Dienstag, 14. April 2020 11:09
An: ONLYOFFICE/onlyoffice-owncloud
Cc: Lutz Jansen; Mention
Betreff: Re: [ONLYOFFICE/onlyoffice-owncloud] collaboration issue on xlsx-files (#304)

 

@Lujansen <https://github.com/Lujansen> , please confirm that the problem was solved by re-installation of the Document Server.
