### ISSUE TITLE
Disable inline editor

### ISSUE THREAD

**Issue by J4RF** [ONLYOFFICE/onlyoffice-owncloud#305]
Can we get an option to disable the inline editor and still open files in the same tab? User experience is a lot worse with the inline editor and it seems like an unnecessary change. For example, if you scroll down a list of files and open a document, the editor renders at the top of the list, covering that section of the list and making inaccessible. The page remains scroll-able but the list is not, so you can scroll outside of the editor but can't access most of the files in the list. Overall it just feels janky and less intuitive. Would much prefer the old behaviour of being able to use a full editor without opening a new tab.

**Comment by HelenBelova17** [comment]
Hello @**J4RF**

Admin can disable the inline option on Onlyoffice setting page/Common settings/disable Open file in the same tab/Save.

**Comment by J4RF** [comment]
Not exactly what I was looking for. Before the latest release it was possible to open in same tab without the use of the inline editor. The inline editor is straight up awful, and we should have the option to disable it. Maybe I'm missing the point, but I don't see what requirement the inline editor is supposed to fill. It just feels like a buggy version of the non-inline editor.

**Comment by LinneyS** [comment]
Fixed in v5.0.1
