### ISSUE TITLE
Nextcloud 11.0.2 (stable) - "Error Download Failed"

### ISSUE THREAD

**Issue by zacharyrohrbach** [ONLYOFFICE/onlyoffice-owncloud#31]
Okay. So this is an issue that I have googled a bunch, and have found zero results for that actually fix my issue. I don't know what types of logs you would want me to provide to help you fix this issue. But I'll be happy to provide them if you tell me. I am accessing this internally, and this is the error I get when I open a document.

![2017-03-30-204120_3840x4080_scrot](https://cloud.githubusercontent.com/assets/13573113/24531875/2b3d1a5e-158a-11e7-984e-3326c5f6160d.png)

Some stuff up front
Ubuntu 16.04
Nginx 1.10.0 (Ubuntu)
Node v6.10.1
I installed all the packages that are necessary to install this, per your documentation. 

Please let me know what logs/configs/whatever you want. Thanks!

**Comment by JohnPerkin** [comment]
Hello!
Please check if Nextcloud's address is accessible from the server with ONLYOFFICE. You may use wget command.

**Comment by JohnPerkin** [comment]
Hello @zacharyrohrbach!
On the current moment is released ownCloud/Nextcloud ONLYOFFICE integration app 1.0.4. It has the ability to specify internal addresses for interaction between NextCloud and Document Server. Please set correct addresses to connect OnlyOffice.

**Comment by LinneyS** [comment]
Could you please specify if the problem recurs or we can close the topic.

**Comment by zacharyrohrbach** [comment]
Just close this. I haven't touched OnlyOffice since I had this issue, and uninstalled it.

**Comment by Djmaximus** [comment]
Hello @zacharyrohrbach!
It's a pitty! We could solve your issue! Please let me know if you change your mind.
