### ISSUE TITLE
OnlyOffice upgrade (to v4.3) offered to NextCloud users but different latest rev here

### ISSUE THREAD

**Issue by Daksol** [ONLYOFFICE/onlyoffice-owncloud#313]
I am not sure this is the right place to ask this question, but please advise me if not.

I support a NextCloud installation which includes OnlyOffice as a key component.

I just got an "update available" message from NextCloud to say that there is an upgrade to OnlyOffice from v4.2.0 to v4.3.0, as per screenshot below.

I came here to "onlyoffice-owncloud" as that seems to be the package used on NextCloud. I wanted to see what was included in this upgrade.

But the latest release showing here at **github.com/ONLYOFFICE/onlyoffice-owncloud** is at v4.2.1

Is this a momentary lapse of harmonisation, or am I looking in the wrong place?

Greatly appreciate the good work being done here.
Thanks
![NextCloud_Showing_OO_Update_v4-3-0](https://user-images.githubusercontent.com/42010857/85945820-83e3a080-b940-11ea-9c7f-6b19090a01ae.PNG)

**Comment by alexanderonlyoffice** [comment]
@Daksol, please note that you are using Nextcloud and searching for the release information in branch for ownCloud - these are two different storages and use different versions of ONLYOFFICE connector. Please follow the link https://github.com/ONLYOFFICE/onlyoffice-nextcloud/releases here is the information about release of ONLYOFFICE connector v.4.3.0 for Nextcloud that complies with the information in your Nextcloud instance.

**Comment by Daksol** [comment]
Thanks
