### ISSUE TITLE
Unavailable Owncloud configuration menu

### ISSUE THREAD

**Issue by sei-nicolas** [ONLYOFFICE/onlyoffice-owncloud#314]
Using owncloud-server 10.4.1 and app version 4.2.1 (installed either through market or manually extracting the tar archive in apps directory):
- no configuration menu appears
- URL ~/index.php/settings/admin#onlyoffice yields nothing related to onlyoffice, simply displays the same content as ~/settings/admin?sectionid=general
- I can find no error in logs

**Comment by HelenBelova17** [comment]
Hello @**sei-nicolas**, check that onlyoffice app is enabled, attach a screenshot with settings / admin / additional page.

**Comment by sei-nicolas** [comment]
Never mind (and thanks for the quick repy), I found the settings, at URL ~/admin?sectionid=additional [may the URL changed across version?]
