### ISSUE TITLE
Nextcloud 11.0.2 (stable) - "ONLYOFFICE app not configured. Please contact admin"

### ISSUE THREAD

**Issue by zacharyrohrbach** [ONLYOFFICE/onlyoffice-owncloud#32]
Okay. So this is an issue that I have googled a bunch, and have found zero results for that actually fix my issue. I don't know what types of logs you would want me to provide to help you fix this issue. But I'll be happy to provide them if you tell me. This is the error I get when I try to access a file outside of my network.

![2017-03-30-204837_3840x4080_scrot](https://cloud.githubusercontent.com/assets/13573113/24531893/53d59c2a-158a-11e7-870c-cfd69b3d980c.png)

Some stuff up front
Ubuntu 16.04
Nginx 1.10.0 (Ubuntu)
Node v6.10.1
I installed all the packages that are necessary to install this, per your documentation.

Please let me know what logs/configs/whatever you want. Thanks!

**Comment by moonkir** [comment]
This erorr view if:

nexctloud - nextcloud.xy - domain name
docserver - 192.168.X.X - ip adress
you щutside the docking server network - 192.168.X.X

**Comment by JohnPerkin** [comment]
Hello @zacharyrohrbach 
In this scenario you need to make ONLYOFFICE accessible from outside network by configuring apache on Nextcloud's server. Unfortunately we do not have a solution for the current version of Document Server but we plan to implement it for 4.3 release.
For today we can suggest you to watch our configuration examples for [nginx](https://github.com/ONLYOFFICE/document-server-proxy/tree/master/nginx) and configure apache on their basis.

**Comment by emresaracoglu** [comment]
Do you use SSL for OnlyOffice server?

**Comment by JohnPerkin** [comment]
Please try to update ownCloud/Nextcloud ONLYOFFICE integration app to the latest version

**Comment by JohnPerkin** [comment]
Hello @zacharyrohrbach 
On the current moment is released integration app 1.0.4. Please update ownCloud/Nextcloud app to the latest version and tell us if it helped or did not.

**Comment by alexanderonlyoffice** [comment]
Hello @zacharyrohrbach,

Could you please specify if the problem recurs or we can close the topic.

**Comment by alexanderonlyoffice** [comment]
This ticket is closed as there is no feedback about the status of the issue.
