### ISSUE TITLE
Nextcloud Plugin

### ISSUE THREAD

**Issue by emresaracoglu** [ONLYOFFICE/onlyoffice-owncloud#33]
`Error PHP Undefined index: REQUEST_URI at /home/getddo/public_html/apps/onlyoffice/appinfo/application.php#65` 

I getting this error with cron

**Comment by JohnPerkin** [comment]
Hello @emresaracoglu!
The issue has already been discussed https://github.com/ONLYOFFICE/onlyoffice-owncloud/issues/12
Commits are already included in the branch develop. In the next release they will appear in master.
