### ISSUE TITLE
ownCloud manual file locks are not respected by onlyoffice-owncloud

### ISSUE THREAD

**Issue by J4RF** [ONLYOFFICE/onlyoffice-owncloud#330]
As of ownCloud 10.5, [manually locking files is supported](https://owncloud.com/news/whats-new-in-owncloud-server-10-5-file-locking/). In my own testing against two different instances running: 

- ownCloud server 10.5.0
- ONLYOFFICE DocumentServer 5.6.3
- onlyoffice-owncloud 4.2.1 and 6.0.1 (tried both on both instances).

I found that files that are locked manually can still be modified and saved by users other than the lock owner using the built-in OnlyOffice apps. This pretty much breaks the usability of file locking for anyone using onlyoffice-owncloud on their ownCloud server. Expected behaviour is that users would be denied the ability to modify a locked file unless they are the owner of the file lock. 

Let me know if more info is needed.

**Comment by alexanderonlyoffice** [comment]
@J4RF, please accept our apologies for the delayed response. Could you please describe the detailed step-by-step scenario on how we can reproduce the issue on our side?

We look forward to hearing from you.

**Comment by J4RF** [comment]
- sign in as user1, create a document file
- share document file with user2
- lock document file as user1
- sign in as user2
- edit and save document

Expected behaviour: user2 should not be able to modify the locked file
Actual behaviour: user2 can modify the locked file
