### ISSUE TITLE
Disabling "Generate document preview" causes 404 requests

### ISSUE THREAD

**Issue by JammingBen** [ONLYOFFICE/onlyoffice-owncloud#336]
By default, "Generate document preview" is set to false. However, ownCloud core does not know anything about this setting, thus it will try to render a preview nonetheless. This results in various 404 calls and missing icons in the file versions list: 

![image](https://user-images.githubusercontent.com/50302941/108716060-efa3fa80-751b-11eb-8efe-46dc63e4b0e0.png)

**Steps to reproduce:**

* Create a new docx file with OnlyOffice
* Open the browser console and refresh the page -> you will notice multiple 404 errors
* Edit the file a few times so new versions are being created
* Open the versions list -> the previews/icons wont be rendered

I think the preferred way to handle this setting is via changing [the PreviewManager's capabilities](https://github.com/ONLYOFFICE/onlyoffice-owncloud/blob/master/lib/preview.php#L124) dynamically based on the setting. This way, ownCloud core implicitly knows about this setting and can handle previews properly.

**Comment by micbar** [comment]
@LinneyS is this fix part of the latest release?

**Comment by LinneyS** [comment]
Hi @micbar 
Yes
v6.3.1
