### ISSUE TITLE
ONLYOFFICE cannot be reached

### ISSUE THREAD

**Issue by osaffer** [ONLYOFFICE/onlyoffice-owncloud#337]
Hi,

I have owncloud and documentserver running in my kubernetes cluster in same namespace.
Onlyoffice app has been deployed too.
I can reach the documentserver/welcome page from owncloud pod.

Unfortunately I cannot edit/create/open any documents, error is "onlyoffice cannot be reached

To access owncloud, I use istio. My URL is istio.example.come/owncloud

I did not expose documentserver to public, is it mandatory ? 

I use advanced settings:

Advanced server settings 

Document Editing Service address for internal requests from the server
http://documentserver/

Server address for internal requests from the Document Editing Service
http://owncloud-svc/

As you see, I dont use https for the moment. 

Thanks for your support

**Comment by SergeyKorneyev** [comment]
Hi,

> I did not expose documentserver to public, is it mandatory ?

Yes, the Document Server needs to be accessible via the address specified in the main connector settings. It's used to download scripts, images, fonts etc.

**Comment by osaffer** [comment]
Thank you I will have a look

**Comment by osaffer** [comment]
Thank you very much it works perfectly !
