### ISSUE TITLE
Nextcloud 11.0.2 (stable) - Для файла с ограничением доступа по тегам получаем "Download failed"

### ISSUE THREAD

**Issue by ndanko** [ONLYOFFICE/onlyoffice-owncloud#34]
Интеграция c Nextcloud не работает для случая, когда для папки Nextcloud применен File access control. 
Есть правило, ограничивающее доступ групп пользователей к папке Nextcloud с тегом. Если права для доступа к файлу в папке все же хватает, то ONLYOFFICE уже не сможет его редактировать, получим ошибку "Download failed".

**Comment by JohnPerkin** [comment]
Добрый день @ndanko!
Пожалуйста обновите ownCloud/Nextcloud ONLYOFFICE integration app до последней версии и установите уровень логгирования равным 0 согласно [инструкции](https://doc.owncloud.org/server/latest/admin_manual/configuration_server/logging_configuration.html). Отправьте лог-файлы на email support@onlyoffice.com

**Comment by ndanko** [comment]
Добрый день, 
отправили на support@onlyoffice.com лог-файл

**Comment by ndanko** [comment]
Подскажите, есть ли планы решить эту проблему? Она останавливает переход на ваш продукт. Не можем разделить зоны и доступы в файловом пространстве, а значит для важных документов отказываемся от вашего инструмента и продолжаем использовать старые.

**Comment by ndanko** [comment]
Добрый день, 
подскажите, а когда планируется решать проблему с ошибкой при работе с правилами на доступ?
Уточнили подробности - файл будет успешно открываться, если создан строго до пометки папки тегом. 
То есть: 

Шаг 1. Создаем файл в папке средствами ONLYOFFICE в веб интерфейсе Nextcloud 
Шаг 2. Ограничиваем папку тегом, которому соответствует правило ограничения доступа (доступ ограничен, если пользователь НЕ включен в конкретную группу)
Результат: ONLYOFFICE успешно редактирует файл, ошибок нет.

А теперь повторим с новой папкой и новым файлом:
Шаг 1. Ограничиваем папку тегом, которому соответствует правило ограничения доступа (доступ ограничен, если пользователь НЕ включен в конкретную группу)
Шаг 2. Создаем файл в папке средствами ONLYOFFICE
Результат: ONLYOFFICE уже не сможет редактировать файл, получим ошибку "Download failed".

**Comment by LinneyS** [comment]
Приветствую.
Уточните, пожалуйста, повторяется ли проблема на последней версии?
Проблема в открытии файла в редакторе у пользователя из группы, если этой группе дали доступ на родительскую папку?

**Comment by LinneyS** [comment]
Не удалось воспроизвести проблему.
