### ISSUE TITLE
Error 400 - WebSockets for Bad Request

### ISSUE THREAD

**Issue by emresaracoglu** [ONLYOFFICE/onlyoffice-owncloud#35]
Hi,

I am getting this error, what is the cause of this error?
Can you help me with this?

192.168.1.99 : Server
192.168.1.101 : OnlyOffice

_vHost file for ofis.domain.com_
```
# vhost_start ofis.domain.com
<VirtualHost 192.168.1.99:443>
 ServerName ofis.domain.com
 ServerAdmin hello@domain.com
 SSLEngine on
 SSLProxyEngine On
 SSLCertificateFile /etc/letsencrypt/live/ofis.domain.com/cert.pem
 SSLCertificateKeyFile /etc/letsencrypt/live/ofis.domain.com/privkey.pem
 SSLCertificateChainFile /etc/letsencrypt/live/ofis.domain.com/fullchain.pem
 SetEnvIf User-Agent ".*MSIE.*" nokeepalive ssl-unclean-shutdown
<IfModule mod_suexec.c>
    SuexecUserGroup domain domain
</IfModule>

<IfModule mod_suphp.c>
    suPHP_UserGroup domain domain
    suPHP_ConfigPath /home/domain
</IfModule>

# OnlyOffice
	RequestHeader unset Accept-Encoding
	ProxyPass / http://192.168.1.101/
	ProxyPassReverse / http://192.168.1.101/
	
ProxyPass "/websocket" "wss://192.168.1.101/websocket"
ProxyPassReverse "/websocket" "wss://192.168.1.101/websocket"

</VirtualHost>
# vhost_end ofis.domain.com
```

![cloudhatasi](https://cloud.githubusercontent.com/assets/297968/24642814/bc5d0ce8-1912-11e7-8c41-d70efa3f6a04.png)

![ddo-hatalar](https://cloud.githubusercontent.com/assets/297968/24646592/399fe3c6-1925-11e7-8392-2bcb8cb1b642.png)

Nextcloud 11.0.2.7 (stable) - OnlyOffice Plugin 1.0.2

**Server configuration**

**Operating system:**
CentOS 7.3
**Web server:**
Apache 2.4

**Comment by emresaracoglu** [comment]
How can I solve this problem?
What do you think @JohnPerkin

**Comment by JohnPerkin** [comment]
Hello @emresaracoglu!
Please update ownCloud/Nextcloud ONLYOFFICE integration app to the latest version and then follow this 
[instruction](https://doc.owncloud.org/server/latest/admin_manual/configuration_server/logging_configuration.html) to set logs level to 0. Then send logs at support@onlyoffice.com

**Comment by emresaracoglu** [comment]
This morning I updated to latest version (1.0.2) and I retested after updating but I continue to experience the same problem.

I set logs level to 0 and I sent it to your address.
Could it be a problem with the vHost file? Because I write "**http://192.168.1.101**" instead of "**https://ofis.domain.com**", It is not a problem _(This time I encounter an SSL error)_

**Comment by LinneyS** [comment]
Could you please specify if the problem recurs or we can close the topic.

**Comment by emresaracoglu** [comment]
OnlyOffice not working on my server, because I have my problems with Nextcloud & OnlyOffice entegration. Tomorrow morning, I will write again your answer. thank you

**Comment by alexanderonlyoffice** [comment]
@emresaracoglu, could you please send us full logs to support@onlyoffice.com.

**Comment by emresaracoglu** [comment]
@BigFishC Yes, I solved.

**Comment by BigFishC** [comment]
I have the same problem.
How did you solve it?

**Comment by emresaracoglu** [comment]
I can not say that the above methods work very well for me. Therefore, I started to use HAproxy which I think is the whole container & VM is more performance for communication with each other, not only for OnlyOffice.

If you start using HAproxy or other proxy systems, I can help you better.. I do not even think you need your help with HAprpxy

**Comment by BigFishC** [comment]
Thank you all the same !
I think  i kown my problem.

**Comment by emresaracoglu** [comment]
@BigFishC 👍
