### ISSUE TITLE
Owncloud integration does not work for me.

### ISSUE THREAD

**Issue by hpl0815** [ONLYOFFICE/onlyoffice-owncloud#36]
I have two containers running on the same machine one for owncloud and one for the document server.

I started the document server with -p 8085:80. If I visit the document server via webbrowser http://ipAdress:8085 it says the service is running. But when I try to access the document server (v.4.3) via owncloud (onlyoffice integration app v. 1.0.1) I get the error "onlyoffice app not configured, please contact..."

Am I doing something wrong? From ownloud container I can ping the document server, but can not use it from owncloud.

**Comment by minh10huy** [comment]
@hpl0815 I have a same problem. Any what solution for issues?

**Comment by JohnPerkin** [comment]
Please try to update ownCloud/Nextcloud ONLYOFFICE integration app

**Comment by JohnPerkin** [comment]
Hello @hpl0815 
On the current moment is released integration app 1.0.4. Please update ownCloud/Nextcloud app and Document Server to the latest versions and tell us if it helped or did not.

**Comment by hpl0815** [comment]
Hello @JohnPerkin,

yes, with the latest version it finally works for me. 

Thanks!
