### ISSUE TITLE
"Open with" menu in ownCloud

### ISSUE THREAD

**Issue by pmaier1** [ONLYOFFICE/onlyoffice-owncloud#365]
With ownCloud Server 10.7, the "Open with" menu has been introduced. Its intention was to allow users to choose between different editor/viewer applications if more than one is available.

Up until now, the menu doesn't play well with ONLYOFFICE as ONLYOFFICE adds several entries to the menu ("Open with ONLYOFFICE", "Download as", "Convert with ONLYOFFICE" for certain file types). People are expecting that
- if there's just ONLYOFFICE available, a click on the file would directly open it (and does not display a menu)
- the "Open in ONLYOFFICE" entry will only be shown for file types ONLYOFFICE is the default application for.

So we should find a way to
1. only show the "Open in ONLYOFFICE" in the menu ("Download as" and "Convert with ONLYOFFICE" should only be shown in the three dots menu)
2. only show "Open in ONLYOFFICE" for file types where ONLYOFFICE is the default application for. If ONLYOFFICE supports a file type but is not the default application, the entry should only be shown in the three dots menu.

How can we get there? @jackermann @JammingBen @LinneyS

**Comment by LinneyS** [comment]
@pmaier1 Thanks for raising the question

Now the logic has been changed in a counter-intuitive way: https://github.com/owncloud/core/pull/38132
A pop-up menu, which appears after clicking on a file's name, has been added. It is displayed if more than one non-system action exists. And if only one user action is added, a search for the default action is initiated.

We think that an array of default actions for each file type should be implemented and displayed in the new menu. That would solve the issue with multiple default actions without displaying a wide array of additional user actions.

And various applications that add their own action as a "default action" could add to this list. And our additional actions would remain in the three dots menu.

**Comment by JammingBen** [comment]
> We think that an array of default actions for each file type should be implemented and displayed in the new menu. That would solve the issue with multiple default actions without displaying a wide array of additional user actions.

This sounds like the best solution to me as well.

Currently, the popup menu shows all registered actions, regardless of the default setting. This was initially implemented because ownCloud supports only one default action per mime type. We will change this to an array of default actions in ownCloud core. As @LinneyS already described, the popup menu will only show if more than one default action is registered.

**Comment by LinneyS** [comment]
Thank you very much for the rework.
Now it has become much more convenient and understandable to use the "Open with" menu.
