### ISSUE TITLE
Ability to connect ownCloud with OnlyOffice without using WebDAV

### ISSUE THREAD

**Issue by babonet13** [ONLYOFFICE/onlyoffice-owncloud#37]
Hello, 

When I try to connect my ownCloud account to the OnlyOffice dashboard, I got a error "The gived credentials or configuration form does not fit to the storage provider"
![owncloud_error](https://cloud.githubusercontent.com/assets/20139338/24715749/e343af86-1a2c-11e7-8302-d53c858388ea.png)
For information, the very same credential works fine for the ownCloud client for Mac and iPhone !

Thanks for help

Bernard

**Comment by JohnPerkin** [comment]
Hello @babonet13! 
It seems like connection URL is not correct. It has to look like `http://IP_or_domain_name/owncloud/remote.php/webdav/`

**Comment by babonet13** [comment]
Thanks for that help John.
Unfortunately, my web hosting provider does not support WebDAV (https://www.infomaniak.com/en/support/faq/1394/webdav-support)
Did you plan to provide a ownCloud access through another way ?
(I am thinking about the way a Mac machine, a Linux machine or a iPhone acces to ownCloud : https://owncloud.org/install/)
Best Regards
Bernard

**Comment by JohnPerkin** [comment]
Hello @babonet13!
ONLYOFFICE integration app was developed because ownCloud supports WebDAV protocol and we do not have any other solution for editing documents from ownCloud/Nextcloud using ONLYOFFICE.
Thank you for your feedback, we will take into consideration

**Comment by LinneyS** [comment]
Please duplicate this issue in https://github.com/ONLYOFFICE/CommunityServer
