### ISSUE TITLE
Error	onlyoffice	Exception: Error occurred in the document service: Error while downloading the document file to be converted.

### ISSUE THREAD

**Issue by farrukh6645** [ONLYOFFICE/onlyoffice-owncloud#375]
<html>
<body>

Error | onlyoffice | Exception: Error occurred in the document service: Error while downloading the document file to be converted./var/www/nextcloud/apps/onlyoffice/lib/documentservice.php - line 94:OCA\Onlyoffice\DocumentService->ProcessConvServResponceError()/var/www/nextcloud/apps/onlyoffice/lib/documentservice.php - line 432:OCA\Onlyoffice\DocumentService->GetConvertedUri()/var/www/nextcloud/apps/onlyoffice/controller/settingscontroller.php - line 172:OCA\Onlyoffice\DocumentService->checkDocServiceUrl()/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 217:OCA\Onlyoffice\Controller\SettingsController->SaveAddress()/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 126:OC\AppFramework\Http\Dispatcher->executeController()/var/www/nextcloud/lib/private/AppFramework/App.php - line 156:OC\AppFramework\Http\Dispatcher->dispatch()/var/www/nextcloud/lib/private/Route/Router.php - line 302:OC\AppFramework\App::main()/var/www/nextcloud/lib/base.php - line 1006:OC\Route\Router->match()/var/www/nextcloud/index.php - line 36:OC::handleRequest()
-- | -- | --

</body>
</html>

**Comment by Antipkin-A** [comment]
Hi, @farrukh6645 
Is this issue actual?

**Comment by farrukh6645** [comment]
Its sorted out
