### ISSUE TITLE
Changing the language of the GUI

### ISSUE THREAD

**Issue by mleu77** [ONLYOFFICE/onlyoffice-owncloud#38]
Hi,
is it possible to change the language of the DocumentServer (and the default Spellchecker language) e.g. to German?
I can't find any hints...

I'd also like to change the default behaviour of opening a document with right-click (like in previous owncloud app). Is this possible?

Thanks in advance!

**Comment by Gimly86** [comment]
Hi,

I have the same question about UI language, is it cool if you implement it to your nextcloud plugin, please. :).

Thanks in advance !

**Comment by LinneyS** [comment]
Fixed https://github.com/ONLYOFFICE/onlyoffice-owncloud/commit/ad6d2f62b3d59d38733219b8921acad659c6f9db
