### ISSUE TITLE
Disable plugins

### ISSUE THREAD

**Issue by Gimly86** [ONLYOFFICE/onlyoffice-owncloud#39]
Hi,

Is it possible to disable DocumentServer plugins, when we activate Onlyoffice-owncloud plugin ?

Thanks in advance for your answer ! :)

**Comment by ibnpetr** [comment]
Hello,
Just remove the content of the /var/www/onlyoffice/documentserver/sdkjs-plugins

**Comment by Gimly86** [comment]
Thank you.
