### ISSUE TITLE
Owncloud / OnyOffice connector - 502 bad gateway

### ISSUE THREAD

**Issue by perpetualwar6** [ONLYOFFICE/onlyoffice-owncloud#395]
Hi there,
I have an Owncloud running version 10.4.1 and running the latest version of OnlyOffice on a separate Ubuntu server (separate from the Owncloud server). I have followed every direction in the installation guide and integration with Owncloud and have been stuck on this issue the past day. As a side note, I can visit the URL of my OnlyOffice (example: https://onlyoffice.xxxx.com) and get all the necessary info such as: ONLYOFFICE Docs Enterprise Edition installed

I am pointing the OnlyOffice connector to my URL (no custom port, just 443) and am receiving a 502 error (bad gateway) when I save my settings in Owncloud for the app. 

I checked my certificate - everything is valid (valid til 2023). SSL Labs rated my website an A+ as well.

When I look at the logs in /var/log/onlyoffice/documentserver - there are only these errors:

2022/11/28 17:35:30 [crit] 2331447#2331447: *207 SSL_do_handshake() failed (SSL: error:0A00006C:SSL routines::bad key share) while SSL handshaking, client: 87.236.176.243, server: 0.0.0.0:443

& 

2022/11/28 19:35:58 [error] 2331447#2331447: *230 connect() failed (111: Unknown error) while connecting to upstream, client: 3.213.177.114, server: , request: "GET /healthcheck HTTP/1.1", upstream: "http://127.0.0.1:8000/healthcheck", host: "onlyoffice.xxxx.com>

Is there something I'm missing?

**Comment by GeorgeONLYOFFICE** [comment]
Hello,

The issue is being taken care of by the Support team in the ticket 37152.
