### ISSUE TITLE
Ability to connect ownCloud with OnlyOffice without using WebDAV

### ISSUE THREAD

**Issue by babonet13** [ONLYOFFICE/onlyoffice-owncloud#41]
For instance the only way to connect ownCloud with OnlyOffice is with WebDAV.
Many Web Hosting service DO NOT provide a WebDAV support ...
... so it could be very useful to have a connection mode similar than the ones used by ownCloud client (for Mac, Linux, Window ... iPhone, ....)

**Comment by JohnPerkin** [comment]
Duplicate https://github.com/ONLYOFFICE/onlyoffice-owncloud/issues/37
