### ISSUE TITLE
Change default document language

### ISSUE THREAD

**Issue by mleu77** [ONLYOFFICE/onlyoffice-owncloud#44]
Hi,
when I open a new OO-document in nextcloud the document language (also spellchecker) is by default English.
Is ist possible to change it e.g. to German? - Or even better:
Is it possible to set it automatically according to peronal settings in nextcloud?

Thanks in advance!

**Comment by JohnPerkin** [comment]
Hello @mleu77!
This option is already implemented https://github.com/ONLYOFFICE/onlyoffice-owncloud/issues/38 in the last ownCloud/Nextcloud ONLYOFFICE integration app 1.0.2. Just change language in personal settings, and ONLYOFFICE will adapt to it.

**Comment by mleu77** [comment]
Hello John,
thanks für you fast reply - great support.

Maybe you understood me wrong - I mean the behavior like shown in the screenshot below.
In every new document (generated in nextcloud app)  I have to change the document language manually e.g. to German.
![2017-04-10 14_39_58-](https://cloud.githubusercontent.com/assets/26937398/24862228/12d84298-1dfc-11e7-8361-ac0aa123c098.png)

It's really not a big issue, but maybe the solution is so simple that I can#t see it.

Regards

**Comment by JohnPerkin** [comment]
Thank you for your remark, we will improve the issue in future versions.
To solve it today you may replace files for creating documents in the folder [assets](https://github.com/ONLYOFFICE/onlyoffice-owncloud/tree/master/assets) with the files in language that you need which you can download [here](https://github.com/ONLYOFFICE/CommunityServer/tree/master/web/studio/ASC.Web.Studio/Products/Files/DocStore/newdocuments)

**Comment by vkzunited** [comment]
Hint: Onlyoffice Documentserver will not work with german user interface when you chose "Deutsch (Förmlich: Sie)". I really became crazy about this because the surface was in english all the time. If you choose "Deutsch (Persönlich)" the translation works perfect. It seems, that a second german L10N is missing.
