### ISSUE TITLE
Documentation of the new "secret key" feature 

### ISSUE THREAD

**Issue by mleu77** [ONLYOFFICE/onlyoffice-owncloud#45]
Hi,
is there a documentation of the new field "secret key" in NC admin page?
Or can you give a short hint how to use it, please?
![nc_oo](https://cloud.githubusercontent.com/assets/26937398/24850439/69a50c0e-1dd0-11e7-9ef6-e580630fc9bd.PNG)

Thanks in advance!

**Comment by JohnPerkin** [comment]
Hello @mleu77!
Documentation concerning secret keys you may see on [ONLYOFFICE API](https://api.onlyoffice.com/editors/signature/) website

**Comment by e-alfred** [comment]
How can we do this with the Docker image? Manually editing the container?

**Comment by thebuero** [comment]
Hi,
I've tried to set the secret key in default.json according to the ONLYOFFICE API website, but it doesn't seem to have an effect at all. (I've set a string for "services.CoAuthoring.secret.inbox.string" and enabled it via "services.CoAuthoring.token.enable.browser" and the other three).
Also I tried to set
`"ipfilter": {
…
}`
to restrict who can access Document-Server, again with no effect at all.
Am I editing the wrong file (/etc/onlyoffice/documentserver/default.json) or missing something else?
My setup is as follows:
Nextcloud 12.0 (stable), running on Ubuntu server 16.04
OnlyOffice integration app 1.0.4
OnlyOffice Document Server 4.3.3, running on Ubuntu server 16.04 (Manual installation according to official docs, using an ssl-cert via letsencrypt.

**Comment by JohnPerkin** [comment]
Hello @thebuero!
You may try to restart Document Server. For .deb package use the command **`supervisorctl restart all`**

**Comment by thebuero** [comment]
Hi @JohnPerkin 
Thanks for your reply. This worked – I only restarted nginx before, assuming it would reload the config. Again, Thank you very much.

**Comment by raphson93** [comment]
@thebuero 
Hi, did you replace the "secret" with the server private key?

`"secret": {
        "inbox": {
          "string": "secret",
          "file": "",
          "tenants": {}
        },
        "outbox": {
          "string": "secret",
          "file": ""
        },
        "session": {
          "string": "secret",
          "file": ""
        }
      },
      "token": {
        "enable": {
          "browser": false,
          "request": {
            "inbox": false,
            "outbox": false
          }
        },
        "inbox": {
          "header": "Authorization",
          "prefix": "Bearer "
        },
        "outbox": {
          "header": "Authorization",
          "prefix": "Bearer ",
          "algorithm": "HS256",
          "expires": "5m"
        },
`

**Comment by danielepercivaldi** [comment]
Hi.
I'm using OO Document Server 4.3.6 in docker and trying to setup secret key, but it does not work.
This is the section in default.json:

      "secret": {
        "inbox": {
          "string": "secret",
          "file": "",
          "tenants": {}
        },
        "outbox": {
          "string": "secret",
          "file": ""
        },
        "session": {
          "string": "secret",
          "file": ""
        }
      },
      "token": {
        "enable": {
          "browser": false,
          "request": {
            "inbox": false,
            "outbox": false
          }
I changed it in:

      "secret": {
        "inbox": {
          "string": "MySecret",
          "file": "",
          "tenants": {}
        },
        "outbox": {
          "string": "MySecret",
          "file": ""
        },
        "session": {
          "string": "MySecret",
          "file": ""
        }
      },
      "token": {
        "enable": {
          "browser": true,
          "request": {
            "inbox": true,
            "outbox": true
          }

And restarted services: supervisorctl restart all
But it does not work. Any suggestion?
Thank you.

**Comment by ibnpetr** [comment]
> and trying to setup secret key, but it does not work.

Could you please provide us with any additional information about the issue.

**Comment by danielepercivaldi** [comment]
Hi @ibnpetr .
Below all the information you need:

- OS: Ubuntu 14.04.5 server LTS (kernel 4.4.0-81-generic)
- Docker:
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:06:06 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:06:06 2017
 OS/Arch:      linux/amd64
 Experimental: false

- OnlyOffice Document Server Image 4.3.6 

- Changed CoAuthoring.secret section in default.json:
...
      "secret": {
        "inbox": {
          "string": "MySecret",
          "file": "",
          "tenants": {}
        },
        "outbox": {
          "string": "MySecret",
          "file": ""
        },
        "session": {
          "string": "MySecret",
          "file": ""
        }
      },
      "token": {
        "enable": {
          "browser": true,
          "request": {
            "inbox": true,
            "outbox": true
          }

- restarted services in OODS container: supervisorctl restart all

- changed configuration in ownCloud app fo OnlyOffice:
![immagine](https://user-images.githubusercontent.com/8720648/27458875-8b0f3c24-57ab-11e7-8437-ec55424e9db4.png)

- Opened a new or existent document and got the following message:
![immagine](https://user-images.githubusercontent.com/8720648/27458984-4c5b85cc-57ac-11e7-83b8-368e88d3b45e.png)

Hope it can help you.

Thanks.

**Comment by ibnpetr** [comment]
Could you please send us the log files.
ONLYOFFICE module log is included into the owncloud logs
Please [change the logging level to "0"](https://doc.owncloud.org/server/latest/admin_manual/configuration_server/logging_configuration.html%29), try opening the document and attach the result log
Also feel free to send it to support@onlyoffice.com (subject "github user")
Looking forward to hearing from you

**Comment by raphson93** [comment]
Hi, below are the following logs:

> {"reqId":"WUzqyuU5GBezuQAhXZbwDwAAAAU","level":1,"time":"June 23, 2017 18:17:46","remoteAddr":"175.143.72.221","user":"--","app":"onlyoffice","method":"POST","url":"\/index.php\/apps\/onlyoffice\/track?doc=Tnd3NytVbExYbzFSZ2ZLRTVNQ1B4M0w2TDR2Vkd2dU9PbG1FZVp1MGplVT0\/eyJmaWxlSWQiOjM5NzkxMjcsIm93bmVySWQiOiJ3ZWVsaWFuZyIsImFjdGlvbiI6InRyYWNrIn0%3D","message":"Track with empty or not correct hash: hash not equal"}
{"reqId":"WUzrSyz7zWOBgj8y-KY4pQAAAAk","level":1,"time":"June 23, 2017 18:19:55","remoteAddr":"175.143.72.221","user":"vincent","app":"onlyoffice","method":"PUT","url":"\/index.php\/apps\/onlyoffice\/ajax\/settings","message":"SetDocumentServerUrl: https:\/\/owncloud.htasia.com:7341\/"}
{"reqId":"WUzrSyz7zWOBgj8y-KY4pQAAAAk","level":1,"time":"June 23, 2017 18:19:55","remoteAddr":"175.143.72.221","user":"vincent","app":"onlyoffice","method":"PUT","url":"\/index.php\/apps\/onlyoffice\/ajax\/settings","message":"SetDocumentServerInternalUrl: https:\/\/owncloud.htasia.com:7341\/"}
{"reqId":"WUzrSyz7zWOBgj8y-KY4pQAAAAk","level":1,"time":"June 23, 2017 18:19:55","remoteAddr":"175.143.72.221","user":"vincent","app":"onlyoffice","method":"PUT","url":"\/index.php\/apps\/onlyoffice\/ajax\/settings","message":"SetStorageUrl: https:\/\/owncloud.htasia.com:7342\/"}
{"reqId":"WUzrSyz7zWOBgj8y-KY4pQAAAAk","level":1,"time":"June 23, 2017 18:19:55","remoteAddr":"175.143.72.221","user":"vincent","app":"onlyoffice","method":"PUT","url":"\/index.php\/apps\/onlyoffice\/ajax\/settings","message":"Set secret key"}
{"reqId":"WUzrSyz7zWOBgj8y-KY4pQAAAAk","level":0,"time":"June 23, 2017 18:19:55","remoteAddr":"175.143.72.221","user":"vincent","app":"onlyoffice","method":"PUT","url":"\/index.php\/apps\/onlyoffice\/ajax\/settings","message":"CommandRequest on check: {\"error\":0,\"version\":\"4.3.6.2\"}"}
{"reqId":"WUzrSyz7zWOBgj8y-KY4pQAAAAk","level":0,"time":"June 23, 2017 18:19:56","remoteAddr":"175.143.72.221","user":"vincent","app":"onlyoffice","method":"PUT","url":"\/index.php\/apps\/onlyoffice\/ajax\/settings","message":"GetConvertedUri on check: https:\/\/owncloud.htasia.com:7342\/index.php\/apps\/onlyoffice\/empty?doc=R2QrRlMxZU8yL1plSExkL2s0V1pSeVpxbmhtMFVRc3JvbXJVaTFXRzRWYz0\/eyJhY3Rpb24iOiJlbXB0eSJ9 return https:\/\/owncloud.htasia.com:7341\/cache\/files\/conv_check_2050002871_docx\/output.docx\/output.docx?md5=aVGNB4g-fUfTIRi-Bzv0nA==&expires=1500805197&disposition=attachment&ooname=output.docx"}
{"reqId":"WUzrSyz7zWOBgj8y-KY4pQAAAAk","level":1,"time":"June 23, 2017 18:19:56","remoteAddr":"175.143.72.221","user":"vincent","app":"onlyoffice","method":"PUT","url":"\/index.php\/apps\/onlyoffice\/ajax\/settings","message":"Set default formats: {\"docx\":\"true\",\"xlsx\":\"true\",\"pptx\":\"true\",\"ppsx\":\"true\",\"txt\":\"true\",\"csv\":\"true\"}"}
{"reqId":"WUzrSyz7zWOBgj8y-KY4pQAAAAk","level":1,"time":"June 23, 2017 18:19:56","remoteAddr":"175.143.72.221","user":"vincent","app":"onlyoffice","method":"PUT","url":"\/index.php\/apps\/onlyoffice\/ajax\/settings","message":"Set opening in a same tab: false"}
{"reqId":"WUzrVdhdOFU8rXc9DzKSOQAAAAo","level":1,"time":"June 23, 2017 18:20:05","remoteAddr":"175.143.72.221","user":"--","app":"onlyoffice","method":"POST","url":"\/index.php\/apps\/onlyoffice\/track?doc=Tnd3NytVbExYbzFSZ2ZLRTVNQ1B4M0w2TDR2Vkd2dU9PbG1FZVp1MGplVT0\/eyJmaWxlSWQiOjM5NzkxMjcsIm93bmVySWQiOiJ3ZWVsaWFuZyIsImFjdGlvbiI6InRyYWNrIn0%3D","message":"Track with empty or not correct hash: hash not equal"}

**Comment by raphson93** [comment]
After apply the following settings, I tested it with the following command in browser:
https://<documentserver>/coauthoring/CommandService.ashx?c=version

It returns `{"error":6}`

**Comment by danielepercivaldi** [comment]
Hi @ibnpetr .
Sorry for the delay. Working hard in the last period ...
Below the log you requested:

{"reqId":"TYfH6nKnVFw6CQ80d\/85","remoteAddr":"127.0.0.1","app":"onlyoffice","message":"Track with invalid jwt: Cannot handle token prior to 2017-06-24T16:09:37+0000","level":1,"time":"Sat, 24 Jun 2017 18:09:30 +0200","method":"POST","url":"\/index.php\/apps\/onlyoffice\/track?doc=UHl2S2JyTm1DYWpBRTUrempTd3dRMjE1ME9NcGRQOXQvSGdua1FiUnRXdz0\/eyJmaWxlSWQiOjYwMjAsIm93bmVySWQiOiJhZG1pbmlzdHJhdG9yIiwiYWN0aW9uIjoidHJhY2sifQ%3D%3D","user":"--"}
{"reqId":"gDHJwCJnkbLgPzC9EQmg","remoteAddr":"127.0.0.1","app":"onlyoffice","message":"Download with invalid jwt: Cannot handle token prior to 2017-06-24T16:09:37+0000","level":1,"time":"Sat, 24 Jun 2017 18:09:30 +0200","method":"GET","url":"\/index.php\/apps\/onlyoffice\/download?doc=NnVhM3B5dnZ3WXhvc2oxVnZtTFlHV1VaVGwxdkgzcXJrMDBxZlljc2l0ST0\/eyJmaWxlSWQiOjYwMjAsIm93bmVySWQiOiJhZG1pbmlzdHJhdG9yIiwiYWN0aW9uIjoiZG93bmxvYWQifQ%3D%3D","user":"--"}
{"reqId":"Z9HdUpQAV3sMWopDQd3m","remoteAddr":"127.0.0.1","app":"onlyoffice","message":"Download with invalid jwt: Cannot handle token prior to 2017-06-24T16:09:38+0000","level":1,"time":"Sat, 24 Jun 2017 18:09:31 +0200","method":"GET","url":"\/index.php\/apps\/onlyoffice\/download?doc=NnVhM3B5dnZ3WXhvc2oxVnZtTFlHV1VaVGwxdkgzcXJrMDBxZlljc2l0ST0\/eyJmaWxlSWQiOjYwMjAsIm93bmVySWQiOiJhZG1pbmlzdHJhdG9yIiwiYWN0aW9uIjoiZG93bmxvYWQifQ%3D%3D","user":"--"}
{"reqId":"85SffLVdTWsiqth6zvEw","remoteAddr":"127.0.0.1","app":"onlyoffice","message":"Download with invalid jwt: Cannot handle token prior to 2017-06-24T16:09:39+0000","level":1,"time":"Sat, 24 Jun 2017 18:09:32 +0200","method":"GET","url":"\/index.php\/apps\/onlyoffice\/download?doc=NnVhM3B5dnZ3WXhvc2oxVnZtTFlHV1VaVGwxdkgzcXJrMDBxZlljc2l0ST0\/eyJmaWxlSWQiOjYwMjAsIm93bmVySWQiOiJhZG1pbmlzdHJhdG9yIiwiYWN0aW9uIjoiZG93bmxvYWQifQ%3D%3D","user":"--"}

It seems to be a date / time problem, uh? I've already checked, and all the machines involved are time-synced (oc and oo are on different hosts).

Thank you.

**Comment by danielepercivaldi** [comment]
Hi.
Version 1.1.3 fixed it.

Thank you.

**Comment by danielepercivaldi** [comment]
Sorry.
Hi.
Version 1.1.3 didn't fix it.
It seems to work ONLY if client, oc and onlyoffice document server are in tha same network AND owncloud and onlyoffice document server are on the same host.
So it does not work through internet and if oc and oo are on different hosts.

Thank you.

**Comment by MarvAmBass** [comment]
seme problem here, I remember after I first used it, it was working by replacing all occurrences of "secret" with my personal secret in `/etc/onlyoffice/documentserver/default.json`.

But somehow it stopped working. I'm still able to connect with the default string 'secret' even thought it got replaced before container start in the default json

**Comment by MarvAmBass** [comment]
so I was able to get it to run. (take a look at my compose file and the Dockerfile beneath onlyoffice-documentserver @ https://github.com/ServerContainers/nextcloud)

the problem was, it seems that the

```
  "token": {
    "enable": {
      "browser": false,
      "request": {
        "inbox": false,
        "outbox": false
      }
```

denies the secret to be used. just switch those three to true and set all three secrets and it works ;)

**Comment by e-alfred** [comment]
@MarvAmBass Thanks for the hint, now everything works.

@JohnPerkin Please add this to the documentation of the security feature, it would help a lot of people dealing with problems with the "secret key".

**Comment by jkaberg** [comment]
@JohnPerkin makeing it possible to set 'secret' in environment variable on docker runtime would be optimal. Eg

```docker run .... -e secret_string=blabla onlyoffice/documentserver```

The above would run a ```sed``` (or similar) on the default.json which replaces the standard secret and changes the above mentioned values from false to true. That would make it a lot easier for everyone.

**Comment by LinneyS** [comment]
Hi @danielepercivaldi 
See the solution for different hosts https://github.com/ONLYOFFICE/DocumentServer/issues/176

**Comment by LinneyS** [comment]
There are problems with getting the **Authorization** header from ownCloud app.
Added the ability to change the header key: 9b65caeb5739c0190a4f513865a44124d16269fb

Open the **ownCloud** config file _/owncloud/config/config.php_ 
and insert a section to it:
```
'onlyoffice' => array (
    'jwt_secret' => "AuthorizationJwt"
)
```

On the **DocumentServer** side, it is possible to change the header key in _/etc/onlyoffice/documentserver/default.json_
```
{
    "services": {
        "CoAuthoring": {
            "token": {
                "inbox": {
                  "header": "AuthorizationJwt"
                },
                "outbox": {
                  "header": "AuthorizationJwt"
                }
            }
        }
    }
}
```
Restart the services for the config changes to take effect:
`supervisorctl restart all`

**Comment by enricobertoldi** [comment]
Hello @danielepercivaldi @LinneyS

**The file to be modified is not default.json but local.json.**

I wrote to Only Office Support asking them to change the guide:
https://api.onlyoffice.com/editors/signature/

**Comment by LinneyS** [comment]
ONLYOFFICE/api.onlyoffice.com@914d129b83461125b3fd911451f1371cd8f92fc5

**Comment by JensPfeifle** [comment]
It was posted above, but just to make it more clear..
The following environment variables can be set in the container to set the secret:
```
JWT_ENABLED=true
JWT_SECRET=yoursecrethere
```
JWT_HEADER can also be set.
Reference: [Added jwt params](https://github.com/ONLYOFFICE/Docker-DocumentServer/commit/ef8826aca47720339081df36eab88b3a3f9602a9)

**Comment by major-mayer** [comment]
Thanks @JensPfeifle i had many troubles setting up the document server secrets and tokens inside the default.json file, but by setting the environment variable it finally worked 😄
