### ISSUE TITLE
ownCloud 9.1.4 (stable) and OnlyOffice 1.0.2 plugin issue

### ISSUE THREAD

**Issue by Vladislav-Ilcheff** [ONLYOFFICE/onlyoffice-owncloud#46]
Hello, 

I have a weird issue with OnlyOffice app.

To be more specific: I can create documents(Document/Spreadsheet/Presentation) and after creation the document auto-opens just fine. After that there is no option to open it in OnlyOfFice in menu, but in the same time option is presented in menu of *.txt files.

Here are some example shots:
![screen shot 2017-04-13 at 02 29 09](https://cloud.githubusercontent.com/assets/27385030/24983753/e98910aa-1ff1-11e7-8bba-e083114b8002.png)
![screen shot 2017-04-13 at 02 32 36](https://cloud.githubusercontent.com/assets/27385030/24983752/e988053e-1ff1-11e7-942b-98fcb072b8ec.png)

I'm using Apache/2.4.25 and php7.0 + redis for the ownCloud installation and OnlyOffice 4.3.1.4 installed over Debian.
I can provide whatever info You may need.

**Comment by JohnPerkin** [comment]
Hello @Vladislav-Ilcheff!
The issue has already been discussed earlier https://github.com/ONLYOFFICE/onlyoffice-owncloud/issues/17
