### ISSUE TITLE
ONLYOFFICE URL is not resolveable

### ISSUE THREAD

**Issue by pthoelken** [ONLYOFFICE/onlyoffice-owncloud#480]
Hello ONLYOFFICE Team, 

I'm running ownCloud with ONLYOFFICE in the same docker-compose.yml file. All fine. I've successful integrate ONLYOFFICE container into ownCloud instance in the settings / configuration tab (https://<URL>/settings/admin?sectionid=additional), but when I click on a document like .docx the Developertools shows me the following error. 

![image](https://github.com/ONLYOFFICE/onlyoffice-owncloud/assets/12643853/0b494f91-5403-42d4-a29b-1101c761a6d2)

So far so correct (bc my owncloud container is accessable from external only by nginxproxymanager), but which kind of configuration is missing here? **onlyoffice-documentserver** is the container name which is reachable from the owncloud container but logically not from the internet / external. 

My cloud is reachable from external by nginxproxymanager with an public domain. This works pretty charm but I have the errors with the onlyoffice instance from above. 

Can anyone help here?

**Comment by igwyd** [comment]
Hello @pthoelken, docker container DNS names work inside the docker network, and not work outside - [You need an instance of ONLYOFFICE Docs that is resolvable and connectable both from ownCloud and any end clients. ONLYOFFICE Docs must be able to POST to ownCloud directly.](https://helpcenter.onlyoffice.com/integration/gettingstarted-owncloud.aspx#Requirements_block). You can use reverse proxy and virtual path for onlyoffice, we have [example ](https://github.com/ONLYOFFICE/docker-onlyoffice-owncloud/blob/master/nginx.conf)for owncloud.

**Comment by pthoelken** [comment]
Is there no security issue, when the onlyoffice instance is accessable from outside?

**Comment by igwyd** [comment]
We are constantly working to improve security our application. I recomend use [JWT settings](https://helpcenter.onlyoffice.com/integration/gettingstarted-owncloud.aspx#JWT_block) and you can enable [IPfilter](https://test-helpcenter.onlyoffice.com/ru/installation/docs-configure-ipfilter.aspx).
