### ISSUE TITLE
OnlyOffice App not configured

### ISSUE THREAD

**Issue by bullfroghrr** [ONLYOFFICE/onlyoffice-owncloud#5]
I installed only office on a separate server using docker and am able to access onlyoffice through that server.  I enabled the app in Owncloud and cloned the dir  as instructed, I then entered the ip address of the server that hosts my OnlyOffice on the admin page of owncloud. however when I try to open a doc from within owncloud it gives me a blank page with the message "ONLYOFFICE app not configured. Please contact admin"
![onlyoffice](https://cloud.githubusercontent.com/assets/25620639/22708636/aa4bae4e-ed3c-11e6-918a-83f8c3f9201f.PNG)

**Comment by ibnpetr** [comment]
Hello 

> I then entered the ip address of the server that hosts my OnlyOffice on the admin page of owncloud

Are you using http or https protocol? Please secify the address.
Wrong prefix may be a reason of this issue, we will add the validation in the next version
Looking forward to hearing from you
Best regards

**Comment by bullfroghrr** [comment]
Both my owncloud server and my onlyoffice server are using https and i am accessing both on a local network 192.168.1.15(owncloud) 192.168.1.16 (onlyoffice)
![screenshot_20170209_202001](https://cloud.githubusercontent.com/assets/25620639/22811569/36d1d072-ef05-11e6-94c6-eea870d7969c.png)

**Comment by ibnpetr** [comment]
Hello 
Please make sure that the link is available from the client pc
https://192.168.1.16/web-apps/apps/api/documents/api.js

**Comment by bullfroghrr** [comment]
Ok, that's giving me a runtime error.

**Comment by ibnpetr** [comment]
> Ok, that's giving me a runtime error.

It means that the issue isn't in an integration application, make sure that Document Server is running and available.

>  i am accessing both on a local network 192.168.1.15(owncloud) 192.168.1.16 (onlyoffice)

Could you please describe what is happening when you open the address of the Document Server in your local network.
