### ISSUE TITLE
OnlyOffice Server Running, OwnCloud can't connect

### ISSUE THREAD

**Issue by axxofreak** [ONLYOFFICE/onlyoffice-owncloud#53]
I have my ownCloud server running, and on a separate server I have OnlyOffice. When I access the OnlyOffice server by IP it says it is running. I added the IP address to my owncloud server for the address for the OnlyOffice server and it saved successfully. But when I try and open a document with Owncloud/OnlyOffice I get 
"ONLYOFFICE not reached. Please contact admin"

Is it possibly because my onlyonly office is not using SSL, while my OwnCloud Server has a SSL from lets encrypt?

**Comment by JohnPerkin** [comment]
Hello @axxofreak!
You are right, when ownCloud instance is running over https it won't work with ONLYOFFICE which is not using https. To enable SSL for Document Server installed please follow the [instruction](http://helpcenter.onlyoffice.com/server/linux/document/switch-to-https.aspx) in our helpcenter.

**Comment by JohnPerkin** [comment]
Hello @axxofreak 
Please let us know if the issue is solved.

**Comment by usr-h** [comment]
Hy,
Not use nginx and disabled ssl but not work!

**Comment by agolybev** [comment]
Hi @usr-h 
If you aren't @axxofreak and not related with him, would you submit another issue and describe you problem there? This would simplify the issue tracking.

**Comment by alexanderonlyoffice** [comment]
Hello @axxofreak, please specify if you have enabled SSL and everything works or there are any issue. 

Hello @usr-h, please specify if you have submitted a new issue and if the issue still exists. If not this ticket will be closed.

**Comment by LinneyS** [comment]
This issue was closed due to no response.
