### ISSUE TITLE
Can't open documents in owncloud - conversion always fails

### ISSUE THREAD

**Issue by tim1mw** [ONLYOFFICE/onlyoffice-owncloud#56]
Every document I try to open via owncloud just gives the error:

"Error occurred in the document server: Conversion error"

Is there any way I can get at the debugging logs so I can find out what's actually going wrong? The error message isn't very helpful.

**Comment by JohnPerkin** [comment]
Hello @tim1mw 
Please enter on your host the command `supervisorctl` and attach here screenshot of its result.

**Comment by vanjulchrist** [comment]
Hi @tim1mw  and @JohnPerkin , 
Please let me know how it has solved?

**Comment by e-alfred** [comment]
I have the same problem. I limit access to Onlyoffice using the "ip_filter" option only allowing the Nextcloud server to access Onlyoffice. It seems that conversions aren't handled directly between the Nextcloud Server and Onlyoffice, so the conversion fails with an error because the client machine is not allowed to access the Onlyoffice server directly.

**Comment by e-alfred** [comment]
I now added the root certificate to /usr/local/share/ca-certificates/ and issued update-ca-certificates and now I get this error message when trying to convert a file:
```

{"reqId":"e2oHK5ySm1TqITCdklwh","level":3,"time":"2017-07-10T13:07:56+00:00","remoteAddr":"server","user":"user","app":"PHP","method":"POST","url":"\/index.php\/apps\/onlyoffice\/ajax\/convert","message":"file_get_contents(https:\/\/server\/ConvertService.ashx): failed to open stream: HTTP request failed! HTTP\/1.1 403 Forbidden\r\n at \/var\/www\/nextcloud\/apps\/onlyoffice\/lib\/documentservice.php#187","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:54.0) Gecko\/20100101 Firefox\/54.0","version":"12.0.0.29"}
{"reqId":"e2oHK5ySm1TqITCdklwh","level":3,"time":"2017-07-10T13:07:56+00:00","remoteAddr":"server","user":"user","app":"PHP","method":"POST","url":"\/index.php\/apps\/onlyoffice\/ajax\/convert","message":"file_get_contents(https:\/\/server\/ConvertService.ashx): failed to open stream: HTTP request failed! HTTP\/1.1 403 Forbidden\r\n at \/var\/www\/nextcloud\/apps\/onlyoffice\/lib\/documentservice.php#187","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:54.0) Gecko\/20100101 Firefox\/54.0","version":"12.0.0.29"}
{"reqId":"e2oHK5ySm1TqITCdklwh","level":3,"time":"2017-07-10T13:07:56+00:00","remoteAddr":"server","user":"user","app":"PHP","method":"POST","url":"\/index.php\/apps\/onlyoffice\/ajax\/convert","message":"file_get_contents(https:\/\/server\/ConvertService.ashx): failed to open stream: HTTP request failed! HTTP\/1.1 403 Forbidden\r\n at \/var\/www\/nextcloud\/apps\/onlyoffice\/lib\/documentservice.php#187","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:54.0) Gecko\/20100101 Firefox\/54.0","version":"12.0.0.29"}
{"reqId":"e2oHK5ySm1TqITCdklwh","level":3,"time":"2017-07-10T13:07:56+00:00","remoteAddr":"server","user":"user","app":"onlyoffice","method":"POST","url":"\/index.php\/apps\/onlyoffice\/ajax\/convert","message":"GetConvertedUri: 36041460 Bad Request or timeout error","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:54.0) Gecko\/20100101 Firefox\/54.0","version":"12.0.0.29"}
```

It seems that the conversion isn't done just between the Onlyoffice server and the Nextcloud server, but this fails due to the ip_filter setting which doesn't allow the client to directly interact with the Onlyoffice server.

**Comment by victorbw** [comment]
the 'old'-file-types (*.doc, *.xls - without the x at the end) do work? actually I have the same error like you, but only with the old file-types

**Comment by LinneyS** [comment]
@e-alfred 
Please try the following:
open the **NextCloud** config file _/nextcloud/config/config.php_ 
and insert a section to it:
`'onlyoffice' => array (
    'verify_peer_off' => TRUE
)`

@tim1mw 
Try restart ONLYOFFICE Document Service:
`supervisorctl restart all`
Re-save the settings for onlyoffice in ownCloud.

**Comment by LinneyS** [comment]
This issue was closed due to no response.
