### ISSUE TITLE
Signature Data not found

### ISSUE THREAD

**Issue by raphson93** [ONLYOFFICE/onlyoffice-owncloud#57]
Hi, I have "Signature data not found" after I updated the onlyoffice app to the latest version.
What am I suppose to do ?
Thanks

@LinneyS

**Comment by JohnPerkin** [comment]
Hello @raphson93 !
Please attach a screenshot of the error.

**Comment by raphson93** [comment]
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- onlyoffice_bak
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
		- Signature data not found.
- onlyoffice
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
		- Signature data not found.

Raw output
==========
Array
(
    [onlyoffice_bak] => Array
        (
            [EXCEPTION] => Array
                (
                    [class] => OC\IntegrityCheck\Exceptions\InvalidSignatureException
                    [message] => Signature data not found.
                )

        )

    [onlyoffice] => Array
        (
            [EXCEPTION] => Array
                (
                    [class] => OC\IntegrityCheck\Exceptions\InvalidSignatureException
                    [message] => Signature data not found.
                )

        )

)

Please ignore the onlyoffice_bak

**Comment by raphson93** [comment]
@JohnPerkin 

So are we supposed to sign the app ourselves or the developer supposed to do it ?
Because inside the appinfo folder I cannot find signature.json

**Comment by JohnPerkin** [comment]
Hello @raphson93!
It is for our developers to sign the app. We will inform you as soon as it will be done.
Thank you for the interest in ONLYOFFICE.

**Comment by raphson93** [comment]
Thanks @JohnPerkin 

There is another issue.. Since I am using php5.6, I have problem to download converted file.
Log:

{"reqId":"WQmQY-pf2fz3ites@74wuwAAAAE","level":3,"time":"May 03, 2017 16:10:12","remoteAddr":"175.143.72.221","user":"vincent","app":"PHP","method":"POST","url":"\/index.php\/apps\/onlyoffice\/ajax\/convert","message":"file_get_contents(): SSL operation failed with code 1. OpenSSL Error messages:\nerror:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed at \/var\/www\/html\/owncloud\/apps\/onlyoffice\/controller\/editorcontroller.php#256"}
{"reqId":"WQmQY-pf2fz3ites@74wuwAAAAE","level":3,"time":"May 03, 2017 16:10:12","remoteAddr":"175.143.72.221","user":"vincent","app":"PHP","method":"POST","url":"\/index.php\/apps\/onlyoffice\/ajax\/convert","message":"file_get_contents(): Failed to enable crypto at \/var\/www\/html\/owncloud\/apps\/onlyoffice\/controller\/editorcontroller.php#256"}
{"reqId":"WQmQY-pf2fz3ites@74wuwAAAAE","level":3,"time":"May 03, 2017 16:10:12","remoteAddr":"175.143.72.221","user":"vincent","app":"PHP","method":"POST","url":"\/index.php\/apps\/onlyoffice\/ajax\/convert","message":"file_get_contents(https:\/\/126.32.3.150:7341\/cache\/files\/conv_19880191481784365_xlsx\/output.xlsx\/output.xlsx?md5=x8efGgK8Lo7kJcnbEhuxIQ==&amp;expires=1496391013&amp;disposition=attachment&amp;ooname=output.xlsx): failed to open stream: operation failed at \/var\/www\/html\/owncloud\/apps\/onlyoffice\/controller\/editorcontroller.php#256"}
{"reqId":"WQmQY-pf2fz3ites@74wuwAAAAE","level":3,"time":"May 03, 2017 16:10:12","remoteAddr":"175.143.72.221","user":"vincent","app":"onlyoffice","method":"POST","url":"\/index.php\/apps\/onlyoffice\/ajax\/convert","message":"Failed download converted file: https:\/\/126.32.3.150:7341\/cache\/files\/conv_19880191481784365_xlsx\/output.xlsx\/output.xlsx?md5=x8efGgK8Lo7kJcnbEhuxIQ==&expires=1496391013&disposition=attachment&ooname=output.xlsx"}

Do you have any idea to solve the ssl3 issue ?

**Comment by raphson93** [comment]
@JohnPerkin 
Hi may i know when this app will get sign ?

**Comment by JohnPerkin** [comment]
Hello @raphson93!
You may monitor it in [Changelog](https://github.com/ONLYOFFICE/onlyoffice-owncloud/blob/master/CHANGELOG.md)

**Comment by LinneyS** [comment]
signed 384e0984782be11cfae948a5418888b182366e03
