### ISSUE TITLE
Showing up as experimental on server?

### ISSUE THREAD

**Issue by FaPrivatliv** [ONLYOFFICE/onlyoffice-owncloud#6]
Hi,

When I added this app to my ownCloud server a few days ago, it wasn't showing up as "Experimental" but today it is. Has something changed in the last few days? Please let me know. Thanks.
![owncloud experimental](https://cloud.githubusercontent.com/assets/25571372/23194229/df75fcfc-f87a-11e6-8155-c3d6fd100527.png)

**Comment by ibnpetr** [comment]
Hello 
The latest changes have been made on 3 Feb. All changes have been approved exactly after their sending.
Please make sure that your ownCloud server receives correct status of the applications (the issue may be in some external network connection limitation)

**Comment by FaPrivatliv** [comment]
Please excuse my delayed response and thank you for yours. 

The issue seems to have resolved itself and these all show up, once again, as approved. The only app showing up as experimental is "Tasks." 

How do I know when there have been updates to these?

**Comment by JohnPerkin** [comment]
After publication in [App Store](https://apps.owncloud.com/content/show.php?content=174798) we submit a request in [app aproval](https://github.com/owncloud/app-approval/issues). Unfortunately we are not awared of the users' notification mechanism. Please contact ownCloud community to resolve this question.
Thank you for the interest in ONLYOFFICE.
