### ISSUE TITLE
Track with empty or not correct hash: hash not equal

### ISSUE THREAD

**Issue by jkaberg** [ONLYOFFICE/onlyoffice-owncloud#62]
I'm getting below message in the nextcloud whenever I try to open a document:

```
{"reqId":"cf+e1+Kww4CK6ftzx8Vq","remoteAddr":"10.0.0.11","app":"onlyoffice","message":"Track with empty or not correct hash: hash not equal","level":1,"time":"2017-05-11 19:50:32","method":"POST","url":"\/apps\/onlyoffice\/track?doc=WTMvRzVySVFGTjd2bVFkaEp6TTdUMlJkaUYrV3BoaVpPRGV1NUZFbmVMZz0\/eyJmaWxlSWQiOjE1OTEwLCJvd25lcklkIjoiam9lbCIsImFjdGlvbiI6InRyYWNrIn0%3D","user":"--","version":"11.0.3.2"}
```

I'm clueless as to why I get this error? I've setup Onlyoffice and Nextcloud as shown in the readme.

**Comment by raphson93** [comment]
@JohnPerkin 

Hi, this issue was also happened in owncloud 10

**Comment by e-alfred** [comment]
I have the same error if I set a secret key. If I remove it from the Onlyoffice server as well as Owncloud, everything works well. Otherwise I get a message that I can't save to the Owncloud Server from Onlyoffice.

**Comment by raphson93** [comment]
@e-alfred 

I did not set the secret key :(

**Comment by FlorianReimold** [comment]
Well, this issue exactly describes how far I got when setting up my Onlyoffice Document Server. My setup is:

Nextcloud 12.0.0 (on Ubuntu Desktop 16.04)
Onlyoffice App 1.0.4
Onlyoffice Document Server running in it's own virtual machine (Ubuntu Server 16.04.2)

All communication is HTTPS. When trying to edit any file with Onlyoffice, the log shows something like:
`{"reqId":"f9WjLwHHHfeS4JDsraRE","level":1,"time":"2017-06-03T13:12:29+00:00","remoteAddr":"192.168.56.102","user":"--","app":"onlyoffice","method":"POST","url":"\/next\/apps\/onlyoffice\/track?doc=S2xWUlJsbytjcVJQajdScThtTGpjZWc3QzJ0Z20rbnNnUzltM24yNzJXdz0\/eyJmaWxlSWQiOjEwOCwib3duZXJJZCI6ImZsb3JpYW4iLCJhY3Rpb24iOiJ0cmFjayJ9","message":"Track with empty or not correct hash: hash not equal","userAgent":"--","version":"12.0.0.29"}`

Onlyoffice displays a graphical error message saying "An error has occurred while opening the file". 

I tried to both set and remove the secret key from the Onlyoffice Nexcloud configuration and /etc/onlyoffice/documentserver/default.json. This did not have any effect on the error.

**Comment by ilvolodel** [comment]
Same here, anyone has found a solution?

**Comment by geiseri** [comment]
I too have the problem with Nextcloud 12.0.0.  I am also running the document server behind a reverse proxy in a docker container.  Does the docker need to be running SSL to work properly behind the reverse proxy?

**Comment by jhettler** [comment]
Hi all, I have the same issue, but what's really weird, in my case it is caused by changing of the onlyoffice server address in owncloud configuration. If I try to open and edit newly uploaded document, everything works fine, once I change the onlyoffice adress in OC configuration, I get the message during opening of documents. If I try to reupload the document, everything works fine again. But I can't imagine reuploading all documents.  It look like there is the old address registered somewhere with the document. Btw. I have it behind proxy as well.

**Comment by e-alfred** [comment]
I have no proxy, but enabled the docker host with SSL encryption. If I remove the secret, everything works well. If I set it, the problem reappears immediately.

**Comment by LinneyS** [comment]
@jkaberg 
Could you please specify if the problem recurs or we can close the topic.

**Comment by LinneyS** [comment]
This issue was closed due to no response.
