### ISSUE TITLE
broken documentServerUrl: slash missing

### ISSUE THREAD

**Issue by dafeer** [ONLYOFFICE/onlyoffice-owncloud#63]
After the recent plugin update to v1.0.4, its function stopped working with the following message:

> ONLYOFFICE not reached. Please contact admin

As it turns out, the users browser refused to load data from the document server `example.org`, the browser log shows:

> Security Policy: The page's settings blocked the loading of a resource at https://example.orgweb-apps/apps/api/documents/api.js

This is the same value you set in the Nextcloud admin page for the key "Document Editing Service address". The previously working value was `https://example.org`, which now needs to be `https://example.org/` (note the slash at the end).

[The documentation](https://github.com/ONLYOFFICE/onlyoffice-owncloud/blob/master/README.md#configuring-owncloudnextcloud-onlyoffice-integration-app) just states it should be `<documentserver>` without specifing that tailing slashes are required now. I'd suggest either fixing the documentation or, better, because it does not break existing setups: Implement a sane url concatination method in [`templates/editor.php:37`](https://github.com/ONLYOFFICE/onlyoffice-owncloud/blob/master/templates/editor.php#L37).

**Comment by edudele** [comment]
I'm in the same situation...
