### ISSUE TITLE
Onlyoffice 1.0.4 app not saving documents in Nextcloud

### ISSUE THREAD

**Issue by Dave-REBL** [ONLYOFFICE/onlyoffice-owncloud#64]
Nextcloud 11.0.3 (stable), running on Ubuntu server 16.04.2
OnlyOffice integration app 1.0.4
OnlyOffice Document Server 4.3.3, running on Ubuntu server 16.04.2

Updated Onlyoffice integration application from 1.02 to 1.04 when notified of the update in Nextcloud. Prior to the update this issue was not present.

**How to reproduce the issue:**
- select an office document in Nextcloud, as expected the document opens in the Onlyoffice document editor (Autosave enabled)
- make changes to the document, noting "All changes saved" message on the Onlyoffice status bar
- click on "Go to Documents", as expected the Onlyoffice document editor exits and the originating Nextcloud page is displayed
- note that the document modification date and size are unchanged in Nextcloud, refreshing the page does not change this information
- select the document again in Nextcloud, note that the document contains recent changes (as if the changes have been saved)
- download the document and open with a desktop document editor, note that the document has not been changed
- the following error is logged in /var/log/onlyoffice/documentserver/docservice/out.log

[2017-05-14 12:08:05.321] [ERROR] nodeJS - sendServerRequest error: docId = 1152914932415221;url = https://nnn.nnn.nnn.nnn/index.php/apps/onlyoffice/track?doc=bjg4aVFLa01hT3NPaHhSOXlRd1JaK0RKZ0pVS3loZFQyeE9kU0o5dlNOZz0/eyJmaWxlSWQiOjExNTI5LCJvd25lcklkIjoiZGJ1Y2siLCJhY3Rpb24iOiJ0cmFjayJ9;data = {"key":"1152914932415221","status":2,"url":"https://onlyoffice.abc.com/cache/files/1152914932415221_2847/output.docx/output.docx?md5=c92akR2439A9rTK8xK1NYA==&expires=1497380886&disposition=attachment&ooname=output.docx","changesurl":"https://onlyoffice.abc.com/cache/files/1152914932415221_2847/changes.zip/changes.zip?md5=O6TLkHjqRlC5063y2n1zNQ==&expires=1497380886&disposition=attachment&ooname=output.zip","history":{"serverVersion":"4.3.3","changes":[{"created":"2017-05-14 19:02:25","user":{"id":"user","name":"user"}}]},"users":["user"],"actions":[{"type":0,"userid":"user"}],"lastsave":"2017-05-14T19:02:27.907Z","notmodified":false}
Error: Error response: statusCode:400 ;body:
{"error":1}
    at Request._callback (/var/www/onlyoffice/documentserver/server/Common/sources/utils.js:260:18)
    at Request.self.callback (/var/www/onlyoffice/documentserver/server/Common/node_modules/request/request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/var/www/onlyoffice/documentserver/server/Common/node_modules/request/request.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/var/www/onlyoffice/documentserver/server/Common/node_modules/request/request.js:1091:12)
    at IncomingMessage.g (events.js:292:16)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)

**Comment by JohnPerkin** [comment]
Hello @Dave-REBL !
We tried to reproduce the issue but everything worked well. Please follow this [instruction](https://doc.owncloud.org/server/latest/admin_manual/configuration_server/logging_configuration.html) to set NextCloud's logs level to 0. Then attach logs here or send them at support@onlyoffice.com

**Comment by Dave-REBL** [comment]
Hello,

Please see the attached file containing the errors that are logged by Nextcloud when exiting the Onlyoffice document editor. Seems to be something related to SSL certificate, not sure what I’m missing here.

Thanks for your quick response on this.

Regards,
Dave

**Comment by e-alfred** [comment]
I have the same problem after upgrading to 1.0.4 on Owncloud 9.1. A warnung shows up after loading a file showing 

> "The document could not be saved. Please check connection settings or contact your administrator. When you click the OK button, you will be prompted to download the document." 

After this, a menu opens to save the file locally. Interestingly, if I change something in the document,  it still gets autosaved and I can see the changes after I reopen the document (but the warning shows up every time). Interestingly, in Owncloud the date doesn't change after the changes are made, so was the document even uploaded to Owncloud after Onlyoffice showed that it would do an autosave?

**Comment by thebuero** [comment]
Hi,
I have the very same issue as described above. (including that when the warning is dismissed, I can work on the file as normal). Newly created files work fine.
Setup is basically the same as above:
Nextcloud 12.0 (stable), running on Ubuntu server 16.04
OnlyOffice integration app 1.0.4
OnlyOffice Document Server 4.3.3, running on Ubuntu server 16.04 (Manual installation according to official docs [here](https://helpcenter.onlyoffice.com/de/server/linux/document/linux-installation.aspx) using an ssl-cert via letsencrypt.

**Comment by t7ko** [comment]
Hi,
The issue is still present in our installation, even after we've updated OnlyOffice to the latest a couple of weeks ago.

**Comment by 5n41d3r** [comment]
Hello I have the same problem for a long time, I have already updated and revised the configuration several times and as the onlyoffice web indicates, but the files edited in nextcloud that go to onlyoffice remain in the onlyoffice cache and when nextcloud download are empty.

In that case, I don't know what to do because if I don't know if changing the configuration will save those files that are cached to the original in nextcloud or lost?

I have the same ssl certificate installed on nextcloud and onlyoffice but with subdomains; cloud.example.com and docs.example.com

these are the versions I have installed:

Nextcloud 11.0.5 (stable)
OnlyOffice integration app 1.1.4
Onlyoffice-documentserver 4.3.6-2

**Comment by utahbmxer** [comment]
I had a similar issue with OnlyOffice running HTTPS in docker.  Noticed the verification error in nextcloud.log.

I am using certs from Lets Encrypt and only copied the server cert and key into the DocumentServer/data/certs/ folder for the container.  I appended chain.pem to the onlyoffice.crt file so there is two certs in the file.  After restarting the container I was able to save documents without issue.

Works without having to disable verification.  Just thought I would share.

**Comment by LinneyS** [comment]
@Dave-REBL 
Could you please specify if the problem recurs or we can close the topic.

**Comment by Dave-REBL** [comment]
@LinneyS 
Please close the topic - moved on to OnlyOffice integration app 1.2.0 running on Nextcloud 12.0.5. Working well for me. Thanks!

**Comment by soneji** [comment]
Hi
I am still having this issue
