### ISSUE TITLE
Proxy & SSL with Nextcloud

### ISSUE THREAD

**Issue by emresaracoglu** [ONLYOFFICE/onlyoffice-owncloud#65]
Hello,

I have not been able to solve this problem for a few months.

Structure:
![adsiz-1 fw](https://cloud.githubusercontent.com/assets/297968/26063724/8222c8d8-3997-11e7-8bc2-a364360f923c.png)

# Method 1 Without SSL

CWP vHost File (for words.XXXX.com)
```
<VirtualHost 10.0.0.60:80>
ServerName words.XXXX.com
ServerAlias www.words.XXXX.com
ServerAdmin hello@XXXX.com
DocumentRoot "/home/XXXX/public_html/Words"
ScriptAlias /cgi-bin/ /home/XXXX/public_html/Words/cgi-bin/

# Include "/usr/local/apache/conf/userdata/XXXX/words.XXXX.com/*.conf
<IfModule mod_suexec.c>
        SuexecUserGroup XXXX XXXX
</IfModule>

<IfModule mod_suphp.c>
        suPHP_UserGroup XXXX XXXX 
</IfModule>

ProxyPass / http://10.0.0.61/
ProxyPassReverse / http://10.0.0.61/

</VirtualHost>
```

OnlyOffice vHost File:

```
include /etc/nginx/includes/onlyoffice-http.conf;
server {
  listen 0.0.0.0:80;
  listen [::]:80 default_server;
  server_name words.XXXX.com;
  server_tokens off;

  include /etc/nginx/includes/onlyoffice-documentserver-*.conf;

  location ~ /.well-known/acme-challenge {
        root /var/www/onlyoffice/;
        allow all;
  }
}
```

**Resut:** 
Screen:

> 302 Error - nginx

Consol:

> Mixed Content: The page at 'https://XXXX.com/apps/onlyoffice/258994' was loaded over HTTPS, but requested an insecure resource 'http://words.XXXX.com/2017-04-26-13-21/web-apps/apps/documenteditor/mai…dc=2017-04-26-13-21&lang=en&customer=ONLYOFFICE&frameEditorId=iframeEditor'. This request has been blocked; the content must be served over HTTPS.

# Method 2 With SSL

CWP vHost File (for words.XXXX.com) - No any change
```
<VirtualHost 10.0.0.60:80>
ServerName words.XXXX.com
ServerAlias www.words.XXXX.com
ServerAdmin hello@XXXX.com
DocumentRoot "/home/XXXX/public_html/Words"
ScriptAlias /cgi-bin/ /home/XXXX/public_html/Words/cgi-bin/

# Include "/usr/local/apache/conf/userdata/datarals/words.XXXX.com/*.conf
<IfModule mod_suexec.c>
        SuexecUserGroup XXXX XXXX
</IfModule>

<IfModule mod_suphp.c>
        suPHP_UserGroup XXXX XXXX 
</IfModule>

ProxyPass / http://10.0.0.61/
ProxyPassReverse / http://10.0.0.61/

</VirtualHost>
```

OnlyOffice vHost File: **(with Let's Encrty/SSL successful)**

```
include /etc/nginx/includes/onlyoffice-http.conf;
## Normal HTTP host
server {
  listen 0.0.0.0:80;
  listen [::]:80 default_server;
  server_name words.XXXX.com;
  server_tokens off;
  ## Redirects all traffic to the HTTPS host
  root /nowhere; ## root doesn't have to be a valid path since we are redirecting
  rewrite ^ https://$host$request_uri? permanent;
}
#HTTP host for internal services
server {
  listen 127.0.0.1:80;
  listen [::1]:80;
  server_name localhost;
  server_tokens off;
  include /etc/nginx/includes/onlyoffice-documentserver-common.conf;
  include /etc/nginx/includes/onlyoffice-documentserver-docservice.conf;
}
## HTTPS host
server {
  listen 0.0.0.0:443 ssl;
  listen [::]:443 ssl default_server;
  server_name words.XXXX.com;
  server_tokens off;
  root /usr/share/nginx/html;
  
  ssl_certificate /etc/letsencrypt/live/words.XXXX.com/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/words.XXXX.com/privkey.pem;
 
  ssl_ciphers "ECDHE-RSA-AES128-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA128:DHE-RSA-AES128-GCM-SHA384:DHE-RSA-AES128-GCM-SHA128:ECDHE-RSA-AES128-SHA384:ECDHE-RSA-AES128-SHA128:ECDHE-RSA-AES128-SHA:ECDHE-RSA-AES128-SHA:DHE-RSA-AES128-SHA128:DHE-RSA-AES128-SHA128:DHE-RSA-AES128-SHA:DHE-RSA-AES128-SHA:ECDHE-RSA-DES-CBC3-SHA:EDH-RSA-DES-CBC3-SHA:AES128-GCM-SHA384:AES128-GCM-SHA128:AES128-SHA128:AES128-SHA128:AES128-SHA:AES128-SHA:DES-CBC3-SHA:HIGH:!aNULL:!eNULL:!EXPORT:!DES:!MD5:!PSK:!RC4";
  ssl_protocols  TLSv1 TLSv1.1 TLSv1.2;
  ssl_session_cache  builtin:1000  shared:SSL:10m;
  ssl_prefer_server_ciphers   on;
  add_header Strict-Transport-Security max-age=31536000;
  # add_header X-Frame-Options SAMEORIGIN;
  add_header X-Content-Type-Options nosniff;
  
  # ssl_stapling on;
  # ssl_stapling_verify on;
  # ssl_trusted_certificate /etc/nginx/ssl/stapling.trusted.crt;
  # resolver 208.67.222.222 208.67.222.220 valid=300s; # Can change to your DNS resolver if desired
  # resolver_timeout 10s;
  ## [Optional] Generate a stronger DHE parameter:
  ##   cd /etc/ssl/certs
  ##   sudo openssl dhparam -out dhparam.pem 4096
  ##
  #ssl_dhparam {{SSL_DHPARAM_PATH}};

  location ~ /.well-known/acme-challenge {
     root /var/www/onlyoffice/;
     allow all;
  }
  include /etc/nginx/includes/onlyoffice-documentserver-*.conf;
}
```

**Resut:** 
Screen:

> ONLYOFFICE not reached. Please contact admin

Consol:

> Refused to load the script 'https://10.0.0.61/web-apps/apps/api/documents/api.js' because it violates the following Content Security Policy directive: "script-src 'self' https://words.XXXX.com/ 'unsafe-inline' 'unsafe-eval'".

How can I solve this? 
Thank you

cc @JohnPerkin and @LinneyS

**Comment by agolybev** [comment]
Hello,
In the first case, the error occurs cause the NextCloud works through the https protocol, and the ONLYOFFICE DocumentServer works through http, and this is not permissible. Both services must use the same protocols.

In the second case, the document server works using https but request is proxeed by http.

I recommend that you configure https in Apache as well as for NextCloud.

In addition, you need to add the X-Forward-Host and X-Forward-Proto headers with the values word.xxxx.com and https and provide proxying websocket trafic. You can see similar example config for httpd(Apache) server [here](https://github.com/ONLYOFFICE/document-server-proxy/tree/master/apache).

**Comment by emresaracoglu** [comment]
Hello @agolybev 
Thank you for your answer

I made the following changes my server but I have not made any changes for ONLYOFFICE Document Server vHost file with SSL method.

CWP vHost File:
```
<VirtualHost 10.0.0.16:8181>
ServerName words.xxxxx.com
ServerAlias www.words.xxxxx.com
ServerAdmin hello@xxxxx.com
DocumentRoot "/home/xxxxx/public_html/_SubDomains/Words"
ScriptAlias /cgi-bin/ /home/xxxxx/public_html/_SubDomains/Words/cgi-bin/

#Custom settings are loaded below this line (if any exist)
#Include "/usr/local/apache/conf/userdata/xxxxx/words.xxxxx.com/*.conf

<IfModule mod_suexec.c>
        SuexecUserGroup xxxxx xxxxx
</IfModule>

<IfModule mod_suphp.c>
        suPHP_UserGroup xxxxx xxxxx
</IfModule> 

Define VPATH /
Define DS_ADDRESS 10.0.0.61

<Location ${VPATH}>
  Require all granted
  SetEnvIf Host "^(.*)$" THE_HOST=$1
  RequestHeader setifempty X-Forwarded-Proto http
  RequestHeader setifempty X-Forwarded-Host %{THE_HOST}e
  RequestHeader edit X-Forwarded-Host (.*) $1${VPATH}
  ProxyAddHeaders Off
</Location>

ProxyPassMatch ^\${VPATH}(.*)(\/websocket)$ "ws://${DS_ADDRESS}/$1$2"
ProxyPass ${VPATH} "http://${DS_ADDRESS}/"
ProxyPassReverse ${VPATH} "http://${DS_ADDRESS}/"

</VirtualHost>
# vhost_end words.xxxxx.com
```

**Result:**
Screen:
> ONLYOFFICE not reached. Please contact admin

Consol:
> GET https://words.xxxx.com/web-apps/apps/api/documents/api.js net::ERR_TOO_MANY_REDIRECTS
#
When I try to access this adrese directly I get this error:
> GET https://words.datarals.com/ net::ERR_TOO_MANY_REDIRECTS

**Comment by agolybev** [comment]
I'm not sure that the VPATH may be just /
For http proxing try this from minimal.conf:
```
...
SetEnvIf Host "^(.*)$" THE_HOST=$1
RequestHeader setifempty X-Forwarded-Proto http
RequestHeader setifempty X-Forwarded-Host %{THE_HOST}e
ProxyAddHeaders Off

ProxyPassMatch (.*)(\/websocket)$ "ws://10.0.0.61/$1$2"
ProxyPass / "http://10.0.0.61/"
ProxyPassReverse / "http://10.0.0.61/"
...
```

**Comment by emresaracoglu** [comment]
When I update the OO server file `(/etc/nginx/conf.d/onlyoffice-documentserver.conf)`, it directs the domain name to the IP address.
For example: 

`https://words.xxx.com => http://10.0.0.61`

This routing is only; It only happens when I change the OnlyOffice file for SSL..
If I use OnlyOffice file, routing is not occurring.

I think I can't fix this problem

**Comment by agolybev** [comment]
Hello @emresaracoglu
Redirection to `10.0.0.61` occurs because the document server generates links to internal resources based on the name of the server and the protocol to which the request is made. In your case, requests form a proxy server to the address `10.0.0.61` using the `http` protocol. For the correct work of the document server, in this case, `X-Forward-Host` and `X-Forward-Proto` header with proxy server name and protocol must be added to the proxy request. To setup this headers to `words.xxx.com` and `https` value you can use this directives:
```
...
RequestHeader set X-Forwarded-Proto https
RequestHeader set X-Forwarded-Host words.xxx.com
ProxyAddHeaders Off
...
```
Additional I provide  [sample config](https://github.com/ONLYOFFICE/document-server-proxy/blob/master/apache/proxy-https-to-http.conf) for Apache server to proxy web trafic from https to http.

**Comment by emresaracoglu** [comment]
@agolybev !!

I say this with all my heart; I had no hope and I think I can not do that.. 
This code with worked!
```
RequestHeader set X-Forwarded-Proto https
RequestHeader set X-Forwarded-Host words.xxx.com
ProxyAddHeaders Off
```
I've done it on your help Alexey & I saw the OnlyOffice panel! **Thank you most sincerely**

**Comment by emresaracoglu** [comment]
I got this error, did I do something missing?

![fireshot screen capture 019 - datarals _ verinin guvenli saklama noktasi - datarals_com_apps_onlyoffice_258754](https://cloud.githubusercontent.com/assets/297968/26152187/8cfb9514-3b0e-11e7-8a27-618cd7e0351a.png)

**Comment by agolybev** [comment]
It seem like `10.0.0.61` server can't resolve `xxxx.com` name or havn't access to it. 
If both servers are on the same network you can setup local network communication.
How to do this see [here](https://api.onlyoffice.com/editors/owncloud#settings)
Your settings should look like this:
![admin - owncloud - mozilla firefox 2017-05-17 14 50 17](https://cloud.githubusercontent.com/assets/8861642/26152876/92a5a68c-3b11-11e7-9e0d-38baf0f1e378.png)

**Comment by emresaracoglu** [comment]
I have tried many times and unfortunately continue to get the same mistake. _(As I cleaned the cache)_

![oo1](https://cloud.githubusercontent.com/assets/297968/26154976/4ce7be60-3b1a-11e7-9a90-282762632e00.png)

**Comment by agolybev** [comment]
Could you check http access form document server `10.0.0.61` to Nextcloud server `10.0.0.60`?
May be the access to  Nextcloud server not allowed for `10.0.0.61` server or Nextcloud service is binded to a specific name, and  does not handle all incomming requests.

**Comment by emresaracoglu** [comment]
No problem with IPs, I checked.
I noticed something; some Word files don't open and this error appears in the console.
Could this be a bug of plugin?
![oo3](https://cloud.githubusercontent.com/assets/297968/26160304/8d70e678-3b29-11e7-996f-579b9abaa5ac.png)

_I don't want to take your time too much, after that you can't spend your time for this. Because this problem is caused by my bad configuration and I will not give up any more, I will try to solve this :) You are very helpful to me. 
Thanks again for your help._

**Comment by emresaracoglu** [comment]
I deleted the OnlyOffice settings in Nextcloud and I only wrote the OnlyOffice server address.
I've had no problems when I reset the server.
Thank you for again!
