### ISSUE TITLE
onlyoffice v. 1.0.3 not update v. 1.0.4

### ISSUE THREAD

**Issue by pvl-e** [ONLYOFFICE/onlyoffice-owncloud#66]
Hi!It's update notification onlyoffice click update to 1.0.4.I go back into the app,but onlyoffice again asks to update.
![default](https://cloud.githubusercontent.com/assets/28727870/26099497/923920e0-3a33-11e7-958b-dfc37612a969.PNG)

**Comment by JohnPerkin** [comment]
Hello @pvl-e!
Enter the ownCloud's directory (by default it's **/var/www/owncloud**) and run the following command:
`chown -R www-data:www-data apps`
Please let us know if it helps and we will bring corrections to the application.

**Comment by pvl-e** [comment]
Yes,thank you.
![default](https://cloud.githubusercontent.com/assets/28727870/26115215/022dfc2a-3a68-11e7-9228-59db5be3ceb6.PNG)
![default](https://cloud.githubusercontent.com/assets/28727870/26115261/2615d14e-3a68-11e7-9c92-9343b6f1534b.PNG)

**Comment by pvl-e** [comment]
Changes noticed as soon as onlyoffice no longer open,maybe the link changes when you update to add in the description?
![default](https://cloud.githubusercontent.com/assets/28727870/26127130/eb9d180a-3a90-11e7-80fa-f8b4f5ffe3dd.PNG)
Old files are now not editable?
![1](https://cloud.githubusercontent.com/assets/28727870/26127158/09413120-3a91-11e7-8ff6-f34ec82e6ba0.PNG)

**Comment by JohnPerkin** [comment]
Hello @pvl-e 
Please check if your problem is related to the issue #63

**Comment by pvl-e** [comment]
Yes,but I'm also wondering about the availability of editing a document created before the update?

**Comment by LinneyS** [comment]
@pvl-e 
The problem with the update process was resolved by the changing of rights. Therefore, I close this request.
The problem with editing files created before the update repeated? If so, create a new issue
