### ISSUE TITLE
Can't open files through NextCloud

### ISSUE THREAD

**Issue by progressguide** [ONLYOFFICE/onlyoffice-owncloud#67]
I have my NextCloud integrated with OnlyOffice. When I try to create a new file or open an existing file in NextCloud, it will redirect me to my OnlyOffice server to open the file. But the file will not open. I get a popup error saying "Error Download Failed". What could be wrong?

**Comment by emresaracoglu** [comment]
Do you get an error message about `Content Security Policy`?

**Comment by progressguide** [comment]
No, all I get is one pop up window that says "Error Download Failed". I'm not sure where to look for error logs either. This is a pretty fresh installation too. I didn't do any modifications but I still get this message. It was working fine before, but a few days later this error started showing up for all my files.

**Comment by JohnPerkin** [comment]
Hello @progressguide!
The error with pop-up window "Download failed" is displayed when the link to the document is inaccessible from document editors. Please describe in details how did you connect Document Server to NextCloud. 
Update ownCloud/Nextcloud ONLYOFFICE integration app to the latest version and then follow this 
[instruction](https://doc.owncloud.org/server/latest/admin_manual/configuration_server/logging_configuration.html) to set logs level to 0. Then post logs here or send at support@onlyoffice.com

**Comment by LinneyS** [comment]
@progressguide 
Could you please specify if the problem recurs or we can close the topic.

**Comment by progressguide** [comment]
Apologies, our host provider fixed this for us. Not sure what they did, thank you!
