### ISSUE TITLE
Open in ONLYOFFICE formats odt ods

### ISSUE THREAD

**Issue by pvl-e** [ONLYOFFICE/onlyoffice-owncloud#69]
Hi!
Installed onlyoffice document server on a separate virtual machine for ubuntu 16.04
Integrated with Nextcloud via github.
Set up https.
Replaced the port from 443 to 4411.
It works,but gives an error when you open odt files,. ods using open in ONLYOFFICE Bad Request or timeout error.
Logging in nextcloud the following:
Error onlyoffice GetConvertedUri: 194 Bad Request or timeout error
Error PHP file_get_contents(https://office.company.ru:4411/ConvertService.ashx): failed to open stream: Connection refused at /usr/share/nginx/nextcloud/apps/onlyoffice/lib/documentservice.php#187 a minute ago
Error PHP file_get_contents(https://office.company.ru:4411/ConvertService.ashx): failed to open stream: Connection refused at /usr/share/nginx/nextcloud/apps/onlyoffice/lib/documentservice.php#187 a minute ago
Error PHP file_get_contents(https://office.company.ru:4411/ConvertService.ashx): failed to open stream: Connection refused at /usr/share/nginx/nextcloud/apps/onlyoffice/lib/documentservice.php#187 a minute ago

**Comment by LinneyS** [comment]
Please try the following:
open the **NextCloud** config file _/nextcloud/config/config.php_ 
and insert a section to it:
`'onlyoffice' => array (
    'verify_peer_off' => TRUE
)`

**Comment by LinneyS** [comment]
Could you please specify if the problem recurs or we can close the topic.
