### ISSUE TITLE
Archive does not contain a directory named onlyoffice - ownCloud

### ISSUE THREAD

**Issue by gr00byuk** [ONLYOFFICE/onlyoffice-owncloud#7]
When I'm trying to enable add-on in "Productivity" section, I see an info: "Archive does not contain a directory named onlyoffice". ownCloud version: 9.1.4.

**Comment by ibnpetr** [comment]
Hello
Please note that ownCloud ONLYOFFICE integration app should be placed into the apps/onlyoffice
`cd apps/
git clone https://github.com/ONLYOFFICE/onlyoffice-owncloud.git onlyoffice`
You probably used other folder name or default folder "onlyoffice-owncloud" has been created (just rename the folder to "onlyoffice")

**Comment by JohnPerkin** [comment]
Hello @dafeer 
In the release of the last version we took into consideration your remark on Tarbomb. The current .zip-file contains a subdirectory 'onlyoffice'.
Thank you for the interest in our product.

**Comment by dafeer** [comment]
Thanks, it works. The installation via the ownCoud-internal app manager does not throw errors anymore.

Confirmed for (SHA1) `9943d825078f905d331005295d4c1cebc3418406  174798-onlyoffice.zip`
