### ISSUE TITLE
An error has occured while opening the file - owncloud/onlyoffice (Centos 7, Owncloud 9, Mysql

### ISSUE THREAD

**Issue by vanjulchrist** [ONLYOFFICE/onlyoffice-owncloud#70]
Hi All,
Sorry for my bad english before..

I wanted to integrate my owncloud 9 with onlyoffice. I've installed onlyoffice-documentserver according to this link [here](https://helpcenter.onlyoffice.com/de/server/linux/document/linux-installation-centos.aspx).

I've configured "ONLYOFFICE Document Service Location server" on owncloud onlyoffice settings with

```
- Document Editing Service address = https://<my-documentserver-address>:443/

- Document Editing Service address for internal requests from the server = http://<my-documentserver-address>:8000/

- Server address for internal requests from the Document Editing Service = <blank>

- Secret = <blank>
```

After save that, i tried to open file like test.docx.
I was happy for seeing the view of onlyoffice but show error already like " 📛 An error has occured while opening the file 📛  ".

Please, any suggestion for giving me "light in the dark" for this case 😢 😢 😭 ??

Thanks

**Comment by JohnPerkin** [comment]
Hello @vanjulchrist!
Please describe the issue more detailed. For example, does it occur when you open documents in your internal network or from outbound client.
Update ownCloud/Nextcloud ONLYOFFICE integration app to the latest version and then follow this 
[instruction](https://doc.owncloud.org/server/latest/admin_manual/configuration_server/logging_configuration.html) to set logs level to 0. Then post logs here or send at support@onlyoffice.com

**Comment by LinneyS** [comment]
Could you please specify if the problem recurs or we can close the topic.

**Comment by vishalv26** [comment]
same.. any update or resolution?

**Comment by LinneyS** [comment]
This issue was closed due to no response.

**Comment by SuperKenVery** [comment]
Maybe you should check your ip settings in owncloud > settings > admin > additional

Is the ip of onlyoffice docs correct?
