### ISSUE TITLE
Nextcloud 12's new editable public links should open docs with OnlyOffice

### ISSUE THREAD

**Issue by steampoweredlawngnome** [ONLYOFFICE/onlyoffice-owncloud#71]
Nextcloud 12 now allows public link shares to be writable, so that a user can share a document with a non-Nextcloud user and have them jump into the editor. This functionality is advertised for use with Collabora/CODE, but I imagine OnlyOffice could use it as well.

**Comment by JohnPerkin** [comment]
Hello @steampoweredlawngnome 
The issue has already been discussed earlier https://github.com/ONLYOFFICE/onlyoffice-owncloud/issues/20
