### ISSUE TITLE
Password Protected Documents

### ISSUE THREAD

**Issue by raphson93** [ONLYOFFICE/onlyoffice-owncloud#72]
@JohnPerkin 

When I uploaded a password protected document, it will prompt me to input the password for first attempt.
When I opened the document again it no longer prompt me the password again (it happened when I shared the files to other users).

So I want to know whether this consider an security issue or not since it will overwrite my password protected documents.

**Comment by reneglauser** [comment]
I have the same problem. When I open a password protected file, the password pretection is removed, when the file is saved from openoffice.

**Comment by ShockwaveNN** [comment]
Duplicate of https://github.com/ONLYOFFICE/DocumentServer/issues/171
