### ISSUE TITLE
Add OCC command for adding URL for Nextcloud

### ISSUE THREAD

**Issue by enoch85** [ONLYOFFICE/onlyoffice-owncloud#75]
In Collabora you type `sudo -u www-data /var/www/nextcloud/occ config:app:set richdocuments wopi_url --value="https://collabora.domain.com"` to add the URL in admin settings. It would be nice if the same thing would be possible for OnlyOffice.

Something like: `sudo -u www-data /var/www/nextcloud/occ config:app:set onlyoffice serverurl --value="https://onlyoffice.domain.com"`

This would work on ownCloud as well.

**Comment by LinneyS** [comment]
Thank you, we are already trying to use it at ONLYOFFICE/docker-onlyoffice-owncloud@a6f750e2747e18dc51d7fcf8906018f8395481d2

9c0d4c88cb076d5583f5bfd2c3bc31ac3379f8e3

**Comment by enoch85** [comment]
So what's the command to use?

**Comment by LinneyS** [comment]
` sudo -u www-data php occ config:app:set onlyoffice DocumentServerUrl --value="https://onlyoffice.domain.com"`

**Comment by enoch85** [comment]
Thank you very much!
