### ISSUE TITLE
Document cannot be saved error message on Nextcloud 11.0.3

### ISSUE THREAD

**Issue by greavette** [ONLYOFFICE/onlyoffice-owncloud#76]
Hello,

I've installed onlyoffice on CenOS 7 successfully in my testing of onlyoffice.  I was able to successfully load in my SSL Certs and see the onlyoffice welcome page.  These are the instructions I used to install onlyoffice on CentOS
https://helpcenter.onlyoffice.com/server/linux/document/linux-installation-centos.aspx

I'm having trouble using my onlyoffice in my Nextcloud in that I receive the following warning message:

> The document could not be saved.  Please check connection settings or contact your Administrator. 

I've seen other have similar issues but I've not seen specifics on how to fix it.  Here is more detail for you on my setup:

- I'm using Nextcloud 11.0.3 and I've added in the onlyoffice App 1.0.4.  
- I port forward my onlyoffice server through my router in order leave my network.  My A record has been created at my ISP and I'm able to confirm that my ssl cert is good.
- Here are the settings I've updated in my Nextcloud Admin panel (I've modified the exact sitename for privacy reasons):
- Document Editing Service address Advanced server settings
 `https://onlyoffice.mycomp.ca:9443`
- Document Editing Service address for internal requests from the server
 `https://onlyoffice.mycomp.ca`
- Server address for internal requests from the Document Editing Service
 `<I've left this field blank in my Admin settings>`
- Using the above setup I get a message that 'Settings have been saved successfully'. 
- I open my Files and I try to open a .docx file.  A new tab opens and onlyoffice begins to load.  But I then receive this warning message:

> The document could not be saved.  Please check connection settings or contact your Administrator.  

What do I need to update either on my onlyoffice or my Nextcloud to allow onlyoffice to save this document in my documents location on Nextcloud?  It seems that onlyoffice thinks it can't save the document on Nextcloud?

Thank you.

**Comment by greavette** [comment]
Looking at other issues I found one closed.  Perhaps @JohnPerkin can look at my issue and provide me direction on what I need to do.  

I've run the following wget command and this is the results:

wget https://onlyoffice.mycomp.ca/index.php/apps/onlyoffice/track
--2017-06-01 17:23:26--  https://onlyoffice.mycomp.ca/index.php/apps/onlyoffice/track
Resolving onlyoffice.mycomp.ca (onlyoffice.mycomp.ca)... 10.101.1.103
Connecting to onlyoffice.mycomp.ca (onlyoffice.mycomp.ca)|10.101.1.103|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2017-06-01 17:23:26 ERROR 404: Not Found.

**Comment by greavette** [comment]
Quick update on this issue...

Seems now that when I receive this error message I can click OK and then I can edit the file afterall and save my changes.

Why am I receiving this error message then if I can edit and save the file?

Thank you.

**Comment by greavette** [comment]
I've now updated my Nextcloud to version 12 and I've applied the Nextcloud onlyoffice app update to 1.0.5.  The problem still persists and I still receive the warning message that my file cannot be saved.  yet when I click OK my file comes up in onlyoffice and I can edit the file and save it.

I found this comment in another issue:

I think I had a similar problem, use apache2 as proxy, disabling HTTPS2.0 with
Protocols http/1.1
in the <VirtualHost> section of Onlyoffice solved the Problem for me.

Where do I make this change to <VirtualHost> section of OnlyOffice?  What file do I change and on what server..OnlyOffice server or Nextcloud?

Thank you.

**Comment by JohnPerkin** [comment]
Hello @greavette 
You may try to specify address of NextCloud instance in the field 'Server address for internal requests from the Document Editing Service'.
If that does not help follow this [instruction](https://doc.owncloud.org/server/latest/admin_manual/configuration_server/logging_configuration.html) to set logs level to 0. Then post logs here or send at support@onlyoffice.com

**Comment by greavette** [comment]
Hello @JohnPerkin , really appreciate your help.

I've confirmed that I've added the Nextcloud server address to the field 'Server address for internal requests from the Document Editing Service'.  

I have some more information for you while I try and gather the logs.  I've noticed that I have warnings and error issues on Chrome.  I've opened my Nextcloud in Firefox and didn't have the same warning and error problems.  Are you aware of problems with Chrome?

I will try to get the logs to you for further investigation.

Thank you.

**Comment by raphson93** [comment]
@greavette 

Hi, it happened on firefox too.

**Comment by ilvolodel** [comment]
Hi same here. I have also imported my CA root using fresh update

**Comment by LinneyS** [comment]
Could you please specify if the problem recurs

**Comment by LinneyS** [comment]
This issue was closed due to no response.

**Comment by kambar** [comment]
Hello everybody
first of all thanks for great job with everything related to ONLYOFFICE! I have similar problem as of (error message with sth like 'you cannot save your changes' and then there is a save as menu opened but after closing menu everything works as expected, save works. Happened on docker after getting newest openoffice:latest image. Same setup worked fine with some older version of docker openoffice image. Sounds like the bug mentioned above but this bug/thread is closed? Could you reopen? I can provide some more data if above repro steps are not enough to reproduce. Best regards!
