### ISSUE TITLE
The file cannot be accessed right now.

### ISSUE THREAD

**Issue by conradjones** [ONLYOFFICE/onlyoffice-owncloud#78]
I get the message "The file cannot be accessed right now." message all the time. I have a spreadsheet open I can make a few edits then it doesn't autosave, the save button does nothing then I get this message.

I installed using the NextCloud VM install script here https://github.com/nextcloud/vm following the instructions.

OnlyOffice was installed via docker using this script.

**Comment by JohnPerkin** [comment]
Hello @conradjones 
You may follow this [instruction](https://doc.owncloud.org/server/latest/admin_manual/configuration_server/logging_configuration.html) to set logs level to 0. Then post logs here or send at support@onlyoffice.com

**Comment by LinneyS** [comment]
Could you please specify if the problem recurs or we can close the topic.
