### ISSUE TITLE
Applications folder already exists

### ISSUE THREAD

**Issue by jaricek** [ONLYOFFICE/onlyoffice-owncloud#8]
Hi,
I have this issue when I enable ONLYOFFICE ....  this notice show me below button ENABLE

> Applications folder already exists

 I am using owncloud 9.1.4 (stable). I have downloaded app to folder /owncloud/apps/onlyoffice

**Comment by ibnpetr** [comment]
Hello 
The issue is similar to [this one](https://github.com/owncloud/documentation/issues/826) 
Please remove and install the application again
