### ISSUE TITLE
Support Encryption without Master Key

### ISSUE THREAD

**Issue by CordlessWool** [ONLYOFFICE/onlyoffice-owncloud#80]
Hi,

I see it is now supported encryption with master key. Will there be any option to support encrypted nextcloud instances without master key in near future or why is it only supported with master key?

Because there are other plugins like draw.io, encryption is no problem.
Thanks

**Comment by LinneyS** [comment]
Hello
The ONLYOFFICE Document Server can not access the file without authorization.
But with the master key everything works.

In other plugins, the file is downloaded from the browser, not the server.

**Comment by LinneyS** [comment]
#26
