### ISSUE TITLE
Onlyoffice app disappears after updating from 1.0.5 to 1.1.2

### ISSUE THREAD

**Issue by danielepercivaldi** [ONLYOFFICE/onlyoffice-owncloud#84]
Ubuntu 14.04
ownCloud 9.1.6

After updating from 1.0.5 to 1.1.2 the onlyoffice app disappear from the list. I guessed its folder does not exist anymore in apps folder ...
I tried to install it manually (getting the zip and unpacking it in apps folder) but it does not appear in the list of available apps.
For now, restored version 1.0.5.

**Comment by andyforceno** [comment]
Ubuntu 14.04, ownCoud 9.1.6
I can confirm both that it disappears, and manually installing it doesn't fix it. However, 1.0.5 doesn't show up either, now. I double-checked permissions on apps/onlyoffice, too.

**Comment by danielepercivaldi** [comment]
Hi.
Version 1.1.3 fixed the problem.

Thank you.

**Comment by andyforceno** [comment]
Yes, 1.1.3 fixes it. Thank you!

**Comment by LinneyS** [comment]
I assume that the problems were related to the publication of the application in the marketplace
