### ISSUE TITLE
Could not save file to owncloud and read-only files are editable

### ISSUE THREAD

**Issue by dnviti** [ONLYOFFICE/onlyoffice-owncloud#85]
Hi all!
I'm trying to integrate this great piece of software that is OnlyOffice with OwnCloud and i'm having 2 major issues:

The first (that i resolved) is that under HTTPS i couldn't save any file to filesystem.
This was the incriminating piece of code:
```
if (($newData = file_get_contents($url))) {
    $this->userSession->setUser($this->userManager->get($users[0]));
    $file->putContent($newData);
    $error = 0;
}
```
Replacing `file_get_contents($url)` with `file_get_contents($url, false, stream_context_create(array('ssl' => array('verify_peer' => false, 'verify_peer_name' => false)` made things working with SSL also.

The last but not least problem i encountered is: if i share a read-only file with owncloud, the user that opens the file can also edit it, it should not though because the file is read-only.

I tried editing the code like below following the OwnCloud API Docs but nothing changes if i put the `if ($file->isUpdatable())` or not
```
if ($file->isUpdatable()){
    if (($newData = file_get_contents($url, false, stream_context_create(array('ssl' => array('verify_peer' => false, 'verify_peer_name' => false)))))) {
        $this->userSession->setUser($this->userManager->get($users[0]));
        $file->putContent($newData);
        $error = 0;
    }
}else{
    $error = 1;
}
```

**Comment by dnviti** [comment]
Please help, we need this functionality.

**Comment by LinneyS** [comment]
Turning off certificate verification is not the best solution. It is necessary to understand what is wrong with verifying the certificate.
The second issue is fixed.

**Comment by dnviti** [comment]
Thank you!

**Comment by dnviti** [comment]
Thanks for the fix.
I'm goind to try with certificate validation, our certificates are bought from DigiCert, i do not understand why they are not succesfully verified by PHP...

**Comment by ibnpetr** [comment]
@dnviti The similar issue is described [here](https://github.com/ONLYOFFICE/onlyoffice-owncloud/issues/25).
Please try adding the DigiCert certificate to the ca-certificates 
Also try adding the intermediate certificate to the Document Server (described [here](https://github.com/ONLYOFFICE/Docker-DocumentServer/issues/54))

**Comment by LinneyS** [comment]
Please try the following:
open the **ownCloud** config file _/owncloud/config/config.php_ 
and insert a section to it:
`'onlyoffice' => array (
    'verify_peer_off' => TRUE
)`
