### ISSUE TITLE
open doc with onlyoffice front panel

### ISSUE THREAD

**Issue by albama** [ONLYOFFICE/onlyoffice-owncloud#87]
i want open files doc,xls with onlyoffice in the windows of nextcloud its possible ?
if i open doc now download it but not see into nextcloud

**Comment by LinneyS** [comment]
ODT, ODS, ODP, DOC, XLS, PPT, PPS, EPUB, RTF, HTML, HTM formats can be converted to Office Open XML format. The conversion call is available from the context menu of the file.
