### ISSUE TITLE
Conversion error & WebSocket:500

### ISSUE THREAD

**Issue by emresaracoglu** [ONLYOFFICE/onlyoffice-owncloud#89]
Hi,
I want to update the Onlyoffice section in the Nextcloud admin panel but I getting this error:

> Error when trying to connect (Error occurred in the document service: Conversion error)

Also, when I want to view the document I get 500 errors.

`sockjs.min.js:2 WebSocket connection to 'wss://words.cloudSite.com/2017-07-03-16-54/spellchecker/doc/3209391499760430/c/370/1nmr0xdq/websocket' failed: Error during WebSocket handshake: Unexpected response code: 500`

What could be the reason for these?
Thank you.

**Comment by realkot** [comment]
Describe you system, W\o it nobody can help u.

PS. Check the forwarding rules in apache\nginix rules.
As example 4apache:

``
	### setup the proxy	###
	SSLProxyVerify none 
	SSLProxyCheckPeerCN off
	SSLProxyCheckPeerName off
	SSLProxyCheckPeerExpire off
	
	SSLEngine on
	SSLProxyEngine on
	ProxyRequests Off
	ProxyPreserveHost On
	ProxyVia full
    <Proxy *>
		Options FollowSymLinks MultiViews
		AllowOverride All
		Order allow,deny
		allow from all
	</Proxy>

	ProxyPass / https://192.168.1.50:443/
	ProxyPassReverse / https://192.168.1.50:443/
	
	### WEBSOCKET PROXY ###
	RewriteEngine on
	RewriteCond %{HTTP:UPGRADE} ^WebSocket$ [NC]
	RewriteCond %{HTTP:CONNECTION} ^Upgrade$ [NC]
	RewriteRule .* wss://192.168.1.50%{REQUEST_URI} [P]
	
	### LOCATION OF CERT FILES ###
	SSLCertificateFile /etc/letsencrypt/live/fullchain.pem
	SSLCertificateKeyFile /etc/letsencrypt/live/privkey.pem
	Include /etc/letsencrypt/options-ssl-apache.conf
``

**Comment by alexanderonlyoffice** [comment]
Hello @emresaracoglu,

The possible reason of the problem can be the following: 
1) Spellchecker service is not running;
2) Websockets are not being proxied; 
3) Functioning of websockets is being violated by antivirus.

Could you please specify if the issue still exists.

**Comment by emresaracoglu** [comment]
Yes, I solved this issue,
 thank you.
