### ISSUE TITLE
Getting "Error, download failed" message

### ISSUE THREAD

**Issue by onny** [ONLYOFFICE/onlyoffice-owncloud#9]
Hey Onlyoffice-Team,
I was getting quite far in setting up onlyoffice with my Nextcloud instance.
![2017-03-01-155916_swaygrab](https://cloud.githubusercontent.com/assets/757752/23465331/39d0a918-fe98-11e6-980c-28dc30a3deba.png)
But somehow the onlyoffice app is unable to load the document :/
Here are some crucial parts of the Firefox network log:

Websocket get:
```GET /2017-02-17-15-53/spellchecker/doc/4478641488380209/c/215/frluq0vg/websocket HTTP/1.1
Host: office.example.com
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:51.0) Gecko/20100101 Firefox/51.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Sec-WebSocket-Version: 13
Origin: https://office.example.com
Sec-WebSocket-Extensions: permessage-deflate
Sec-WebSocket-Key: PQOr/14uoy5wJdOp0rYxMQ==
DNT: 1
Connection: keep-alive, Upgrade
Pragma: no-cache
Cache-Control: no-cache
Upgrade: websocket
```
Webscoket Response
```HTTP/1.1 101 Switching Protocols
Server: nginx
Date: Wed, 01 Mar 2017 15:01:44 GMT
Connection: upgrade
Upgrade: websocket
Sec-WebSocket-Accept: P92tKIk4jJ9h48XUTymOd15lCTk=
```
Thats it, nothing further in this case.

Querying the info file works, as far as I can see:
```GET /2017-02-17-15-53/spellchecker/doc/4478641488380209/c/info?t=1488380505819 HTTP/1.1
Host: office.example.com
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:51.0) Gecko/20100101 Firefox/51.0
Accept: */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Referer: https://office.example.com/2017-02-17-15-53/web-apps/apps/documenteditor/main/index.html?_dc=2017-02-17-15-53&lang=en-US&customer=ONLYOFFICE&frameEditorId=iframeEditor
DNT: 1
Connection: keep-alive
```
Response header
```HTTP/2.0 200 OK
Access-Control-Allow-Origin: *
Cache-Control: no-store, no-cache, no-transform, must-revalidate, max-age=0
Content-Encoding: gzip
Content-Type: application/json; charset=UTF-8
Date: Wed, 01 Mar 2017 15:01:44 GMT
Server: Caddy
Vary: Accept-Encoding, Origin, Accept-Encoding
Content-Length: 102
X-Firefox-Spdy: h2
```
Response content (JSON)
```websocket: true
origins: {
0: "*.*"
}
cookie_needed: false
entropy: 54859483
```
If you could get me any hint to further debug this issue, I would be really happy :)

Best regards,
Jonas

**Comment by JohnPerkin** [comment]
Hello!
The previous version of the app was incompatible with Nextcloud. Please check if the issue doesn't appear in the current version 1.0.1.
Thank you for the interest in our product.

**Comment by nopeee535** [comment]
did you renamed the folder to onlyoffice (in the apps folder)?

cd apps/
git clone https://github.com/ONLYOFFICE/onlyoffice-owncloud.git onlyoffice

**Comment by onny** [comment]
Hey, thank you for your support. Today I tried the latest version:
```
git clone https://github.com/ONLYOFFICE/onlyoffice-owncloud.git onlyoffice
```
But still the same error :(
I guess the error is somewhere between my (https://caddyserver.com/)[Caddy] SSL-Proxy and the docker container ... I guess I have to further check the ssl websocket connection.

**Comment by JohnPerkin** [comment]
Hello!
According to your Candy SSL configuration, Document Server container is listening to the port 9980. Unfortunately current version of document editors does not support custom ports. This function will be available in the new version 4.3.0. We will inform about its release in our [Changelog](https://github.com/ONLYOFFICE/DocumentServer/releases).
Feel free to contact us here if you will have any questions or suggestion.

**Comment by onny** [comment]
According to your docker container, a setup with different port seems to be supported? https://hub.docker.com/r/onlyoffice/documentserver/#running-onlyoffice-document-server-on-different-port

**Comment by JohnPerkin** [comment]
Hello!
Unfortunately the information from hub.docker.com is outdated as old versions of Document Server supported listening to custom ports. But in the 4.3 this option will be resumed.
Thank you for the attention to our product.

**Comment by onny** [comment]
Is ssl port supported? I now tried to run the docker server like this:
```
docker run -i -t -d -p 443:443 -v /home/onny/app/onlyoffice/DocumentServer/data:/var/www/onlyoffice/Data onlyoffice/documentserver
```
And visiting "office.example.com" looks fine so far
![2017-03-08-003333_swaygrab](https://cloud.githubusercontent.com/assets/757752/23683043/26675044-0397-11e7-9ea4-f5af515eee04.png)
I further updated the Caddyfile for the SSL proxy
```
office.example.com {
        log /var/log/caddy/office.example.com_access.log {
                rotate {
                        size 50 # Rotate after 50 MB
                }
        }
        gzip
        tls user@example.com
        proxy / https://http-new.pi:443 {
                insecure_skip_verify
                websocket
                header_upstream Host {host}
                header_upstream X-Real-IP {remote}
                header_upstream X-Forwarded-Proto {scheme}
                header_downstream -Server ""
        }
}
```
Unfortunately the same error messages in Nextcloud :(
Firefox tells me:
```
Firefox can’t establish a connection to the server at wss://office.example.com/2017-02-17-15-53/doc/4478641488380209/c/318/lc22okxa/websocket.
Firefox can’t establish a connection to the server at wss://office.example.com/2017-02-17-15-53/spellchecker/doc/4478641488380209/c/018/4ttuzjfa/websocket.
```
Caddy also has problems:
```
08/Mar/2017:00:30:26 +0100 [ERROR 502 /2017-02-17-15-53/spellchecker/doc/4478641488380209/c/975/fwdbd0hb/xhr] net/http: request canceled
08/Mar/2017:00:30:26 +0100 [ERROR 502 /2017-02-17-15-53/doc/4478641488380209/c/331/4vgreu1d/xhr] net/http: request canceled
```
Still some kind of websocket problem?
Thanks for your help!

**Comment by JohnPerkin** [comment]
Hello!
Document Server supports running over SSL. You may see configuration of SSL proxy in the example of [nginx](https://github.com/ONLYOFFICE/document-server-proxy/blob/master/nginx/proxy-https-to-http.conf) configuration and compare it to your configuration file.

**Comment by JohnPerkin** [comment]
Hello @onny!
Documents Server 4.3 is released. How to change its port to custom you may see on our [helpcenter](http://helpcenter.onlyoffice.com/server/docker/document/docker-installation.aspx#Installing).

**Comment by onny** [comment]
Thank you for the support.
I tested the latest OnlyOffice document server version (according to docker hub: 4.3.2.3) and the issue is still not solved for me :( I'm still getting the error message ```download failed```.
Thats how I launch the document server:
```
docker run -i -t -d -p 9980:80 onlyoffice/documentserver
```
Thats my SSL proxy configuration (caddy):
```
office.example.com {
        log /var/log/caddy/office.example.com_access.log {
                rotate {
                        size 50 # Rotate after 50 MB
                }      
        }      
        gzip   
        tls test@example.com
        proxy / http://http-new.pi:9980 {
                websocket
                header_upstream Host {host}
                header_upstream X-Real-IP {remote}
                header_upstream X-Forwarded-Proto {scheme}
                header_downstream -Server ""
        }      
}
```
I'm using ```firefox 53.0``` and also tried it with ```chromium 58.0.3029.81```

**Comment by onny** [comment]
Strange, whats up with that? ```https://office.example.com/web-apps/apps/api/documents/```
![2017-04-22-120338_swaygrab](https://cloud.githubusercontent.com/assets/757752/25303465/cdf2a752-2753-11e7-9b7c-cae306fe848c.png)

**Comment by onny** [comment]
Manually querying the websocket connecting:
```
curl --insecure --include --no-buffer \
       --header "Connection: Upgrade" \
       --header "Upgrade: websocket" \
       --header "Sec-WebSocket-Key: nhEQybZ+YP/lQU67JZwA2Q==" \
       --header "Sec-WebSocket-Version: 13" \
       https://office.example.com/2017-04-14-08-31/spellchecker/doc/4621071492851644/c/875/o240n0wn/websocket
```
Seems to work fine 
```
HTTP/1.1 101 Switching Protocols
Server: nginx
Date: Sun, 23 Apr 2017 07:59:39 GMT
Connection: upgrade
Upgrade: websocket
Sec-WebSocket-Accept: lIS+Mb2i9mounKstO3r+qy6S+gM=

o
```
Connection keeps open some seconds. Then:
```
$c[3000,"No response from heartbeat"]èNormal closure
```

**Comment by onny** [comment]
I've checked out the nginx.error.log inside the docker container. Opening a document in Nextcloud triggers following error messages:
```
2017/04/28 16:34:25 [crit] 406#0: *5 connect() to [::1]:8000 failed (99: Cannot assign requested address) while connecting to upstream, client: 10.25.0.102, server: , request: "GET /2017-04-26-13-21/doc/4621071492851644/c/207/r0wd2wsd/websocket HTTP/1.1", upstream: "http://[::1]:8000/doc/4621071492851644/c/207/r0wd2wsd/websocket", host: "office.example.com"
2017/04/28 16:34:27 [crit] 406#0: *9 connect() to [::1]:8080 failed (99: Cannot assign requested address) while connecting to upstream, client: 10.25.0.102, server: , request: "GET /2017-04-26-13-21/spellchecker/doc/4621071492851644/c/391/lwvzn5ah/websocket HTTP/1.1", upstream: "http://[::1]:8080/doc/4621071492851644/c/391/lwvzn5ah/websocket", host: "office.example.com"
```
I'm not sure what this means. I can tell that no process is listening on port 8000 nor port 8080 :(

**Comment by onny** [comment]
I've updated the nextcloud app and the documentserver to following versions:
* Documentserver (docker): 4.4.1.38 (05.07.17)
* Nextcloud app version: 1.1.3
I started the document server via docker like this:
```
docker run -i -t -d -p 9980:80 -v /app/onlyoffice/DocumentServer/logs:/var/log/onlyoffice onlyoffice/documentserver
```
I tried out the new configuration parameters like this:
```
Document Editing Service address = https://office.<SERVER-ADDR>/
Document Editing Service address for internal requests from the server = http://127.0.0.1:9980/
Server address for internal requests from the Document Editing Service = http://127.0.0.1:9980/
```
Unfortunately I get a new error when trying to save the settings:
```
Error when trying to connect (Error occurred in the document service: Error while downloading the document file to be converted.)
```

**Comment by jorgedlcruz** [comment]
I'm having the same exact issue, using SSL and such, why is trying to connect using the 8000 port? How can I change that?

**Comment by jorgedlcruz** [comment]
I've found that the port 8000 is running inside the onlyoffice docker image:
```
tcp6       0      0 :::8000                 :::*                    LISTEN      -                off (0.00/0/0)
tcp6       0      0 :::5672                 :::*                    LISTEN      -                off (0.00/0/0)
tcp6       0      0 :::8080                 :::*                    LISTEN      -                off (0.00/0/0)
tcp6       0      0 :::80                   :::*                    LISTEN      437/nginx        off (0.00/0/0)
tcp6       0      0 :::4369                 :::*                    LISTEN      -                off (0.00/0/0)
tcp6       0      0 :::443                  :::*                    LISTEN      437/nginx        off (0.00/0/0)
tcp6       0      0 :::8126                 :::*                    LISTEN      -                off (0.00/0/0)
```
So for now I've tried to map that port to the outside when deploying the docker image, still not success, maybe it's something to do with docker and ipv6, let me check.

**Comment by jorgedlcruz** [comment]
I am convinced that after enable IPv6 on Docker, and redeploy the container, with an IPv6 and IPv4 this will work, but I can't make IPv6 work on my end.

**Comment by jorgedlcruz** [comment]
Whoa! Is working, multiple things I've done not sure what of them works, if not all:
- Created my own network with IPv6 and assigned to the new container with --network=onlyoffice
- On the container I needed to edit /etc/hosts to know the main Nextcloud server, as example docs.domain.com to the Container Host IP 172.18.0.1 on my case, the docker container is 172.18.0.2
- Which goes to the third part, on the Nextcloud configuration, on the second option "Document Editing Service address for internal requests from the server " I've added: http://172.18.0.2:8000/

And everything works like a charm, again, not sure what of all of them fixes this issue, try them :)

**Comment by onny** [comment]
Hey thanks for the info. I edited the hosts file and used the internal IP in the config field "Document Editing Service address for internal requests from the server ". It applied the settings without any error :)
But still the same error (but no error in nginx error log).
I could see that on the docker image, there's no ipv6 running so I also would like to try that out. Can you explain that part a bit more?

**Comment by jorgedlcruz** [comment]
Hi Onny,
Basically I did 
`
12 | docker network create --ipv6 --subnet=w:x:y:z:aaaa::/80 onlyoffice net.ipv6.conf.eth0.proxy_ndp=1
-- | --
`
And then
sudo docker run -itd -p 0.0.0.0:8443:443 --network=onlyoffice --restart=always \
    -v /app/onlyoffice/DocumentServer/cache:/var/lib/onlyoffice/documentserver/App_Data/cache/files  \
    -v /app/onlyoffice/DocumentServer/logs:/var/log/onlyoffice  \
    -v /app/onlyoffice/DocumentServer/data:/var/www/onlyoffice/Data onlyoffice/documentserver

**Comment by onny** [comment]
Still no success :(

**Comment by jorgedlcruz** [comment]
What are the errors now ? Not only in nginx, but in the other log folders you can see what's going on.

**Comment by onny** [comment]
I'm going to build documentserver from source and package it for ArchLinux https://aur.archlinux.org/packages/onlyoffice-documentserver I guess that will be useful for better debugging in the future

**Comment by alexisrosano89** [comment]
Hello @onny could you resolve that problem??

I am with the same problem since two days.

Regards!

**Comment by onny** [comment]
@alexisrosano89:
Yes I solved the problem for me. I made a build script for the documentserver and installed it on my ArchLinux server: https://aur.archlinux.org/packages/onlyoffice-documentserver/
So I didn't have to use the docker image and could debug it more easily. I further wrote a short instruction here: https://wiki.archlinux.org/index.php/Onlyoffice_Documentserver

Best regards,
Jonas

**Comment by alexisrosano89** [comment]
Ah, okey.

I'm running in Ubuntu :(

**Comment by agolybev** [comment]
Hi @alexisrosano89!
What is your problem? We'll solve it easier if we start at the begin.

**Comment by alexisrosano89** [comment]
Ok.

I could install de OnlyOffice Docker image in: http://localhost:8080, but I'am receiving that error:

![39d0a918-fe98-11e6-980c-28dc30a3deba](https://user-images.githubusercontent.com/4732738/32336237-8adb8e26-bfcd-11e7-96ad-b42944e248d9.png)

NextCloud Log saids:

“CommandRequest on check error: Error occurred in the document service: Error while downloading the document file to be converted.”

Nextcloud is installed in: http://localhost/nextcloud

Do you know what I am missing?

Regards!

**Comment by agolybev** [comment]
@alexisrosano89, thanks for details.
I think when you open a file in the NextCloud, it pass the link to the file into documentserver. In you case it will be like a http://localhost/nextcloud/.../file-name.ext. Inside the documentserver container it will be local link, because container has own `localhost`.
Try entering to NextCloud by dns name or non-local ip. Also use dns name or non-local ip in documentserver url.

**Comment by alexisrosano89** [comment]
Ok, @agolybev  thanks for your answer, I understand.

So I have to buy a domain name for that testing purpose?

**Comment by agolybev** [comment]
@alexisrosano89, sorry I wasn't so accurate. I meant loopback ip instead local ip. 
You could use LAN dns-name or ip.

**Comment by alexisrosano89** [comment]
Hello!

Now I get "CommandRequest on check error: Error occurred in the document service: Conversion error"

**Comment by agolybev** [comment]
Hi @alexisrosano89, Could you clarify when the error occurs?
If you've got it when you apply Document Server address, ensure that address is accessible for the user browser and from the ownCloud/Nextcloud server.

**Comment by alexisrosano89** [comment]
Thanks again for your help @agolybev.

My question is, do you know how can I set an FQDN to my docker image of document server?

**Comment by jorgedlcruz** [comment]
Hello, I've shared it here before, but if you follow this instructions you will be ready to go - https://www.jorgedelacruz.es/2017/07/17/onlyoffice-instalando-onlyoffice-document-server-sobre-contenedor-docker-dentro-de-una-instancia-nextcloud/

**Comment by alexisrosano89** [comment]
Thanks for your answer Jorge, but this tutorial does not work for me :-1:

**Comment by alexisrosano89** [comment]
My NextCloud configuration:

![screenshot-2017-11-8 administracion - nextcloud](https://user-images.githubusercontent.com/4732738/32571776-65c41fb6-c4a7-11e7-9dde-1c4137ba0b91.png)

When I edit the /etc/hosts from the docker image:

![screenshot from 2017-11-08 16-52-30](https://user-images.githubusercontent.com/4732738/32571884-b8f7c6b0-c4a7-11e7-9cb5-14a4028dd505.png)

When I inspect the docker container:

![screenshot from 2017-11-08 17-06-46](https://user-images.githubusercontent.com/4732738/32571783-6d5e0002-c4a7-11e7-817a-e9a4f609c7f7.png)

**Comment by agolybev** [comment]
Hi @alexisrosano89, Try removing second url for document server in NextCloud configuration page, also I think that url has wrong port number. You've ran document server on 8080 port.

**Comment by ExaconAT** [comment]
Hello! I'm working on the following scenario since yesterday:
 
                                   Public IP
                               Haproxy Cluster (https)
                          IIII     2 Internal IP's  (http) IIII
Nextcloud VM (Apache2)     Onlyoffice Documentserver VM (Nginx)

I've managed to include the Documentserver in Nextcloud.
But now i've got a similar problem:

![error](https://user-images.githubusercontent.com/33482537/33366643-2771a968-d4ec-11e7-9fc0-f47faf2011ce.jpg)

**Comment by ibnpetr** [comment]
Hello 
"Herunterladen ist fehlgeschlagen" means that your Document Server doesn't have access to the storage (Nextcloud)
Please specify the settings in the Nextcloud's admin panel
Try using the internal addresses in the advanced settings.
![admin - nextcloud](https://user-images.githubusercontent.com/16033936/33373836-af8935dc-d514-11e7-9a2e-8dbc96b20dc4.png)

**Comment by ExaconAT** [comment]
Hello thanks for your reply:

![hosts](https://user-images.githubusercontent.com/33482537/33374935-75284d4e-d508-11e7-89b1-74c5f63a8f16.png)


![config_oo](https://user-images.githubusercontent.com/33482537/33374941-7a4118b0-d508-11e7-80f5-52ae5969a665.png)

**Comment by ibnpetr** [comment]
"Error while downloading the document file to be converted" - Document Server still doesn't have access to the storage
Your NC address http://internal-nc.local should be accessible from the server with ONLYOFFICE otherwise the documents cannot be downloaded.
What does wget http://internal-nc.local show?
Do you see any errors in the NC log?

**Comment by ExaconAT** [comment]
**WGET**
302 Found
HTTP-Anforderung gesendet, warte auf Antwort... 200 OK
Länge: 7353 (7,2K) [text/html]
In »»index.html«« speichern.

index.html                               100%[=================================================================================>]   7,18K  --.-KB/s    in 0s

2017-11-29 14:26:42 (213 MB/s) - »index.html« gespeichert [7353/7353]

**LOG**
Error | onlyoffice | CommandRequest  on check error: Im Dokumentenservice ist ein Fehler aufgetreten: Error  while downloading the document file to be converted.
-- | -- | --

**Comment by onny** [comment]
@ExaconAT: Try changing the output language of your commands in the terminal, e.g. using this command:
```
export LC_ALL="C"
wget http://example.com
```

**Comment by ExaconAT** [comment]
Hello, i've manged to fix it. Had to point the two Domains internally on the HAProxy IP.

**Comment by bkakadiya** [comment]
Just downloaded java sample. Uploaded file and tried to Open or Edit. And getting 
![image](https://user-images.githubusercontent.com/1933579/43341228-d2a31f9c-91ac-11e8-8f73-2ef30e7032d3.png)

Investigated further and it seems like following are not present while requesting document

 url: "<%= Model.GetFileUri() %>",                        
key: "<%= Model.GetKey() %>",

And surprisingly Model which is of type FileModel.java doesn't have those property at all.
My guess it has to be set somewhere in EditorServlet.java before forwarding it to editor.jsp.

**Comment by LinneyS** [comment]
Initial issue resolved
For other requests, open a new one.

**Comment by liuwenchang** [comment]
donot use 127.0.0.1 or localhost，use real ip

**Comment by marcellopato** [comment]
Hello, I am stuck at the same point. I can upload a file, but can't download it.
I am on macos High Sierra, running the ONLYOFFICE DOCKER image downloaded from Docker Hub.
Let's see some code from the response:

`{
	"response": 200,
	"data": {
		"config": {
			"type": "desktop",
			"documentType": "text",
			"document": {
				"title": "16323195dd440b.docx",
				"url": "http://192.168.15.16:8080/guard/API/office/Storage/Documents/163234ad367c8d.docx?a=163234b2b580b0",
				"fileType": "docx",
				"key": "785998973",
				"info": {
					"owner": "Me",
					"updated": "15.09.22"
				},
				"permissions": {
					"comment": true,
					"download": true,
					"edit": true,
					"fillForms": true,
					"modifyFilter": true,
					"modifyContentControl": true,
					"review": true
				}
			},
			"editorConfig": {
				"mode": "edit",
				"lang": "en",
				"callbackUrl": "http://192.168.15.16:8080/guard/API/office/webeditor-ajax.php?type=track&fileName=163234ad367c8d.docx&userAddress=host.docker.internal",
				"user": {
					"id": 0,
					"name": ""
				},
				"embedded": {
					"saveUrl": "http://192.168.15.16:8080/guard/API/office/Storage/Documents/163234ad367c8d.docx",
					"embedUrl": "http://192.168.15.16:8080/guard/API/office/Storage/Documents/163234ad367c8d.docx",
					"shareUrl": "http://192.168.15.16:8080/guard/API/office/Storage/Documents/163234ad367c8d.docx",
					"toolbarDocked": "top"
				},
				"customization": {
					"about": true,
					"autosave": false,
					"feedback": true,
					"zoom": -2
				}
			}
		},
		"history": null,
		"historyData": null,
		"path": "/16323195dd440b.docx"
	}
}`

This is the response from Firefox inspector tab. I tryed to reach the URL right on the browser and the response was:

`Cannot GET /guard/API/office/Storage/Documents/163234ad367c8d.docx`

Am I missing something? Any ideas?
Thanks in advance!

**Comment by silasrm** [comment]
I'm solving creating a redirection inside `/etc/nginx/conf.d/ds.conf`:
```sql
server {
	listen 9010;
	listen [::]:9010;

	server_name _;

	root /var/www/html;

	# Add index.php to the list if you are using PHP
	index index.html index.htm index.nginx-debian.html;


	location / {
		rewrite ^/?(.*)$ /$1 break;    
	    proxy_pass  http://localhost;
	    proxy_set_header Host $host;
	    proxy_set_header X-Real-IP $remote_addr;
	    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	}
}
```

9010 is my external port.
