### ISSUE TITLE
Document Server address for ONLYOFFICE PERSONAL

### ISSUE THREAD

**Issue by deljones** [ONLYOFFICE/onlyoffice-owncloud#90]
Does anyone know what the address is for the Document Server address.

I have the ONLYOFFICE app installed on my NC12 instance and my account has been created on ONLYOFFICE PERSONAL. I can create doc there and the do appear correctly in NC. However in order to do it the other way NC > OOP I need the document server address entered into the NC app settings.

Has anyone connected NC12 to OOP successfully?

Del

**Comment by ibnpetr** [comment]
Hello 

> I need the document server address entered into the NC app settings.

Your NC12 instance should be connected to your [own](http://helpcenter.onlyoffice.com/server/document.aspx) ONLYOFFICE Document Server instance.
ONLYOFFICE PERSONAL cannot be used for the integration with your NC

**Comment by deljones** [comment]
OK... So it working in one direction, OOP > NC12 is normal?

Del

**Comment by ibnpetr** [comment]
> OOP > NC12 is normal?

Yes you can connect your NC account to your ONLYOFFICE PERSONAL.
But you cannot integrate ONLYOFFICE PERSONAL document editing service into any third party application

**Comment by deljones** [comment]
Very good Alex... Thanks for the clarification

Derek



------ Original Message ------
