### ISSUE TITLE
Code signing exception in OC 10.0.2

### ISSUE THREAD

**Issue by svengit** [ONLYOFFICE/onlyoffice-owncloud#91]
there should be proper signature data

- onlyoffice
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
		- Signature data not found.

**Comment by LinneyS** [comment]
Hi @svengit 
The source code of the repository does not contain a signature file.
Take the signed app from the page with the [release](https://github.com/ONLYOFFICE/onlyoffice-owncloud/releases) or from the official [application store](https://marketplace.owncloud.com/apps/onlyoffice)

**Comment by svengit** [comment]
Hi @LinneyS,
it would be nice to change the 'Installing ownCloud/Nextcloud ONLYOFFICE integration app' part in the README.md then. It clearly states to use 'git clone'.

Best regards

**Comment by LinneyS** [comment]
thx
