### ISSUE TITLE
Error language parameter for Chinese

### ISSUE THREAD

**Issue by wohenbushuang** [ONLYOFFICE/onlyoffice-owncloud#93]
Nextcloud 12, latest app. The `lang` parameter should be `zh`, `zh-CN` instead. So it cannot fetch `zh-CN.json` with 404 and the translation remain English.

BTW, I still cannot find the way to add Chinese fonts on document server, useless with `/usr/bin/documentserver-generate-allfonts.sh`

**Comment by wohenbushuang** [comment]
Maybe because that the code value for Nextcloud language preference is just `zh-CN`

**Comment by ibnpetr** [comment]
Hello 
Thanks, we will fix this issue with lang parameter in the next version.
Could you please describe the problem with Chinese fonts on document server.

**Comment by ibnpetr** [comment]
@wohenbushuang 
Update: The issue has been fixed in the version 4.4 
Please specify version of the Document Server

**Comment by LinneyS** [comment]
Fixed
