### ISSUE TITLE
Cross domain errors. Same server installation [Nextcloud][Centos7]

### ISSUE THREAD

**Issue by Proch92** [ONLYOFFICE/onlyoffice-owncloud#94]
Hi, this is my setup:
Apache that serves nextcloud on port 80.
nginx ssl reverse proxy -> localhost:8080 (docker 8080->80) (onlyoffice community server docker image)
https://external-ip/ -> nginx -> localhost:8080 -> docker -> onlyoffice:80

nextcloud is configured to search for onlyoffice at https://external_ip/

I can access https://external_ip/ and it works, but when i try to edit a file from nextcloud it gives me a blank page with those errors:

![image](https://user-images.githubusercontent.com/1202862/28724162-6a092c40-73b9-11e7-8933-cc39c1dee9e1.png)

the blank page:

![image](https://user-images.githubusercontent.com/1202862/28724189-7f7d5952-73b9-11e7-8a04-0ecd5fcf168a.png)

It seems like it's a cross domain error. Do you have any idea how to fix it?

**Comment by agolybev** [comment]
Hello @Proch92,
Try to comment `add_header X-Frame-Options DENY;` string in the nginx config. Don't forget to restart nginx after that.

**Comment by Proch92** [comment]
Thanks. That was the issue.
I was looking in the wrong nginx as i thought the problem was the onlyoffice nginx (inside the docker), but the setting actually was in the nginx serving the proxy.
