### ISSUE TITLE
Unknown error

### ISSUE THREAD

**Issue by jmaris** [ONLYOFFICE/onlyoffice-owncloud#95]
Hey,

I recently installed onlyoffice using the docker image on my server.

Onlyoffice is set to run on port 8080 on localhost, and is then proxied by nginx to https://office.mysite.com. nextcloud is configured to point to that.

When i try to open a file i get Unknown Error : Press "ok" to return to document list"

any idea why this is ?

**Comment by ibnpetr** [comment]
Hello 
Could you please send us log files of the nextcloud (/data/nextcloud.log) and document server (folder /var/log/onlyoffice/documentserver/ inside the container )

**Comment by LinneyS** [comment]
Could you please specify if the problem recurs or we can close the topic.

**Comment by stone212** [comment]
@LinneyS I am having this problem also.  The precise description as jmaris, above.

Once I "mount" the container I do not find any files or directories under /var/log/onlyoffice and there is no /data directory

**Comment by alexanderonlyoffice** [comment]
@stone212, if you use Docker installation, please check /app/onlyoffice/DocumentServer/logs. 

You can download Nextcloud log in Logging section in Nextcloud by clicking action menu (three dots icon) on the top toolbar.

Please send all logs to **support@onlyoffice.com** with a note 'For technical support'.

**Comment by stone212** [comment]
@alexanderonlyoffice What is wrong with posting logs here?  Isn't this the forum for "issues"?  That seems unnecessarily difficult and unusual for an open source project.  I have just switched to Collabora in the meantime and it is working so I will come back to this if it is necessary with the hope that we can use GitHub Issues to track issues in GitHub. :)

**Comment by alexanderonlyoffice** [comment]
@stone212, you can post your logs here.

**Comment by stone212** [comment]
@alexanderonlyoffice Thank you but I simply installed Collabora and we are very happy with it.
