### ISSUE TITLE
Connection was not established between nextcloud and onlyoffice!

### ISSUE THREAD

**Issue by zenny** [ONLYOFFICE/onlyoffice-owncloud#97]
Hi,

I installed successfully onlyoffice in one of the lxc containers in the same local network (192.168.10.1) that is running nextcloud in another lxc container (192.168.10.2). But they do not seem to connect even to use internally**. Both document server and nextcloud are running, but disconnected even after appending https://192.168.10.1 in the nextcloud onlyoffice app settings for using internal purposes.

A similar error I can find in the log as described at http://dev.onlyoffice.org/ru/viewtopic.php?p=21909

Connection refused at /usr/share/nginx/nextcloud/apps/onlyoffice/lib/documentservice.php

Cheers,
/z

**without letsencrypt (a PITA), used a self-signed certificate instead for internal use.

**Comment by zenny** [comment]
Bump!

**Comment by LinneyS** [comment]
Please try the following:
open the **NextCloud** config file _/nextcloud/config/config.php_ 
and insert a section to it:
`'onlyoffice' => array (
    'verify_peer_off' => TRUE
)`

**Comment by dave7376** [comment]
LinneyS - have the same issue but with real certs on my nextcloud and onlyoffice doc server and when i add the 'onlyoffice' => array ( 'verify_peer_off' => TRUE ) to the config.php in nextcloud, nextcloud stops loading and presents me with a blank white page.
these are both fresh installs and was ok until i switched to https.

any help appreicated ?

**Comment by LinneyS** [comment]
@dave7376 
Then follow this [instruction](https://docs.nextcloud.com/server/12/admin_manual/configuration_server/logging_configuration.html) to set logs level to 0.
Re-save the settings for onlyoffice in NextCloud.
Then send logs at support@onlyoffice.com

**Comment by dave7376** [comment]
@LinneyS 
did as requested above and sent log - have since dug a little deeper and fix my issue with the cert chain so all good.
thanks for your help though.

**Comment by alexanderonlyoffice** [comment]
@zenny , could you please specify if the issue still exists.

**Comment by dave7376** [comment]
Hi Mate,

No issue is no longer thank you all sorted

Cheers

Dave

Sent from my iPhone

On 19 Oct 2017, at 22:59, alexanderonlyoffice <notifications@github.com<mailto:notifications@github.com>> wrote:


@zenny<https://github.com/zenny> , could you please specify if the issue still exists.

**Comment by zainadan** [comment]
Hi. I have integrated nextcloud with onlyoffice and enabled https. whenever I try to open a file on nextcloud I get 172.16.0.202 refused to connect.

Kindly Assist.

![image](https://user-images.githubusercontent.com/40002531/87407694-2d769300-c5cb-11ea-8865-e7c134903853.png)

**Comment by dave7376** [comment]
Hi,

Have you checked the connection and verified between each using wget?



Sent from my iPhone

On 14 Jul 2020, at 19:12, zainadan <notifications@github.com> wrote:

﻿

Hi. I have integrated nextcloud with onlyoffice and enabled https. whenever I try to open a file on nextcloud I get 172.16.0.202 refused to connect.

Kindly Assist.

[image]<https://user-images.githubusercontent.com/40002531/87407694-2d769300-c5cb-11ea-8865-e7c134903853.png>
