### ISSUE TITLE
Spreadsheet editor Co-edit is not working and the saved changes were not updated

### ISSUE THREAD

**Issue by kesavarajaphp** [ONLYOFFICE/onlyoffice-owncloud#98]
BUG

We integrated the document server V 4.4.2 with Nextcloud 12. We are facing the problem in Spreadsheet editing.

1. We uploaded a .xlsx document in nextcloud server. The document shared with 4 users. When all users open the same document and editing, the Co-edit is not working. The changes made by User A, did not updated to Other users instantly Or Later. Also the spread sheet document changes made by User A  was disappeared, when A is checking on the next day.

2. The Spreadsheet cells are showing to the same user Like Editing with red dots box, But he opens the document in only one tab and in one computer. After cleared the browser cache and checked, it disappeared and showing with the name of 'Guest' editing. 

3. "The file cannot be accessed right now" error came for all Users. 
No errors in the server log Or Nextcloud log For the above three problems, as our log level is set to 0 only. 

4. History of the Modifications were not visible in the document.
![access-error](https://user-images.githubusercontent.com/29251273/29449741-9187cfd6-8419-11e7-9dad-41437c80f50b.jpg)

Expecting : 1. When Multiple users using the Spreadsheet, We need the changes to be applied Or Updated in the spread sheet instantly Or at least after some time.
2. The Editing red box should show only when any one of the user is editing the Spreadsheet and when the user is done, it should not display the red box.
3. After the editing is done, if the user is not closing the window, the spreadsheet can be accessed to them after few minutes / Hours also.
4. If the User A is editing the document, then the user B can see the Modification time and changes made by A Like history of the document changes.

DocumentServer Version : 4.4.2,Browser : Google Chrome, Firefox

Please kindly revert back.

Thank you.

**Comment by ibnpetr** [comment]
Hello 
Can the issue also be reproduced when working with docx and pptx files?
Can the xlsx files be opened/edited/saved in a single-user mode? (can the file be downloaded from Nextcloud when the editing is completed)

**Comment by kesavarajaphp** [comment]
@ibnpetr 
Hi,
Thank you for the Reply. 
1. As we are using xlsx documents only now. We did not check the same issue in docx and pptx files.
2. Yes the xlsx files can be opened / edited /Saved in a Single-user Mode. The file can be downloaded from document editor after completed the editing. But before closing the window the file can be downloaded from Nextcloud files page, contains the Previous version of the file.
When the user closed the window and after 10 seconds the xlsx file Downloaded from nextcloud files page, it got updated and we can see the newer version.

Installation type : Linux
we followed the below link to install the document server  https://helpcenter.onlyoffice.com/server/linux/document/compile-source-code.aspx

Please help us to resolve the issue.

**Comment by ibnpetr** [comment]
@kesavarajaphp 

1. Please try working with docx and pptx files and let us know

2. > When the user closed the window and after 10 seconds the xlsx file Downloaded from nextcloud files page, it got updated and we can see the newer version.

This is how it should work by default, - the file will be updated in the Nextcloud storage in abot 10 sec after you close the editing session.

**Comment by alexanderonlyoffice** [comment]
Hello @kesavarajaphp, 

Please try to update document server to the latest version and check if the issue still exists. Please notify us about the result.

**Comment by Wizlonex** [comment]
Hi:

I see the same error.  I have onlyoffice server 18.01.172 installed in an LXD container on Ubuntu 16.04.  I access it via Nextcloud (also installed via LXD container).  Sometimes (and too many times), I get the "the file cannot be access right now" error.  If I refresh the page, it comes back.  I may or may-not lose my most recent editions (it varies).  Many times it works without errors, then they surface again for no apparent reason.

I have read that the built-in php http server may be causing a problem, but I have no way of knowing.  This error is making me reconsider using onlyoffice server (and hence onlyoffice desktop apps).

The Nextcloud install has been a solid performer and I do not suspect it is at fault (but I can't prove that).  I have no evidence to suggest my router or network is at fault either, so I suspect the issue is in the onlyoffice set-up.

I will try a fresh re-install on an alternate machine in a few weeks, but would really like to understand and fix this problem so as to restore my confidence in onlyoffice.

I am open to suggestions or ideas.  I can also post any log files etc.

V/R

Andrew

**Comment by alexanderonlyoffice** [comment]
Hello @Wizlonex,

Could you please specify the version of the document server and ONLYOFFICE connector. 

Please open browser's console (choose tab Network) and reproduce the mentioned issue. Make a screenshot, so we can see browser's console on it.  

Specify also if this issue occurs only with one particular file or with all the files.

**Comment by Wizlonex** [comment]
Hi:

Nextcloud connector app: version 1.2.0
How do I list the version number of my doc-server please?  The install was very recent (January), so my version is almost certainly the latest (installed using your official ubuntu installation method), but I will gladly provide more info if you can show me what you want.

Not sure if the attached screenshot helps...?

The error happens on editing any file.  And it's totally unpredictable: I have gone nearly an hour without seeing this, and then I sometimes see it five times in a few minutes.

![onlyoffice](https://user-images.githubusercontent.com/35621692/37389311-bb41e2b8-275b-11e8-8572-a7cb814202c6.PNG)
![onlyoffice2](https://user-images.githubusercontent.com/35621692/37389333-d311e712-275b-11e8-9391-e27fc9706063.PNG)

**Comment by alexanderonlyoffice** [comment]
@Wizlonex please send us logs of the document server and Nextcloud to **support@onlyoffice.com**. Please add a note to the email "For technical support".

You can check the version of the document server by opening any file -> '**About**' button (it is on the left toolbar).

**Comment by Wizlonex** [comment]
Of course: I forgot about that method.  Sorry.  Doc server - Version 5.0.7 CE.

Installed in an LXD container running Ubuntu 16.04.  I will gather logs and send email.

**Comment by alexanderonlyoffice** [comment]
@Wizlonex, we have received your logs. We will check them for any errors and notify you about the result.

**Comment by arnowelzel** [comment]
This affects me as well - see #164. Maybe a duplicate?

**Comment by alexanderonlyoffice** [comment]
@arnowelzel, please see #164

**Comment by alexanderonlyoffice** [comment]
Hello @Wizlonex, we found a lot of records about errors in logs. Please do the following: Go to Administration section of Nextcloud -> Click on the Save button for ONLYOFFICE address settings -> If there are any issues, open browser's console (Network tab) -> Click on the Save button once again -> Send us a screenshot.

**Comment by Wizlonex** [comment]
Hi.  No issues or errors re-saving the settings.  Did not make a difference to the error I am seeing - it happened again within minutes.  It's as if the connection is being dropped, which I don;t really understand.

Perhaps it's because I am running this as a containerized service under LXD in Ubuntu?  I will try a fresh re-install in a few weeks when I get back to my server to see if it makes a difference.  Thanks.

**Comment by Wizlonex** [comment]
The error has been eliminated.  I performed a complete re-install and the issue went away, sorry that's not a very good solution but it worked for me.  THANK YOU.
